### ISSUE TITLE
databaseId is not a parameter in function, not in input data

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#10]
https://github.com/OHDSI/CohortDiagnostics/blob/b66d84ac02b03035599d49506fbe40b8d2f30497/R/IncidenceRates.R#L263

**Comment by gowthamrao** [comment]
@schuemie 

In the current version master branch - calling function `CohortDiagnostics::plotincidenceRate(` gives the following warning message

> Warning message:
Unknown or uninitialised column: 'databaseId'

**Comment by schuemie** [comment]
I don't see that warning, and the [`!is.null`](https://github.com/OHDSI/CohortDiagnostics/blob/master/R/IncidenceRates.R#L263) should catch the fact that the column doesn't exist.

Are you sure you're on the latest version in master (or develop)?

**Comment by gowthamrao** [comment]
@schuemie i am getting this warning message in master

**Comment by schuemie** [comment]
But I am unable to reproduce it on my end, and the warning message shouldn't occur. Did you do a clean reinstall of the package (i.e. did you close all instances of R, and open only one)? 

One way to check if you're truly on the latest version is to use `debug(CohortDiagnostics::plotincidenceRate)`, and see if the code in the debugger matches the code in the repo. This will also allow you to pinpoint where the warning message occurs (as mentioned, the current code shouldn't throw the warning).
