### ISSUE TITLE
Shiny not loading, warning message: Warning: Error in dplyr::bind_rows: Argument 1 must have names.                                                        

### ISSUE THREAD

**Issue by christinaread** [OHDSI/CohortDiagnostics#1000]
Hello,

I am experiencing an issue running the Shiny viewer. When running any of the codes: "shiny::runApp()" ; "CohortDiagnostics::launchDiagnosticsExplorer(
  sqliteDbPath = "data/MergedCohortDiagnosticsData_default.sqlite")", or clicking run app in the global.r file, the shiny does not load correctly. The webpage will load but not generate any information. The following warning message appears, but there is no error and the code continues to run (without producing results) indefinitely. Thank you for your help.

Listening on http://127.0.0.1:4654
Warning: Error in dplyr::bind_rows: Argument 1 must have names.                                                        
  74: <Anonymous>
Warning: Error in dplyr::bind_rows: Argument 1 must have names.
  74: <Anonymous>

**Comment by azimov** [comment]
Hi @christinaread I will need a bit more information to debug your issue.

Firstly, which version of CohortDiagnostics are you using?

Secondly, is the path `data/MergedCohortDiagnosticsData_default.sqlite` the correct location of your output file?

Thirdly, are you sure you generated the merged sqlite database without errors? It's possible that the file itself wasn't generated correctly during your analysis steps.

**Comment by azimov** [comment]
Hi Christina, there should be a log file of the execution stored in the output folder (the `exportFolder` parameter to `executeDiagnostics`) the default name is just `log.txt`. Uploading this as a [gist](https://gist.github.com/) and attaching the link may help me see if anything went wrong.

**Comment by christinaread** [comment]
I am running the function CohortDiagnostics::launchDiagnosticsExplorer using either the zip files or the sqlite files (we tried both but neither worked) provided by the hospital, who ran the executeDiagnostics function. Is there a way for me to access a log.txt of the error when I am not the one also running executeDiagnostics?

**Comment by azimov** [comment]
@christinaread as it was someone external that ran this study, I think that you will need to contact the site to get the log file directly. There shouldn't be any patient sensitive information contained within but we can't verify this in the same way as we do for the csv files.

If you have the zip file looking at the CSV files there may be beneficial. `metadata.csv` and `executionTimes.csv` will give indications as to what was executed, what the parameters were and how long it took. This information shouldn't contain any sensitive information so you may be able to share it.

**Comment by azimov** [comment]
closed due to inactivity
