### ISSUE TITLE
Cohort selection drop down does not remember the cohort selected

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#1004]
Observed behavior:
- i go to cohort count tab, select a cohort id that i am interested in
- next go to index event breakdown and find that it is reporting on some other cohort, and i have to reselect the cohort
- next i go to cohort characterization - and it is reporting on another cohort, and i have to reselect the cohort.

Expected behavior:
- once i select the cohort, i would like it try to persist when i toggle from one diagnostics tab to another.

I am pretty sure this expected behavior existed before, i wonder if the code change to modular shiny may have impacted this behavior.

**Comment by azimov** [comment]
The reactives for these have fundamentally changed since this issue was reported - the UX of OhdsiShinyModules is under review and should gradually be improved
