### ISSUE TITLE
Mapped concept in cohort tab - maybe we need to rethink this

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#1008]
I think this UI is confusing: The purpose of this segment is to understand the usage of mapped (usually non-standard) concepts for each standard (resolved in concept set expression) in a given data source.

![image](https://user-images.githubusercontent.com/13936600/202606865-37c0b281-e13f-49ca-b9e8-c9ed567614a4.png)

e.g. in the screenshot above, i am filtering to one resolved concept id 443904 that was in the resolved concept id table. I want to see what are the mapped concepts (what are the non -standard concepts mapped to the  standard concept) AND what are the counts of the non-standard concepts in the selected data source.

But if i have a click thru experience from the resolved table itself i.e. in the resolved table, if i select a row - the mapped table appears below it, it would be much more nicer

**Comment by azimov** [comment]
Closed as this is an OhdsiShinyModules ui related issue
