### ISSUE TITLE
Mismatch between selected drop down and label

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#1012]
Observed on v3.1.0 master branch on data.ohdsi.org/PhenotypeLibrary

![image](https://user-images.githubusercontent.com/13936600/204565403-2df8aa5e-5333-4bed-92e6-25564b7a346f.png)

**Comment by gowthamrao** [comment]
To reproduce

- go to cohort counts, select the cohort 251 - review count
- now toggle to orphan concepts. the select drop down cohort is 251, label is something else

workaround:
- toggle cohort drop down

i think this is shiny reactive object for the label not resetting itself

**Comment by azimov** [comment]
i renamed this variable but I can't see a bug in the app when I test it. There is a delay for the text reloading when the app is under load though
