### ISSUE TITLE
Add percent with decimal formatting to characterization output

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#1013]
Characterization output does not have formatting

![image](https://user-images.githubusercontent.com/13936600/204611778-5e108745-d264-42c4-b364-b8bc422bb1aa.png)

here the 0.0 implies the value is some where > 0.00 but less than 0.05 i.e. between 0 to 5%
a value of 0.1 implies the value is some where > 0.05 but < 0.15

We need more precision in this table. A true value of 0.0412 should be shown 4.1%, value of 0.0643 A 6.4%, a value of 0.834 as 83.4%

**Comment by azimov** [comment]
Data now displays as a percentage when only proportional data is displayed. This table function is too complex to modify as is in a reasonable time to support both continuous and percentage variables in the way it is constructed. This change would be significant and will have to wait for a future version.

**Comment by pbr6cornell** [comment]
Jamie, could we at least start by just changing the precision on all numbers to 2 digits instead of only 1?  That way we could at least see what % in whole number.   In present form, 1 digit means the vast majority of numbers dont give us sufficient context to use to even sort the values properly.

**Comment by pbr6cornell** [comment]
Ah, perhaps i misunderstood, are you saying that restricitng to only proportions as an input will format values correctly?  % with a decimal point?  So the issue here was just not limiting the selction correctly?  If so, then that could work, but maybe 2 decimal would be a reasonable compromise in this mixed mode version
