### ISSUE TITLE
cohortTables variable referenced as cohortTableNames later in script

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/CohortDiagnostics#1025]
https://github.com/OHDSI/CohortDiagnostics/blob/6506370d84551598db50acbcf3a570d833cb599a/extras/CodeToRun.R#L39

This should be updated to 

 cohortTableNames <- CohortGenerator::getCohortTableNames()

**Comment by azimov** [comment]
Closing as this is now resolved in the develop branch
