### ISSUE TITLE
Java errors on deployed shiny app

### ISSUE THREAD

**Issue by solis9753** [OHDSI/CohortDiagnostics#1030]
Creating a DiagnosticsExplorer app is working fine locally, but on the shinyapps.io server it raises java errors when attempting to retrieve result tables. For example see below some screenshots for different functionalities of the app. 

When trying to view the characterisation table:
![Screenshot 2023-02-06 at 3 47 50 PM](https://user-images.githubusercontent.com/36792048/217014834-0682aaeb-f8b4-4f61-a8b9-eae1fa7da258.png)

When trying to view the orphan concepts table:
![Screenshot 2023-02-06 at 3 48 07 PM](https://user-images.githubusercontent.com/36792048/217014893-5f75ffd9-0af5-48d1-8f2c-d7d4f68ffd08.png)

Note that none of the tables can be viewed on the deployed shiny app, yielding similar errors as above. 

Also note that I am uploading results in an sqlite database, and as per previous suggestion Java should not be invoked. #993 

In the second screenshot, there is an error in a tryCatch statement returning a `value[[3L]]` label suggesting that there's an error when trying to read from the connection. I am suspecting that the shiny settings are not read correctly, but cannot pin point where exactly and why is the issue occurring. 

I apologise for the lack of a repro but would appreciate some pointers.

**Comment by azimov** [comment]
The shinyapps.io server should now be better supported by the latest release of OhdsiShinyModules. I am able to test on a Posit Connect platform but not the pay for use shinyapps.io as I quickly fill up the time. Please post any future shiny rekated issues over on [OHDSI/OhdsiShinyModules](https:://github.com/OHDSI/OhdsiShinyModules)
