### ISSUE TITLE
incidence_rate results csv not matching the table specification

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/CohortDiagnostics#1032]
CohortDiagnostics defines the `incidence_rate` table based on [ref](https://github.com/OHDSI/CohortDiagnostics/blob/develop/inst/settings/resultsDataModelSpecification.csv#L135-L142).

In reviewing the resulting incidence_rate.csv file, it appears that some fields are empty - for example, when producing an overall incidence rate that is not stratified by gender/age_group, you'll get something like this:

```csv
"cohort_count","person_years","gender","age_group","calendar_year","incidence_rate","cohort_id","database_id"
220227,41883569.8311,,,,5.258076159412607,10393,"-948018521"
```

I think the primary key definition of the incidence_rate table is correct and perhaps some additional formatting is required when producing the result such that an empty gender/age_group is given a designation (i.e. zero) to indicate that it is not used in that row? This is currently causing upload problems since the upload functionality in CD handles these cases by using an assumed value for these missing fields while the approach I've been working on will not make such an assumption.

**Comment by azimov** [comment]
This was related to an old issue with the primary key columns for strata and should now be resolved
