### ISSUE TITLE
Diagnostics explorer shiny app crashes seemingly at random

### ISSUE THREAD

**Issue by DrTTrousers** [OHDSI/CohortDiagnostics#1033]
``` r
Warning: Error in ._jobjRef_dollar: no field, method or inner class called 'parent' 
  100: stop
   99: ._jobjRef_dollar
   98: $.Throwable
   96: cnd_some
   95: cnd_inherits
   94: <Anonymous>
   93: stop
   92: <Anonymous>
   91: stop
   90: value[[3L]]
   89: tryCatchOne
   88: tryCatchList
   87: tryCatch
   86: do
   85: hybrid_chain
   84: renderFunc
   83: output$DiagnosticsExplorer-orphanConcepts-orphanConceptsTable
    2: shiny::runApp
    1: CohortDiagnostics::launchDiagnosticsExplorer
```

The app will launch fine, and display, however when clicking between tabs, eventually an error replaces the table views 

![image](https://user-images.githubusercontent.com/86723895/218746039-ddf66c54-b992-4e16-a509-bb0b54d413c4.png)

This renders the app useless. This is using CohortDiagnostics 3.1.2 and Shiny 1.7.4.

**Comment by azimov** [comment]
This is likely an error with the sql query but I can't tell what the cause would be. How is the application being used - is it with an sqlite or postgres database? If its postgres there could be any number of database backend issues that may cause this (e.g. user permissions on tables)

**Comment by DrTTrousers** [comment]
@azimov I've actually been bashing at this a little further since my original post - and something I experienced with strategus has shown up again.

The same script / Shiny app runs fine in Windows. The above error is collected from an Enterprise RWorkbench instance running linux.

Both cases are calling a .sqlite file created by createMergedResultsFile()

I've got a load of these error messages, so will append one below. To clarify, the shiny _kind of_ runs, but after a few clicks the error shows up.

``` r
his warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.
Error in .jcall("java/lang/Class", "Ljava/lang/Class;", "forName", cl,  : 
  RcallMethod: cannot determine object class
SELECT oc.*,
              cs.concept_set_name,
              c.concept_name,
              c.vocabulary_id,
              c.concept_code,
              c.standard_concept
            FROM  main.demo_orphan_concept oc
            INNER JOIN  main.demo_concept_sets cs
              ON oc.cohort_id = cs.cohort_id
                AND oc.concept_set_id = cs.concept_set_id
            INNER JOIN  main.demo_concept c
              ON oc.concept_id = c.concept_id
            WHERE oc.cohort_id = 10365
              AND database_id in ('DAGERMANY')
              ;
Warning: Error in ._jobjRef_dollar: no field, method or inner class called 'parent' 
  100: stop
   99: ._jobjRef_dollar
   98: $.Throwable
   96: cnd_some
   95: cnd_inherits
   94: <Anonymous>
   93: stop
   92: <Anonymous>
   91: stop
   90: value[[3L]]
   89: tryCatchOne
   88: tryCatchList
   87: tryCatch
   86: do
   85: hybrid_chain
   84: renderFunc
   83: output$DiagnosticsExplorer-orphanConcepts-orphanConceptsTable
    2: shiny::runApp
    1: CohortDiagnostics::launchDiagnosticsExplorer
```

**Comment by DrTTrousers** [comment]
I'm going to close this issue, I think it is specific to running the app from inside a linux R Workbench environment, as I've been able to get the same apps running fine on Windows and in an RSConnect server.
