### ISSUE TITLE
CohortDiagnostics does not support cohortDefinitionSet created by cohortSubsetOperator

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#1038]
The following message is seen. Probably needs the data model to support these fields

> The following fields found in the cohortDefinitionSet will be exported in JSON format as part of metadata field of cohort table:                                                   
>     isSubset,
>     subsetDefinitionId,
>     subsetParent
>  - Unexpected fields found in table cohort - subsetParent, isSubset, subsetDefinitionId. These fields will be ignored.

**Comment by gowthamrao** [comment]
https://github.com/OHDSI/CohortDiagnostics/pull/1042/commits/12437cbe0aa10d557d014c0e298954c7f0f22eaa

**Comment by azimov** [comment]
should now be resolved in released version
