### ISSUE TITLE
minor typo bug

### ISSUE THREAD

**Issue by jreps** [OHDSI/CohortDiagnostics#1047]
on line 512 in https://github.com/OHDSI/CohortDiagnostics/blob/main/R/RunDiagnostics.R

 for (subsetDef in dfs) {
      subsetDefinitions <- rbind(subsetDefinitions, dfs)
    }

should be 
 for (subsetDef in dfs) {
      subsetDefinitions <- rbind(subsetDefinitions, subsetDef)
    }

**Comment by azimov** [comment]
fixed in develop, will be released as a hotfix today
