### ISSUE TITLE
Time distribution diagnostics

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#1057]
I think it would be useful to describe the subject and event counts by time distributions binned in 30 days e.g.

0 days, < 30 days, < 60 days, < 90 days, < 120 days.. >= 360 days

- Time in days between a person’s observation start date in the data source and their cohort start date; 
- Time in days between a person’s cohort start date and cohort end date; 
- Time in days between a person’s cohort start date and the last date of continuous observation in the data source

This would help answer questions like 
- how many subjects/events had 0 days 
- how many had 30 days

**Comment by azimov** [comment]
Closing due to age: Please re-specify this diagnostic if you wish to include it in a future version. Its difficult to be sure what this would entail
