### ISSUE TITLE
Error in createMergedResultsFile

### ISSUE THREAD

**Issue by rfherrerac** [OHDSI/CohortDiagnostics#1061]
When running createMergedResultsFile getting this error 

 Assertion on 'connectionDetails' failed: Must inherit from class 'connectionDetails', but has classes 'ConnectionDetails','DefaultConnectionDetails'.

Also affecting the shiny app lunch.

**Comment by azimov** [comment]
Hi @rfherrerac this issue Is likely caused by your version of `DatabaseConnector` being old or your version of `CohortDiagnostics` being old. Please run:

```
remotes::install_github("OHDSI/CohortDiagnostics")
```

And update all available packages.
If this doesn't resolve your issue run:

```
install.packages("DatabaseConnector")
```

This should update everything to the latest versions.
