### ISSUE TITLE
Results data model DDL does not support cohort subset fields

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#1066]
https://github.com/OHDSI/CohortDiagnostics/blob/73120fe7e7736b3e3c1391a2607f4e17261cb5c5/inst/sql/sql_server/CreateResultsDataModel.sql#L107-L114

while CohortDiagnostics output does

**Comment by azimov** [comment]
@gowthamrao please provide the steps you used to create the data model - changes to support subsetted cohorts were added in [this migration](https://github.com/OHDSI/CohortDiagnostics/blob/main/inst/sql/sql_server/migrations/Migration_3-v3_2_0_suport_cohort_subsets.sql) but this will require updating any data models.

To execute run:

```r
CohortDiagnostics::migrateDataModel(connectionDetails, databaseSchema, tablePrefix = tablePrefix)
```


If this is a fresh database instance can you check if the "migrations" table is created and, if so, which migrations were executed. To get the migrations that have been previously executed run:

```r
mm <- CohortDiagnostics::getDataMigrator(connectionDetails, databaseSchema, tablePrefix)
mm$status()
```

**Comment by gowthamrao** [comment]
Hi @azimov in the sql referenced above the fields related to subset appear missing

I used this function to create the data model



```
CohortDiagnostics::createResultsDataModel(connectionDetails = connectionDetails,
                                          databaseSchema = resultsSchema)
```

In debug mode it is running this 

```
--Table cohort
--HINT DISTRIBUTE ON RANDOM
CREATE TABLE phenotypedili.cohort (
			cohort_id BIGINT NOT NULL,
			cohort_name VARCHAR(255) NOT NULL,
			metadata VARCHAR,
			sql VARCHAR NOT NULL,
			json VARCHAR NOT NULL,
			PRIMARY KEY(cohort_id)
);
```



 

> If this is a fresh database instance can you check if the "migrations" table is created and, if so, which migrations were executed. To get the migrations that have been previously executed run:
> 
> mm <- CohortDiagnostics::getDataMigrator(connectionDetails, databaseSchema, tablePrefix)
> mm$getStatus() 


```
> mm$getStatus() 
> Connecting using PostgreSQL driver
>                                  migrationFile migrationOrder executed
> 1               Migration_1-v3_1_0_time_id.sql              1     TRUE
> 2       Migration_2-v3_1_0_ir_person_years.sql              2     TRUE
> 3 Migration_3-v3_2_0_suport_cohort_subsets.sql              3     TRUE
> 4     Migration_4-v3_2_1_cohort_name_field.sql              4     TRUE
```

I am still getting

```

Connecting using PostgreSQL driver
Uploading file: cohort.csv to table: cohort                                                                                                                                                      
- Preparing to upload rows 1 through 135
Column is_subset in table cohort in results folder D:/windows_temp/AppData/Local/Temp/rtemp\RtmpwnENfh\unzipTempFolder1e2cd26612a is of type logical, but was expecting int. Attempting to convert.
Attempting to use bulk loading...
ERROR:  column "subset_parent" of relation "cohort" does not exist                                                                                          
Error in private$callback(data, index) : 
  Error while bulk uploading data, psql returned a non zero status. Status =  1
```

**Comment by gowthamrao** [comment]
Basically the output of cohort diagnostics i.e. cohort table has additional fields that are not in the cohort diagnostics results data model DDL. These fields are in the cohort diagnostics results data model csv

> Rows: 135 Columns: 7                                                                                                                                                                             
> -- Column specification --------------------------------------------------------------------------------------------------------------------------------------
> Delimiter: ","
> chr (3): cohort_name, json, sql
> dbl (3): cohort_id, subset_parent, subset_definition_id
> lgl (1): is_subset

**Comment by gowthamrao** [comment]
It looks like i am missing something. there is a migrations script here

https://github.com/OHDSI/CohortDiagnostics/blob/73120fe7e7736b3e3c1391a2607f4e17261cb5c5/inst/sql/sqlite/migrations/Migration_4-v3_2_1_cohort_name_field.sql#L14-L17

that appears to have the missing fields in the DDL that supports the subset fields.

**Comment by gowthamrao** [comment]
It looks like for postgres i have to use a two step process

```
CohortDiagnostics::createResultsDataModel(connectionDetails = connectionDetails,
                                          databaseSchema = resultsSchema)

CohortDiagnostics::migrateDataModel(connectionDetails = connectionDetails,
                                    databaseSchema = resultsSchema)
```

With the two step process above, i am now able to upload data into postgres.
