### ISSUE TITLE
Publish app error due to jnj urls in env.lock

### ISSUE THREAD

**Issue by alondhe** [OHDSI/CohortDiagnostics#1077]
I used launchDiagnosticsExplorer() and then tried using the Publish feature to then publish the app to our Posit Connect server. This fails, and part of the error stack includes inability to hit some JNJ Urls for repos like CRAN:

```
Warning: unable to access index for repository https://rstudiopm.jnj.com/CRAN/__linux__/centos7/latest/src/contrib:
  cannot open URL 'https://rstudiopm.jnj.com/CRAN/__linux__/centos7/latest/src/contrib/PACKAGES'
Warning: unable to access index for repository https://rstudiopm.jnj.com/JNJ/__linux__/centos7/latest/src/contrib:
  cannot open URL 'https://rstudiopm.jnj.com/JNJ/__linux__/centos7/latest/src/contrib/PACKAGES'
Warning: unable to access index for repository https://rstudiopm.jnj.com/GitHub/__linux__/centos7/latest/src/contrib:
  cannot open URL 'https://rstudiopm.jnj.com/GitHub/__linux__/centos7/latest/src/contrib/PACKAGES'
Warning: unable to access index for repository https://rstudiopm.jnj.com/JNJ-External/__linux__/centos7/latest/src/contrib:
  cannot open URL 'https://rstudiopm.jnj.com/JNJ-External/__linux__/centos7/latest/src/contrib/PACKAGES'
Error in FUN(X[[i]], ...) : subscript out of bounds
```

Here's those in the package:
https://github.com/OHDSI/CohortDiagnostics/blob/main/inst/shiny/DiagnosticsExplorer/renv.lock#L7-L19

**Comment by DrTTrousers** [comment]
So when I've had issues with things like this, it was IP blocking on one or both sides of the EC-2 to Mirror that was the culprit. A lot of the EC-2 IP range ends up on default blacklists because of how much they are used to spam/botnet things.

Just as a check, can either one or both sides of this problem check with their IT sec that the respective IP ranges are unblocked?

Alternatively, fork the CohortDiagnostics package and edit the lock file/dependencies to specify the GitHub versions/repos.

Did you happen to spot which of the package dependencies this happened on?

**Comment by alondhe** [comment]
tagging @azimov

**Comment by alondhe** [comment]
> So when I've had issues with things like this, it was IP blocking on one or both sides of the EC-2 to Mirror that was the culprit. A lot of the EC-2 IP range ends up on default blacklists because of how much they are used to spam/botnet things.
> 
> Just as a check, can either one or both sides of this problem check with their IT sec that the respective IP ranges are unblocked?
> 
> Alternatively, fork the CohortDiagnostics package and edit the lock file/dependencies to specify the GitHub versions/repos.
> 
> Did you happen to spot which of the package dependencies this happened on?

I believe these are internal jnj urls, and not something others can access. I haven't tried with alternate repo urls, but we should use public ones in the package here

**Comment by alondhe** [comment]
Thanks @azimov -- just tried your changes in develop, and they fix the issue.
