### ISSUE TITLE
createDiagnosticsExplorerZip does not copy the DiagnosticsExplorer.Rproj

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#1089]
I am so used to clicking [DiagnosticsExplorer.Rproj](https://github.com/OHDSI/CohortDiagnostics/blob/main/inst/shiny/DiagnosticsExplorer/DiagnosticsExplorer.Rproj) file and starting the shiny. But the function above does not copy it?

arent all files in inst copied https://github.com/OHDSI/CohortDiagnostics/blob/76911f757b9db74f7fe1c4a7e7405d4d285dc622/R/Shiny.R#L253 ?

**Comment by gowthamrao** [comment]
![image](https://github.com/OHDSI/CohortDiagnostics/assets/13936600/10ec9d2e-0616-4de7-bea0-612e85aa9be9)

**Comment by azimov** [comment]
Closing the project file should not be used in the sub dir
