### ISSUE TITLE
incidence rates won't display in shiny unless stratified by age, sex, and calendar year

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/CohortDiagnostics#1094]
Shiny app is located here: https://rconnect.jnj.com/OHDA/EPI_1115/ and the sqlite file has been provided in teams. I can also supply if needed. 

The issue is that unless all 3 strata are checked the incidence rate plots will not display on rconnect or locally. If any of the strata are unchecked the display reads "No data for this combination"

**Comment by azimov** [comment]
Closing: This should have been resolved in an OSM relases
