### ISSUE TITLE
Less than operator in LEFT JOIN

### ISSUE THREAD

**Issue by jdposada** [OHDSI/CohortDiagnostics#11]
Hi,

In the query below a `<` operator is used in the JOIN. This is not supported in some databases, particularly in BQ. This query is in `CohortDiagnostics/inst/sql/sql_server/OrphanCodes.sql" `

```sql
SELECT ss1.*
INTO #search_string_subset
FROM #search_str_top1000 ss1
LEFT JOIN #search_str_top1000 ss2
	ON ss2.concept_name_length < ss1.concept_name_length
		AND ss1.concept_name LIKE CONCAT (
			'%',
			ss2.concept_name,
			'%'
			)
WHERE ss2.concept_name IS NULL;
```

I think that changing to this should be equivalent and work

```sql
SELECT ss1.*
INTO #search_string_subset
FROM #search_str_top1000 ss1
LEFT JOIN #search_str_top1000 ss2
	ON ss2.concept_name_length = ss1.concept_name_length
		AND ss1.concept_name LIKE CONCAT (
			'%',
			ss2.concept_name,
			'%'
			)
WHERE ss2.concept_name IS NULL
AND ss2.concept_name_length < ss1.concept_name_length;
```

**Comment by schuemie** [comment]
Your proposal completely changes the logic. The goal of the query is to find search strings for which there are no shorter search strings that are a proper substring of the first search string. Your modification finds an empty set (I think), because the left join will always find the string itself and is therefore not NULL.

Maybe use a nested inner join inside the left join?

**Comment by jdposada** [comment]
Thanks for the quick answer :)

An example:

thoracic spondylarthritis | spondylarthritis
postmeningococcal arthritis (disorder) | postmeningococcal arthritis

Using this query
```sql
SELECT
  *
FROM
  `som-nero-phi-rit.EhdenRaDrugUtilization.xyvfoksdsearch_str_top1000`
WHERE
  concept_name NOT IN (
  SELECT
    ss1.concept_name
  FROM
    `som-nero-phi-rit.EhdenRaDrugUtilization.xyvfoksdsearch_str_top1000` ss1
  CROSS JOIN
    `som-nero-phi-rit.EhdenRaDrugUtilization.xyvfoksdsearch_str_top1000` ss2
  WHERE
    ss1.concept_name LIKE CONCAT ( '%', ss2.concept_name, '%' )
    AND ss2.concept_name_length < ss1.concept_name_length)
```

I keep `spondylarthritis` and `postmeningococcal arthritis` is that the intent?

I believe the translation to SQL SERVER will be the following but not sure

```sql
SELECT *
INTO #search_string_subset
FROM #search_str_top1000
WHERE
  concept_name NOT IN (
  SELECT
    ss1.concept_name
  FROM
    #search_str_top1000 ss1
  CROSS JOIN
    #search_str_top1000 ss2
  WHERE
    ss1.concept_name LIKE CONCAT ( '%', ss2.concept_name, '%' )
    AND ss2.concept_name_length < ss1.concept_name_length)
```

**Comment by konstjar** [comment]
@jdposada We tested on BQ, the SQL is correct and BQ supports boolean expression in ON statements. The core error is different. Thus this one could be closed for now.

**Comment by jdposada** [comment]
@konstjar Attached the screenshot from BQ UI. The issue remains

<img width="638" alt="Screen Shot 2020-04-01 at 10 37 17 AM" src="https://user-images.githubusercontent.com/11167042/78168473-d9251a00-7404-11ea-93df-156773a7025c.png">

**Comment by schuemie** [comment]
That error message is very informative. If I understand correctly, the issue isn't that you can't have the less than operator in a LEFT JOIN. The issue is that you *must* have an equality operator. So moving the less than operator to the WHERE clause will not fix the problem.

**Comment by schuemie** [comment]
A way to avoid the LEFT JOIN would be to use NOT IN, like this:

```sql
SELECT *
FROM temp.search_str_top1000
WHERE concept_name NOT IN (
		SELECT ss1.concept_name
		FROM temp.search_str_top1000 ss1
		INNER JOIN temp.search_str_top1000 ss2
			ON ss2.concept_name_length < ss1.concept_name_length
				AND ss1.concept_name LIKE CONCAT (
					'%',
					ss2.concept_name,
					'%'
					)
		);
```

Could someone test that a query like this *does* run on BigQuery? If so, we'd still need to see how well that performs on other platforms, because the NOT IN introduces an additional many-to-many string comparison.

@wivern

**Comment by konstjar** [comment]
@schuemie Yes, I can confirm, that this SQL will work in BQ
![image](https://user-images.githubusercontent.com/4144173/78249370-83c53780-74ee-11ea-96ff-cd51cca91922.png)
