### ISSUE TITLE
PK discrepancy with CDM DDL

### ISSUE THREAD

**Issue by ChungsooKim** [OHDSI/CohortDiagnostics#1105]
Hi 
I got an error during my strategus package running with CohortDiagnostics. 

![image](https://github.com/OHDSI/CohortDiagnostics/assets/42205861/fb0fd4c0-a4e5-4e8f-b6d8-c1067c404136)

This let me know that there are some discrepancy between the inst/settings/resultsDataModelSpecification.csv and CDM DDL. 

For example, in the CDM definition, concept_synonym table doesn't have PK in their DDL, 
![image](https://github.com/OHDSI/CohortDiagnostics/assets/42205861/76f614c8-d9d3-4fbe-bc58-8d9ac113d01e)
but all columns are denoted as PK in resultsDataModelSpecification.csv 
![image](https://github.com/OHDSI/CohortDiagnostics/assets/42205861/48a44eec-a171-4cbd-bdca-561be4d8876b)

Any discussion for this?

**Comment by azimov** [comment]
This is now resolved in develop and will be included in the next release
