### ISSUE TITLE
Move filtering of covariates

### ISSUE THREAD

**Issue by ginberg** [OHDSI/CohortDiagnostics#1112]
FeatureExtraction has integrated the solution that CohortDiagnostics currently has to filter covariates by minCharacterizationMean.
So since FE version 3.5.0, you can add this parameter to [getDbCovariateData](https://github.com/OHDSI/CohortDiagnostics/blob/03c40ab06832a329f2c904fbd686a0596ea9af6f/R/CohortCharacterizationDiagnostics.R#L40)

**Comment by azimov** [comment]
This has been released in the latest version
