### ISSUE TITLE
No DROP TABLE statement for cohort_summary_stats

### ISSUE THREAD

**Issue by katy-sadowski** [OHDSI/CohortDiagnostics#1115]
https://github.com/OHDSI/CohortDiagnostics/blob/03c40ab06832a329f2c904fbd686a0596ea9af6f/inst/sql/sql_server/CreateResultsDataModel.sql#L165

If we reuse a database/schema for multiple CohortDx runs, we get an error when the package tries to create the cohort_summary_stats table.  It looks like all of the other tables have a DROP TABLE IF EXISTS statement at the top of this file.

Thread: Main
Message:  Error executing SQL:
table cd_cohort_summary_stats already exists
An error report has been created at  C:/Users/sadowskk/IqviaGppCode/CdxStrategus/errorReportSql.txt
Level:  FATAL
Time:  2024-04-25 20:51:51

Stack trace:
19: (function (condition) 
{
    if (is(condition, "error")) {
        log("FATAL"
18: signalCondition(cnd)
17: signal_abort(cnd, .file)
16: abort(paste("Error executing SQL:", message, paste("An error report has bee
15: .createErrorReport(dbms, err$message, sqlStatement, errorReportFile)
14: value[[3]](cond)
13: tryCatchOne(expr, names, parentenv, handlers[[1]])
12: tryCatchList(expr, classes, parentenv, handlers)
11: tryCatch({
    startQuery <- Sys.time()
    lowLevelExecuteSql(connection, sq
10: DatabaseConnector::executeSql(connection, sql)
9: .createDataModel(connection, databaseSchema, tablePrefix)
8: CohortDiagnostics::createResultsDataModel(connectionDetails = resultsDataba

**Comment by azimov** [comment]
This should now be resolved in the develop branch

**Comment by azimov** [comment]
Fixed in latest release
