### ISSUE TITLE
Error Viewing Results Using Diagnostics Explorer

### ISSUE THREAD

**Issue by vittoriaramella** [OHDSI/CohortDiagnostics#1123]
Hi everyone, 

I'm getting an error while trying to view the results of CohortDiagnostics in the Diagnostics Explorer.

Once I have converted the csv results to an sqlite database file, I get this error running the `launchDiagnosticsExplorer(sqliteDbPath = "MyCohortDiagnosticsResults.sqlite")`:

```
Using DatabaseConnector jdbc driver.
Initalizing pooled connection
Connecting using SQLite driver
Error in `DatabaseConnector::getTableNames()`:
! Pool, R6 connection not supported
```

This is what I get if i run `rlang::last_trace()`

```
<error/rlang_error>
Error in `DatabaseConnector::getTableNames()`:
! Pool, R6 connection not supported
---
Backtrace:
     ▆
  1. ├─CohortDiagnostics::launchDiagnosticsExplorer(...)
  2. │ └─shiny::runApp(appDir = appDir)
  3. │   └─appParts$onStart()
  4. │     └─shiny::loadSupport(appDir, renv = sharedEnv, globalrenv = globalenv())
  5. │       ├─withr::with_dir(...)
  6. │       │ └─base::force(code)
  7. │       └─shiny:::sourceUTF8(basename(globalPath), envir = globalrenv)
  8. │         └─base::eval(exprs, envir)
  9. │           └─base::eval(exprs, envir)
 10. ├─shiny::..stacktraceon..(...)
 11. └─OhdsiShinyModules::createCdDatabaseDataSource(...) at global.R:94:3
 12.   └─OhdsiShinyModules:::.availableTables(connectionHandler, resultDatabaseSettings$schema)
 13.     ├─base::tolower(...)
 14.     └─DatabaseConnector::getTableNames(connectionHandler$getConnection(), databaseSchema = schema)
```

I'm running R version 4.2.3, DatabaseConnector v6.3.2 and CohortDiagnostics v3.2.5.

I don't know if this could be an issue related to the way the sqlite file is built or an issue related to the DatabaseConnector package (so I should report this on their GitHub).

Thanks in advance,
Vittoria

**Comment by ggamit** [comment]
Hi,
I'm getting the exact same error same, using a similar configuration.
It seems that in global.R (line 82) the call
_connectionHandler <- ResultModelManager::PooledConnectionHandler$new(shinySettings$connectionDetails)_
returns a connection object of class "R6", which is not supported by DatabaseConnector
_> class(connectionHandler)
[1] "PooledConnectionHandler" "ConnectionHandler"       "R6"_   
A fix or a suggestion for a workaround will be appreciated, thanks!
Guy.

**Comment by frankcorneliusmartin** [comment]
> > class(connectionHandler)
> [1] "PooledConnectionHandler" "ConnectionHandler" "R6"

We are also experiencing the same

**Comment by frankcorneliusmartin** [comment]
We made it working by downgrading a bunch of packages. The last package we downgraded was the ShinyModules:

`remotes::install_github('OHDSI/OhdsiShinyModules@v2.0.2')`

But we also downgraded the siny version itself (and some other packages):
remotes::install_version('shiny',version='1.7.4',repos = "http://cran.us.r-project.org")

**Comment by scheah92** [comment]
Just want to add my +1 here, same issues.

I think this truly warrants a closer look by the developers.

**Comment by azimov** [comment]
This issue has now been resolved in OhdsiShinyModule. Please update with:

`remotes::install_github("OHDSI/OhdsiShinyModules")`
