### ISSUE TITLE
Release 3.3.0 planning

### ISSUE THREAD

**Issue by azimov** [OHDSI/CohortDiagnostics#1128]
After discussion earlier I have the following steps that we need for a 3.3.0 release:

## Improve unit test speed 

This is a fairly broad goal - the overall objective is to half the total test time for the unit tests to make it easier to change the package.

To achieve this we have a few points:

* Investigate DittoDb for caching query results
* Reduce the test burden for PRs by having unit tests run only on sqlite (and then run on the full database suite when they get merged into develop)
* Isolated tests for each diagnostic function instead of running everything multiple times - this will reduce a lot of the redundant execution
 
## Support use achilles for precomputed concept counts
* #1117 and #1120 aimed to improve this - we will go with #1120 as it seems like the best overall solution. It looks like this just needs some unit tests

## Fix sampling for FE
The sampling feature should speed up feature extraction in a lot of cases, #1114 addresses that this should only happen for feature extraction as results were weird for other packages

## R Check segfaults on GA Mac
It is still unclear to me why this is happening but it could be in a dependent package (possibly ResultModelManager). This requires improvement

@ablack3 @cebarboza please add to this discussion as I likely missed something from our meeting

**Comment by ablack3** [comment]
I've been experimenting with the tests. I decided to try to maximize code coverage in the smallest amount of execution time and just see where that gets us. I'm only running tests on a synpuf duckdb database and they run in under a minute. Current code coverage is around 80%. It's a starting point. I'm thinking we will want to run the full test suite before releasing but running only on duckdb during development seems ok.

There are definitely features in the package I'm not very familiar with like the data migrations and cohort subsetting.

**Comment by azimov** [comment]
> I've been experimenting with the tests. I decided to try to maximize code coverage in the smallest amount of execution time and just see where that gets us. I'm only running tests on a synpuf duckdb database and they run in under a minute. Current code coverage is around 80%. It's a starting point. I'm thinking we will want to run the full test suite before releasing but running only on duckdb during development seems ok.
> 

This sounds great for most purposes. I have already set up changes so that full tests only run on merge to develop/main so this should speed up the rate of changes.

**Comment by ablack3** [comment]
<img width="614" alt="image" src="https://github.com/user-attachments/assets/0aa15525-ed61-4563-8959-edad44a4b49b">
I'm wondering if we really need the concept_ancestor and concept_relationship tables in the results. When running tests on postgres a lot of time is taken uploading 600,000+ rows to the results database. I'm just wondering if we need all this vocab data in the results or if we could get by with just a concepts table with some additional columns.

**Comment by ablack3** [comment]
I did some ad-hoc testing of using dittodb with DatabaseConnector on postgres. 
It works fine with RPostgres driver and DBI::dbConnect. It does not work at all with `createConnectionDetails`, `connect` from DatabaseConnector.
It tries to work with createDbiConnectionDetails, connect but does give an error and a warning.

```
In dbMockConnect(drv, ...) :
  DatabaseConnectorDriver is an unknown driver, dittodb will have limited functionality.
Error in find_file(path) : 
  Couldn't find the file aasdf/conInfo-.R in any of the mock directories.
```

So I think it is possible to get this working but it would take some work and for sure we would need to connect using DBI::dbConnect which could be inside DatabaseConnector.

**Comment by ablack3** [comment]
I think we should remove the dependency on OhdsiShinyModules by putting the shiny app code in the CohortDiagnostics package. I had trouble deploying the cohort diagnostics app to Connect and was getting an error that "ReportGenerator was not installed from a known source."
I was confused why OhdsiShinyModules would depend on ReportGenerator but then realized that it's now depending on a different ReportGenerator package than the one developed in Darwin and presented at OHDSI Europe last year. 
I just think it would be cleaner and easier to keep the shiny app code in CohortDiagnostics and not need to worry about two R packages with the same name in my R library.

https://github.com/darwin-eu/reportGenerator
https://github.com/OHDSI/reportGenerator
