### ISSUE TITLE
runTemporalCohortCharacterization defaults to FALSE

### ISSUE THREAD

**Issue by schuemie** [OHDSI/CohortDiagnostics#113]
`runTemporalCohortCharacterization`  defaults to FALSE, while all other diagnostics default to TRUE: 
https://github.com/OHDSI/CohortDiagnostics/blob/3019c417f02b866e9deafbbea698575d8a00563e/R/RunDiagnostics.R#L94

Setting to TRUE by default would be more consistent. @gowthamrao, any reason not to?

**Comment by gowthamrao** [comment]
I agree we should make it TRUE by default and thus consistent with others. I will make those changes
