### ISSUE TITLE
Combine included source concepts and orphan concepts into one submenu - concepts

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#129]
- Append the three tables into one data table
- color included concepts with green, color orphan concepts with red
- add filter (by vocabulary, standard or concept class)
- sort by counts
- be able to join columns of counts by database id - to allow comparisions across databases

**Comment by schuemie** [comment]
Why?

**Comment by gowthamrao** [comment]
The premise is that UI simplification (with less toggling on menu items) will lead to better quality decision making. 

In this case - the decision based on data presented on 'concepts' - so they need to be made visible together. Presence of 'included concepts' informs 'orphan concepts'. The relative numbers of informative, as is the string match.

We differentiate between them using filter, and colors

**Comment by gowthamrao** [comment]
Example 
Type | Concept ID | Vocabulary | Code | Concept Name | Database1 | Database2
-- | -- | -- | -- | -- | -- | --
Orphan | 4064161 | SNOMED | 19943007 | Cirrhosis   of liver | 58,474 | 424,342
Included | 45601187 | ICD10CM | K74.60 | Unspecified cirrhosi | 25,537 | 0
Orphan | 45601187 | ICD10CM | K74.60 | Unspecified cirrhosi | 0 | 232,333

**Comment by gowthamrao** [comment]
Combine these two 
https://github.com/OHDSI/CohortDiagnostics/blob/701638b699cb27d75767484c7f3a4b090de69643/inst/shiny/DiagnosticsExplorer/server.R#L383
https://github.com/OHDSI/CohortDiagnostics/blob/701638b699cb27d75767484c7f3a4b090de69643/inst/shiny/DiagnosticsExplorer/server.R#L476

**Comment by gowthamrao** [comment]
recommended concepts and included/resolved concepts now have a new UI
