### ISSUE TITLE
formalize extraction of concept sets from JSON into a separate package

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/CohortDiagnostics#13]

**Comment by gowthamrao** [comment]
Hi @vojtechhuser I think our new changes to ROhdsiWebApi will handle this. 

https://github.com/OHDSI/ROhdsiWebApi/blob/354a8ebd69229d73ddc3be565c45df8cb023e005/extras/TestCode.R#L48

its still in develop branch of ROhdsiWebApi and we hope to release by end of the month as v1.0.0 . 

Please let me know if that does not satisfy your request.
