### ISSUE TITLE
In Venn diagram - enforce target on left side, and comparator on right side of Venn

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#130]
Sometimes comparator is left side, and target is on right side
othertimes target is on left side, and comparator is on right side

Comparator on left side
![image](https://user-images.githubusercontent.com/13936600/88691732-3c7d3b00-d0cb-11ea-82d6-edb53667e305.png)

target on left side
![image](https://user-images.githubusercontent.com/13936600/88691931-79e1c880-d0cb-11ea-944c-756bcc402e2c.png)

Probably because the cohort with more numbers is on left side

We should enforce target on left side, and comparator on right side.
This will make it easier to interpret

**Comment by schuemie** [comment]
I agree this would be good, but have tried to achieve this in the past and failed. The VennDiagram package does have an option to enforce which side goes where, but it throws an error if you try to use it. You could try, and if the problem still exists, we'd need to file an issue with the developer.

**Comment by gowthamrao** [comment]
Did you try rendering the Venn diagram using ggplot, ggviz or plotly?

**Comment by schuemie** [comment]
I did not. That sounds like a lot of work ;-)

**Comment by gowthamrao** [comment]
Venn diagram has been replaced by Stacked bar
