### ISSUE TITLE
formal construct for set of cohorts   (study.json) object

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/CohortDiagnostics#14]

**Comment by gowthamrao** [comment]
Hi @vojtechhuser I think the question is - how to import a set of cohort definitions into a standalone study package? If yes, then the we are trying to solve : is using ROhdsiWebApi function

https://github.com/OHDSI/ROhdsiWebApi/blob/354a8ebd69229d73ddc3be565c45df8cb023e005/R/CohortDefinition.R#L127

Would a vignette, as described here https://github.com/OHDSI/CohortDiagnostics/issues/33 and https://github.com/OHDSI/CohortDiagnostics/issues/8 help? 

(if not, please feel free to reopen this issue)

**Comment by vojtechhuser** [comment]
I wish to re-open. It is not what I meant. I can't re-open since I don't have sufficient rights to the repo.

The proposal is to do the informatics right. The idea is that set of cohorts is an important construct to model and properly handle.  For example for cohort pathway - I need a set of cohorts. So the goal is to have a proper JSON structure for it. In fact a review of all our JSON structures is what I propose. Make the approach harmonized.
