### ISSUE TITLE
Invalid object name 'scratch.dbo.concept_counts'.

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/CohortDiagnostics#15]
![image](https://user-images.githubusercontent.com/6305439/76124136-0928fb00-5fc8-11ea-9c1d-f6dd06913888.png)

I haven't figured it out, but when running a couple databases in a row, I would hit this issue.  I'm guessing there is a table clean up or generation issue along the way?  Or a connection needs to be closed or something.

Sorry, didn't pin-point why it was happening, but happened twice.  If I rerun the DB that generated the issue, it goes away.

**Comment by schuemie** [comment]
Hmmm, my guess is there was a conflict because someone else was running the same code at the same time, and cleaned up the table before you were done with it. I'll try to turn it into a temp table, so there will be no more collisions.

**Comment by anthonysena** [comment]
I think @ericaVoss and I were running this and created this conflict as I got the same error but attributed it to the PDW maintenance that day.

**Comment by ericaVoss** [comment]
It wouldn't be hard to pass it a study name or something to make sure you don't step on someone else's toes.

**Comment by schuemie** [comment]
Fixed [here](https://github.com/OHDSI/CohortDiagnostics/commit/6fcf823ee526198852258ba5c4dd96d27b78e3ab)
