### ISSUE TITLE
rlang error in trying to run latest version of cohortdiagnostics 

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/CohortDiagnostics#156]
**Problem:** During instantiation of cohort the following error occurs involving rlang package, error below:
Instantiation cohort [797] Pulmonary Arterial Hypertension, pheno library, Alg10, Li 2017, with  position of claim, without >180 years of age restriction
  |==========================================================================================================================================================================| 100%
Executing SQL took 1.67 mins
Error: Can't combine `..1$description` <logical> and `..2$description` <character>.
Run `rlang::last_error()` to see where the error occurred.
****
compared package versions with @joelswerdel and @stephenfortin and do not see any differences....

**Comment by jhardin29** [comment]
Above error occurs when running on R version 3.6.1; ran successfully on @RupaMakadia's EC2 instance which runs R version 3.6.3. At this point giving up on resolving this issue and will update R to a newer version and will hope it resolves the issue.

**Comment by gowthamrao** [comment]
Maybe related to https://github.com/OHDSI/CohortDiagnostics/issues/153

@jhardin29 please let me know if v1.1.1 fixes your issue

**Comment by jhardin29** [comment]
tagging @gowthamrao and @jgilbert I updated the version of Java and installed a daily Rstudio desktop build from here: https://dailies.rstudio.com/ and it now works fine; thank you.
