### ISSUE TITLE
RJSONIO::toJSON formatting concept_ids in scientific notation

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/CohortDiagnostics#161]
Related to https://github.com/ohdsi-studies/Covid19CharacterizationCharybdis/issues/68 and not specific only to CohortDiagnostics: the use of RJSONIO::toJSON() has an issue whereby concept_ids are converted to scientific notation. We may want to consider revising this to use jsonlite instead [per this article](https://stackoverflow.com/questions/10820638/disable-scientific-notation-when-converting-to-json).

**Comment by anthonysena** [comment]
I sorted this out for the upcoming ScyllaCharacterization study and noting that it is not specific to CohortDiagnostics but rather a behavior of ROhdsiWebAPI. Here is the code I wrote to address this:

https://github.com/ohdsi-studies/ScyllaCharacterization/blob/master/extras/PackageMaintenance.R#L116-L122

**Comment by gowthamrao** [comment]
Do you think it is best to make changes in ROhdsiWebApi instead?

**Comment by gowthamrao** [comment]
Fixed here https://github.com/OHDSI/ROhdsiWebApi/issues/152
