### ISSUE TITLE
Obtain a copy of omop vocabulary for conceptIds used in cohort diagnostics

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#162]
Limit to only the conceptId's in cohorts (Concept, Domain, Vocabulary, Concept_class, Concept_relationship, Relationship, Concept_Synonym, concept_ancestor)

**Comment by gowthamrao** [comment]
In current design, covariate and tempoarl_covariate brings down a copy of concept_id details with it e.g. concept_name. When we append results from across different data sources, we append and deduplicate covariate / temporal_covariate here

https://github.com/OHDSI/CohortDiagnostics/blob/master/R/Shiny.R#L95-L96

this strategy assumes that concept_name does not change over time in omop vocabulary - which is an incorrect assumptions. Concept-names may change.

e.g.

in a 2018 version of vocabulary - 'Alendronate' begins with a capital letter
![image](https://user-images.githubusercontent.com/13936600/90003155-b122ae80-dc61-11ea-833e-0b8e5fc0670e.png)

in a 2020 version of vocabulary, - 'alendronate' does not
![image](https://user-images.githubusercontent.com/13936600/90003269-d6afb800-dc61-11ea-9e11-a88da312df43.png)


This is being treated as two seperate row items during `distinct()` because append/bind is case sensitive.

This leads to 

![image](https://user-images.githubusercontent.com/13936600/90003369-f810a400-dc61-11ea-91f8-7c53562a18cd.png)

**Comment by gowthamrao** [comment]
We dont capture the version of the vocabulary used by a database in current design, i.e. we cannot build a rule to deduplicated concept-id metadata using vocabulary version.

Short term solution:
- group by conceptId
- max(conceptName)

Long term solution:
- retrieve all conceptId in results
- get the concept meta data from most recent version of the vocabulary
- capture display vocabulary version (which maybe different from the vocabulary used by the source database)

**Comment by gowthamrao** [comment]
This issue is probably causing performance issue with some caretesian join

**Comment by cgreich** [comment]
@gowthamrao: Are you sure this is not a red herring? The concept_name can change between versions, but not semantically. There may be orthographical changes, long or short versions of descriptors or other edit changes, but the entity will stay the same. So, for all intents and purposes you could just consolidate all concept_names per concept_id into one. I'd take the most recent one.

**Comment by gowthamrao** [comment]
Long term solution will need to be an option to refresh and pull down conceptId metadata from most recent vocabulary - assuming the semantic meaning is the same

**Comment by cgreich** [comment]
Yes, concepts cannot change their meaning. That would cause a deprecation. So, changed names have only optical relevance. Can't you just pick one concept_name? Even randomly?

**Comment by gowthamrao** [comment]
Yes. That's the short term solution

**Comment by gowthamrao** [comment]
Implemented in version 2. Version 2 will have a full copy of vocabulary tables when running in database mode. But when running in R memory (as dataframe/premerged file) it will have a partial copy of vocabulary tables limited to the conceptIds that are directly related to the cohorts being diagnosed.
