### ISSUE TITLE
Error when launching sharedshiny  app

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/CohortDiagnostics#165]
Problem: receive this error when attempting to launch sharedshiny app, see screenshot and text from R session below:

> runApp('ShinyApps/EPI_797')
Using merged data detected in data folder

Listening on http://127.0.0.1:7298
Warning: Error in tag: argument is missing, with no default
  73: tag
  72: tags$td
![image](https://user-images.githubusercontent.com/11822115/89794504-23c24b80-daf5-11ea-969c-9d35f569cbb6.png)

App runs fine locally but not on sharedshiny server; any insight would be appreciated. Tagging @azimov and @gowthamrao  Thank you!

**Comment by azimov** [comment]
I think I've seen this error before, its likely a comma missing somewhere in the UI code.

**Comment by azimov** [comment]
@gowthamrao I fixed this in [this PR](https://github.com/OHDSI/CohortDiagnostics/pull/166), to test, run this on R version 3.51. on the jnj shared shiny server.

**Comment by gowthamrao** [comment]
Thank you @azimov !
