### ISSUE TITLE
Make sure source concept sets are handled properly

### ISSUE THREAD

**Issue by schuemie** [OHDSI/CohortDiagnostics#17]
Currently assuming concept sets expressions resolve to standard concepts, but this is not always true, meaning we miss them in included and orphan source concepts.

**Comment by gowthamrao** [comment]
@schuemie  i think this is still an active issue? We are still assuming that correct?

**Comment by schuemie** [comment]
I don't know. We'd need to test it using a concept set that include source concepts.
