### ISSUE TITLE
Run Orphan concepts error since change to webapi

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#180]
@chrisknoll probably related to bigquery changes in webapi

> DBMS:
> pdw
> 
> Error:
> com.microsoft.sqlserver.jdbc.SQLServerException: The query processor ran out of stack space during query optimization. Please simplify the query.
> 
> SQL:
> CREATE TABLE  #Codesets   WITH (LOCATION = USER_DB, DISTRIBUTION = REPLICATE) AS
> SELECT
> * 
> FROM

**Comment by schuemie** [comment]
@gowthamrao, [this commit](https://github.com/OHDSI/CohortDiagnostics/commit/9b85c08161999adb75b60993625743611dcca2fb) should fix that. I'm testing it right now, and seems to work for smaller examples. Could you test it on a larger problem (many concept sets)?

**Comment by gowthamrao** [comment]
Fixed by @schuemie
