### ISSUE TITLE
Add optional phenotypeId to cohorts to run

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#184]
We need a way to group cohortIds (unique identifier of cohorts being diagnosed) by an optional field such as phenotypeId. If present then the cohortDiagnostics should group together cohortIds such that

- only cohortIds within the same group (phenotypeId) are compared to each other for overlap.
https://github.com/OHDSI/CohortDiagnostics/blob/83493697f0bc6c31c86d6044c0f9684ddbd89177/R/RunDiagnostics.R#L91

**Comment by pbr6cornell** [comment]
don't need to support phenotypeid,  we just need to support that overlap is performed on sets of cohortids, which is user providesd.  a list of lists would be sufficient for this.   the use case of overlap is not just to compare within definitions within phenotype, but the point is that a user should be able to specify which cohorts gets compared with each other, so that it is not required to do all pair-wise comparisons - as is current default.

**Comment by gowthamrao** [comment]
CohortDiagnostics is designed to run on a set of cohortId's - as referenced in the cohorts to run. 

The input specification for cohort diagnostics is an external object as
https://github.com/OHDSI/CohortDiagnostics/blob/83493697f0bc6c31c86d6044c0f9684ddbd89177/R/RunDiagnostics.R#L70

or 
https://github.com/OHDSI/CohortDiagnostics/blob/83493697f0bc6c31c86d6044c0f9684ddbd89177/R/RunDiagnostics.R#L72

To limit certain diagnostics, such as overlap, to a subset of cohortIds - we need to have that as an input to the cohortOverlap function call. The easiest option is adding the field phenotypeId to cohort group cohorts and have this group be used by cohortOverlap..

Sounds like we want to use a more generic framework. Then - we may want to use another reference structure such as (absence of which - no grouping is assumed and the app runs in default mode).


groupName | diagnosticsToRun | cohortId
-- | -- | --
Pneumonia | overlap | 10101
Pneumonia | overlap | 10102
Pneumonia | overlap | 10103
study1 | overlap | 10102
study1 | overlap | 10103
study1 | overlap | 10106

**Comment by gowthamrao** [comment]
Another alternative is to run, only the subset of cohorts at a time (i.e. we call cohortDiagnostics for each group seperately)  - but that will make us loose some of the optimizations such as not being able to reuse the conceptSetExpressions that are shared across cohort definitions.

**Comment by gowthamrao** [comment]
Added optional phentoypeId in version 2
