### ISSUE TITLE
invalid 'nchars' argument error

### ISSUE THREAD

**Issue by edward-burn** [OHDSI/CohortDiagnostics#19]
I've created a standalone package using the "examplePackage" template (for a covid studyathon project) and while it works for two of the cohorts I've created in Atlas, it fails for two others (where a range of additional exclusion criteria are specified). When creating the cohorts I get the error: 
"Warning: file("") only supports open = "w+" and open = "w+b": using the former
Warning: text connection used with readChar(), results may be incorrect
Error in readChar(pathToSql, file.info(pathToSql)$size) :
invalid 'nchars' argument"

The study package is here https://github.com/edward-burn/CharacterisationAndPlpECMO/tree/master/Feasibility/Cohort%20Diagnostics/ECMO%20cohort%20diagnostics, with an issue with more details on the cohorts it fails for here https://github.com/edward-burn/CharacterisationAndPlpECMO/issues/1

This error is somewhat mysterious to me, are there some constraints on names of concept sets or number of exclusion criteria that I'm missing?

**Comment by schuemie** [comment]
The 'nchars' message is a weird way of saying it can't find a text file, most likely the CohortsToCreate.csv file.

I'm able to run your package without problem. Did you make sure to rebuild the package before running?

**Comment by edward-burn** [comment]
I'm still having this problem. When I include all 4 of my cohorts and rebuild the package it fails with this error. 

The inclusion of "171 ECMO cohort" and "177 ECMO w viral" seem to cause the problem. These cohorts have a number of extra eligibility criteria, but they run fine on Atlas and create sensible counts.

The study package (https://github.com/edward-burn/CharacterisationAndPlpECMO/tree/master/Feasibility/Cohort%20Diagnostics/ECMO%20cohort%20diagnostics) now contains all four of the cohorts and fails in my environment. Are you able to run this version without a problem?

**Comment by edward-burn** [comment]
This was caused by some trailing whitespace in my cohort names, and has now been fixed
