### ISSUE TITLE
Issue with temporal characterization

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/CohortDiagnostics#191]
I keep getting the error:

`Error: Column timeId not found in .data`

When I try to run the temporal characterization

**Comment by gowthamrao** [comment]
Thank you. Which version are you using?

**Comment by clairblacketer** [comment]
I was using v1.2.1 for this

**Comment by gowthamrao** [comment]
@clairblacketer this should be resolved in 1.2.7. Please let me know if it is not.
