### ISSUE TITLE
Mathematics behind Incidence and Prevalence rate

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#201]
We need to document what we mean by incidence and prevalence. 
What we mean by rate calculated at year/month intervals

**Comment by gowthamrao** [comment]
SQL example https://github.com/OHDSI/Kala/blob/develop/inst/sql/sql_server/ComputeTimeSeriesDay.sql

**Comment by gowthamrao** [comment]
https://github.com/OHDSI/CohortDiagnostics/issues/97

**Comment by schuemie** [comment]
I documented how the IR is calculated [here](https://github.com/OHDSI/CohortDiagnostics/blob/master/inst/shiny/DiagnosticsExplorer/html/incidenceRate.html) (shown when you click the info button for the IR tab). Are you saying that explanation is insufficient?

**Comment by cgreich** [comment]
Is this a good moment to publicly discuss the various definitions and methods for calculation? After all, incidence should be the number of new **cases**, not patients who had a new case. For that, you need to be able to leave a case, like in cohort end date. If that is not possible, because you cannot define or haven't defined the end date, this definition is the best next thing.

I am saying this because in your FAQ you encourage people to compare the incidence rate to published numbers.

**Comment by gowthamrao** [comment]
> publicly discuss the various definitions and methods for calculation

I think this deserves a methods paper - something like 'application of methods to calculate incidence and prevalence statistics in observational data'. 

While computing incidence/prevalence related statistics - a lot of design choices are made (e.g. washout period). In addition there are various 'flavors' of incidence and prevalence that many times don't approximate to the same value.

These wide variations in output with similar sounding terms to describe them (all having incidence/prevalence in them e.g. life time incidence, annualized incidence, cumulative incidence, incidence proportion) causes cognitive dissonance among collaborators  making scientific discourse on a topic difficult.

> I am saying this because in your FAQ you encourage people to compare the incidence rate to published numbers.

This has become a major source of headache, with energy spent on deciphering why the numbers are different. A paper would hopefully help reduce this and help generate reliable evidence.

So i propose we document this and target it as a publication

**Comment by gowthamrao** [comment]
working on timeseries diagnostics
