### ISSUE TITLE
Build a R-shiny app to execute cohort diagnostics

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#203]
Cohort Diagnostics may be run in webapi mode or package mode. However, based on recent experience, configuring/installing/executing/reviewing output of cohort diagnostics is a tedious process that needs to be simplified.

We propose a R-shiny application that allows to

- specify connection details as required by databaseConnector if data in remote db (allow secure connection). 
- create R packages for teams to run and help diagnoze
- collect the results (premerge) . output csv/premerged to loction of user choice (using UI)
- alternatively provide a way to upload to db
- provided/use site specific unique identifiers and global cohort definitions. AtlasId may represent a local sites cohort id.

The UI should support all functions related to: runCohortDiagnostics, connectionDetail and exit connection

**Comment by ablack3** [comment]
A supported workflow could be
1) Define and generate your cohort in Atlas
2) Log in to the proposed shiny app, select your cohort, push the "Run Diagnostics" button, view results

**Comment by gowthamrao** [comment]
Related to https://github.com/OHDSI/CohortDiagnostics/issues/324

**Comment by azimov** [comment]
This will likely be completed as part of strategus which will make it significantly easier for users to design studies
