### ISSUE TITLE
ERROR: relation "cdm_ibm_ccae_v1103.concept_relationship" 

### ISSUE THREAD

**Issue by edward-burn** [OHDSI/CohortDiagnostics#21]
When setting runOrphanConcepts to true I had the error " Error: Error executing SQL:
org.postgresql.util.PSQLException: ERROR: relation "cdm_ibm_ccae_v1103.concept_relationship" does not exist
  Position: 214
An error report has been created at  C:/Users/eburn/Documents/ECMO_prediction/CharacterisationAndPlpECMO-master-1/CharacterisationAndPlpECMO-master/Feasibility/Cohort Diagnostics/ECMO cohort diagnostics/errorReport.txt"

I think this might be because of line 42 here:
https://github.com/OHDSI/CohortDiagnostics/blob/ce351b3e592c64539500c84875b068dbf22990d8/inst/sql/sql_server/OrphanCodes.sql

Perhaps replacing "cdm_ibm_ccae_v1103.dbo.concept_relationship" with "@cdm_database_schema.concept_relationship" would fix the problem?

**Comment by schuemie** [comment]
Yikes! Sorry about that. I just pushed a fix to the develop branch. Can you install it?

**Comment by edward-burn** [comment]
Perfect, this now works perfectly using the develop branch
