### ISSUE TITLE
Difference in values between cohort characterization and temporal characterization

### ISSUE THREAD

**Issue by jswerdel** [OHDSI/CohortDiagnostics#213]
There seems to be differences between the values in the 2 tabs.  I have seen this for the 0 to 0 days values in particular.  An example is for pustular psoriasis in CCAE examining adalimumab, cohort characterization has the value of 4.6% while temporal characterization has 0.0.

**Comment by jswerdel** [comment]
[screen shots.docx](https://github.com/OHDSI/CohortDiagnostics/files/5170605/screen.shots.docx)

**Comment by gowthamrao** [comment]
@jswerdel  this i think is explained by how Feature Extraction handles the queries for the same conceptIds. One is at the concept level, and other is concept-group level (i.e. concept only vs concept + descendants)

tagging @schuemie for additional comments.

This is a potential source of confusion -so we have to clearly describe it. 

(adding to version 2)

**Comment by schuemie** [comment]
Yes, we deliberately chose to use the *verbatim* concepts (so excluding descendants) for the temporal characterization, while the cohort characterization includes the descendants. This is because the two diagnostics serve very different goals, which we should definitely communicate clearly.
