### ISSUE TITLE
Cohort Characterization Age Groups

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/CohortDiagnostics#216]
The Age Groups aren't sticking together in the Pretty Cohort Characterization

0-69 stick together
![image](https://user-images.githubusercontent.com/6305439/92288628-7c5dec00-eedb-11ea-838c-e3b1b1ac6303.png)

The rest are found below
![image](https://user-images.githubusercontent.com/6305439/92288648-90a1e900-eedb-11ea-95ff-f412053ec53f.png)

Looks like it has to do with whatever the "first" database is  . . . that defines the age groups that get lumped together.  So for example if you put MDCR first the age group start 45-104.  The 0-44 show up later.

**Comment by gowthamrao** [comment]
Thank you! And thank you for the screenshots.

**Comment by gowthamrao** [comment]
Fixed in develop branch
