### ISSUE TITLE
cohort_definition_id should be bigint

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#217]
In OMOP CDM cohort_definition_id is BIGINT

https://github.com/OHDSI/CommonDataModel/blob/58f01a2a69b4960a48eb1ebf9ea11a4cae76c841/Sql%20Server/OMOP%20CDM%20Results%20sql%20server.txt#L48

It is not in Cohort Diagnostics

Create cohort tables
https://github.com/OHDSI/CohortDiagnostics/blob/master/inst/sql/sql_server/CreateCohortTable.sql#L5

Create cohort inclusion stats tables
https://github.com/OHDSI/CohortDiagnostics/blob/master/inst/sql/sql_server/CreateInclusionStatsTables.sql#L14

We need cohort_definition_id to be BIGINT to support the idea of use of referent conceptId in phenotype library. In phenotype library, every phenotype will have a referent omop standard conceptId. The phenotypeId will be `referent concept id * 1000` and cohort definition ids will be `phenotypeId + (3-999)` , as every cohort definition id may belong to one and only one phenotype.

We need to make this change to support BIGINT for cohort_definition_id in cohort diagnostics

**Comment by gowthamrao** [comment]
Example data:
```
inclusionRulesTest <- tidyr::tibble(
  cohort_definition_id = c(1124300003, 1124300004, 1124300005, 1124300005, 1124300006),
  rule_sequence_id = c(0, 0, 0, 1, 0),
  name = c(
    'With no history of gastrointestinal hemorrhage',
    'Gender is male',
    'Gender is male',
    'Metabolic disease at any time',
    'With gastrointestinal hemorrhage at some point'
  )
)
```

when inserting using 
```

DatabaseConnector::insertTable(connection = connection,
                               tableName = "#cohort_inclusion",
                               data = inclusionRulesTest,
                               dropTableIfExists = FALSE,
                               createTable = FALSE,
                               tempTable = TRUE,
                               oracleTempSchema = oracleTempSchema)
```
found here 
https://github.com/OHDSI/CohortDiagnostics/blob/d1e309941933c8e18c4c7da2aff15ee68e7b01be/R/CohortConstruction.R#L746-L757

is giving error on redshift dbms

> Warning: the condition has length > 1 and only the first element will be used
> Warning: the condition has length > 1 and only the first element will be used
> Warning: the condition has length > 1 and only the first element will be used
> java.sql.SQLException: [Amazon] (500310) Invalid operation: column "rule_sequence_id" of relation "#cohort_inclusion" does not exist;

**Comment by gowthamrao** [comment]
Warning seems to come from DatabaseConnector line

https://github.com/OHDSI/DatabaseConnector/blob/12332c0d56c1de53df6ca9009e95364a59124076/R/InsertTable.R#L436

**Comment by schuemie** [comment]
Not sure if this helps, but the error message references "rule_sequence_id", which should probable be "rule_sequence". (see [here](https://github.com/OHDSI/CohortDiagnostics/blob/master/inst/sql/sql_server/CreateInclusionStatsTables.sql#L15))

**Comment by gowthamrao** [comment]
Closed as an issue with DatabaseConnector

https://github.com/OHDSI/DatabaseConnector/issues/80#issuecomment-688402626
