### ISSUE TITLE
Perform cohort and temporal characterization for all cohorts at once

### ISSUE THREAD

**Issue by schuemie** [OHDSI/CohortDiagnostics#218]
A new feature of FeatureExtraction (currently still in the [develop](https://github.com/OHDSI/FeatureExtraction/tree/develop) branch) is that you can create aggregate statistics for multiple cohorts at once. Using this feature will speed up characterization greatly.

Just use a vector of cohort Ids as the `cohortId` argument of `getDbCovariateData`. The resulting `covariateData` object will have the familiar `covariates` and `covariatesContinuous` tables, but with an extra column called `cohortDefinitionId`, which can be used to untangle the data of the multiple cohorts. There's also a new function called `filterByCohortDefinitionId` that can be used to filter a `covariateData` object to one cohort.

**Comment by gowthamrao** [comment]
Tested and included in version 2 - works for time distribution, characterization (including temporal).

@schuemie  this works great. thank you for adding to Feature Extraction. Significantly faster

**Comment by gowthamrao** [comment]
As described here https://github.com/OHDSI/FeatureExtraction/issues/102
seems to fail with bigint cohortId's

**Comment by gowthamrao** [comment]
Fixed bigint issue
Added batch mode
