### ISSUE TITLE
Make sure empty cohorts are handled correctly

### ISSUE THREAD

**Issue by schuemie** [OHDSI/CohortDiagnostics#22]
Most diagnostics test for this explicitly, but may not be handled correctly everywhere. Specifically makes sure all still runs even if all cohorts are empty. See https://github.com/ohdsi-studies/Covid19CohortEvaluation/issues/1

**Comment by gowthamrao** [comment]
Maybe related to https://github.com/OHDSI/CohortDiagnostics/issues/153

**Comment by gowthamrao** [comment]
Done with changes to version 2
