### ISSUE TITLE
Error in Orphan Concepts When Concept Set Contains Excluded Concepts

### ISSUE THREAD

**Issue by katy-sadowski** [OHDSI/CohortDiagnostics#220]
Some of my concept sets are showing the following error on the Orphan (Source) Concepts tab:

`Error: Can't convert <double> to <list>.`

I've deduced that the concept sets with this error are ones that contain a concept with the "Exclude" box checked in ATLAS.

I am on:

- WebAPI version 2.7.7
- ATLAS version 2.7.7
- CohortDiagnostics version 1.2.2

To reproduce:

Here's a concept set for which I'm getting the error:
```{
  "items": [
    {
      "concept": {
        "CONCEPT_ID": 255573,
        "CONCEPT_NAME": "Chronic obstructive lung disease",
        "STANDARD_CONCEPT": "S",
        "STANDARD_CONCEPT_CAPTION": "Standard",
        "INVALID_REASON": "V",
        "INVALID_REASON_CAPTION": "Valid",
        "CONCEPT_CODE": "13645005",
        "DOMAIN_ID": "Condition",
        "VOCABULARY_ID": "SNOMED",
        "CONCEPT_CLASS_ID": "Clinical Finding"
      },
      "isExcluded": false,
      "includeDescendants": true,
      "includeMapped": true
    },
    {
      "concept": {
        "CONCEPT_ID": 261895,
        "CONCEPT_NAME": "Compensatory emphysema",
        "STANDARD_CONCEPT": "S",
        "STANDARD_CONCEPT_CAPTION": "Standard",
        "INVALID_REASON": "V",
        "INVALID_REASON_CAPTION": "Valid",
        "CONCEPT_CODE": "33325001",
        "DOMAIN_ID": "Condition",
        "VOCABULARY_ID": "SNOMED",
        "CONCEPT_CLASS_ID": "Clinical Finding"
      },
      "isExcluded": true,
      "includeDescendants": true,
      "includeMapped": true
    }
  ]
}```

Please let me know if there's further info you need from me or if I can help troubleshooting in any way.

**Comment by gowthamrao** [comment]
@katy-sadowski  have you tried v 1.2.7

https://github.com/OHDSI/DatabaseConnector/issues/80#issuecomment-683336615

i am trying refactor much of our code to use type stable methods - but its becoming tricky. so i am hoping to rewrite the package as v2 with these issues addressed

**Comment by katy-sadowski** [comment]
Let me try upgrading; didn't realize there was a more-recent version since I'd last updated pretty recently.  Will report back.

**Comment by katy-sadowski** [comment]
@gowthamrao I installed again using the instructions [here](https://github.com/OHDSI/CohortDiagnostics/issues/220) and it installed version 1.2.2.  Do I need to grab 1.2.7 off of GitHub?

**Comment by gowthamrao** [comment]
Hi @katy-sadowski  please try using the version 2 in develop right now. We have addressed this issue in that version. Apologies for the inconvenience.

You can install it using `remotes::install_github('OHDSI/CohortDiagnostics', ref = 'develop')`

Please let us know if that works.

**Comment by katy-sadowski** [comment]
I'm getting this error at the `instantiateCohortSet` step:

```Error in instantiateCohortSet(connectionDetails = connectionDetails, cdmDatabaseSchema = cdmDatabaseSchema,  : 
  4 assertions failed:
 * Variable 'cohortReference': Must have at least 6 cols, but has 4 cols.
 * Variable 'cohortReference$cohortId': Must be of type 'double', not 'integer'.
 * Variable 'cohortReference$webApiCohortId': Must be of type 'double', not 'NULL'.
 * Variable 'names(cohortReference)': Must be a subset of set
 * {referentConceptId,cohortId,webApiCohortId,cohortName,logicDescription,clinicalRationale}.```

I assume related to some changes to the inputs to that function in the new version - but the help documentation isn't loading for the updated library.  Are you able to share updated docs for the dev version so I can work past this?  Thanks!

**Comment by katy-sadowski** [comment]
Hi again,

I was unable to debug the above error, so I tried uninstalling and reinstalling the package to get on the working version - but now by default it's installing v2.0.0.  However, there are 2 new errors this time (the above error seems to have been resolved).

1. When running `cohortDiagnostics` I get this error: `Variable 'databaseDescription': Must be of type 'character', not 'NULL'`. Seems it's now requiring a value in `databaseDescription` even though the default value is NULL.  This is resolved by specifying a string for that variable.
2. After that fix, this error is raised instead:
```
Error: Must subset elements with a valid subscript vector.
i Logical subscripts must match the size of the indexed input.
x Input has size 1 but subscript has size 0.
```

I'm not an R whiz so it's pretty difficult for me to tell what's going on here.  Any ideas?  Thanks very much!

**Comment by katy-sadowski** [comment]
I had a bit more time to poke around and discovered the cause of the above error.  It was expecting a non-NULL value for `databaseName`, even though the default value for that variable is NULL in the `runCohortDiagnostics` function, and docs don't state this is a required variable.

**Comment by katy-sadowski** [comment]
Unfortunately now I'm running into a new issue which is preventing me from opening the app to see if the orphan concept issue is fixed.  I'll leave this issue open for now and open a new one with the other issue.

**Comment by katy-sadowski** [comment]
I filed the new issue.  Happy to report that I found a workaround and got the app to work - and this orphan concept issue is fixed! I'll close this. I will also file an issue for those `databaseName` and `databaseDescription` things - just documentation updates needed there I believe.
