### ISSUE TITLE
Temporal cohort characterization doesn't show in shiny app

### ISSUE THREAD

**Issue by schuemie** [OHDSI/CohortDiagnostics#221]
The shiny app [expects an object called `timeRef`](https://github.com/OHDSI/CohortDiagnostics/blob/22172863cea05d9bde7cdf37d687febc33aa24cb/inst/shiny/DiagnosticsExplorer/global.R#L116), but this is not generated anywhere. It does not appear in the list of CSV files that is generated.

**Comment by gowthamrao** [comment]
Yes. timeRef will be part of version 2. 

This was accidentally merged to version 1 during testing. I did not take it out because it was part of a logic, and the output of version 1 would satisfy the logic before coming to checking if timeRef exists.

**Comment by schuemie** [comment]
"the output of version 1 would satisfy the logic before coming to checking if timeRef exists."

What do you mean by that? The output of v1.2.7 doesn't show in the Shiny app of v1.2.7 (for the reason outlined above).

**Comment by gowthamrao** [comment]
Fixed
