### ISSUE TITLE
Orphan concepts don't show in Shiny app

### ISSUE THREAD

**Issue by schuemie** [OHDSI/CohortDiagnostics#222]
I get `Error: Column 'conceptName' not found in '.data'`. This is probably because `orphan_concepts.csv` doesn't contain a column `concept_name`, which in turn is probably because it is removed [here](https://github.com/OHDSI/CohortDiagnostics/blob/master/R/ConceptSets.R#L469).

**Comment by gowthamrao** [comment]
Fixed
