### ISSUE TITLE
"ERROR: hash table size exceeded"

### ISSUE THREAD

**Issue by edward-burn** [OHDSI/CohortDiagnostics#229]
I have created a CohortDiagnostics package using the examplePackage framework. It ran successfully up to "Creating temporal cohort characterizations" where it failed with the error 
"Sending temp tables to server
Constructing features on server
  |===================================================================                                            |  60%Error: Error executing SQL:
org.postgresql.util.PSQLException: ERROR: hash table size exceeded"

To note, four of my cohorts returned zero counts (but the first 15 cohorts all had positive counts).
  
  

........................
ERROR REPORT
Thread: Main
Message:  Error: Error executing SQL: org.postgresql.util.PSQLException: ERROR: hash table size exceeded An error report has been created at  
Level:  FATAL
Time:  2020-09-17 23:34:19

Stack trace:
13: stop(paste("Error executing SQL:", message, paste("An error report has been created at ", fileName), sep = "\n"), ca
12: .createErrorReport(connection@dbms, err$message, sqlStatement, errorReportFile)
11: value[[3]](cond)
10: tryCatchOne(expr, names, parentenv, handlers[[1]])
9: tryCatchList(expr, classes, parentenv, handlers)
8: tryCatch({
    startQuery <- Sys.time()
    lowLevelExecuteSql(connection, sqlStatement)
    if (profile) {
        
7: DatabaseConnector::executeSql(connection, sql, profile = profile)
6: (function (connection, oracleTempSchema = NULL, cdmDatabaseSchema, cohortTable = "#cohort_person", cohortId = -1, cd
5: do.call(eval(parse(text = fun)), args)
4: FeatureExtraction::getDbCovariateData(connection = connection, oracleTempSchema = oracleTempSchema, cdmDatabaseSchem
3: getCohortCharacteristics(connection = connection, cdmDatabaseSchema = cdmDatabaseSchema, oracleTempSchema = oracleTe
2: CohortDiagnostics.R#97: CohortDiagnostics::runCohortDiagnostics(packageName = "diagCovidRA", connectionDetails = con
1: runCohortDiagnostics(connectionDetails = connectionDetails, cdmDatabaseSchema = cdmDatabaseSchema, cohortDatabaseSch

R version:
R version 4.0.2 (2020-06-22)

Platform:
x86_64-w64-mingw32

Attached base packages:
- stats
- graphics
- grDevices
- utils
- datasets
- methods
- base

Other attached packages:
- diagCovidRA (0.0.1)
- DatabaseConnector (3.0.0)

**Comment by gowthamrao** [comment]
Hi @edward-burn would it be possible for you to please try the develop branch.

**Comment by edward-burn** [comment]
Hi @gowthamrao, I used the develop branch and all worked fine with the examplePackage as is. However, when I updated this with my cohorts I get a similar error as before, see error report below. 

This seems related to the new temporal characterization. To note, only createCohorts and runInclusionStatistics were set to TRUE in runCohortDiagnostics, but it still tried to run this temporal characterization.

........
Thread: Main
Message:  Error: Error executing SQL: org.postgresql.util.PSQLException: ERROR: hash table size exceeded An error report has been created at  
Level:  FATAL
Time:  2020-09-18 11:53:28

Stack trace:
13: stop(paste("Error executing SQL:", message, paste("An error report has been created at ", fileName), sep = "\n"), ca
12: .createErrorReport(connection@dbms, err$message, sqlStatement, errorReportFile)
11: value[[3]](cond)
10: tryCatchOne(expr, names, parentenv, handlers[[1]])
9: tryCatchList(expr, classes, parentenv, handlers)
8: tryCatch({
    startQuery <- Sys.time()
    lowLevelExecuteSql(connection, sqlStatement)
    if (profile) {
        
7: DatabaseConnector::executeSql(connection, sql, profile = profile)
6: (function (connection, oracleTempSchema = NULL, cdmDatabaseSchema, cohortTable = "#cohort_person", cohortId = -1, cd
5: do.call(eval(parse(text = fun)), args)
4: FeatureExtraction::getDbCovariateData(connection = connection, oracleTempSchema = oracleTempSchema, cdmDatabaseSchem
3: getCohortCharacteristics(connection = connection, cdmDatabaseSchema = cdmDatabaseSchema, oracleTempSchema = oracleTe
2: CohortDiagnostics.R#97: CohortDiagnostics::runCohortDiagnostics(packageName = "diagCovidRA", connectionDetails = con
1: runCohortDiagnostics(connectionDetails = connectionDetails, cdmDatabaseSchema = cdmDatabaseSchema, cohortDatabaseSch

R version:
R version 4.0.2 (2020-06-22)

Platform:
x86_64-w64-mingw32

Attached base packages:
- stats
- graphics
- grDevices
- utils
- datasets
- methods
- base

Other attached packages:
- diagCovidRA (0.0.1)
- DatabaseConnector (3.0.0)

**Comment by gowthamrao** [comment]
We have introduced 'batch mode' where the characterization job now runs in batches of 100 cohorts. Maybe that will solve it.

How many cohorts were you characterizing?
