### ISSUE TITLE
Issue when cohorts use measurement (potential bug)

### ISSUE THREAD

**Issue by azzashoaibi** [OHDSI/CohortDiagnostics#23]
Found a potential bug while runing Cohort Diagnostics on cohort (see attached cohort JSON)

This cohort is unique edge case with measurement domain being used twice

![image](https://user-images.githubusercontent.com/26492586/77811436-982dae00-7070-11ea-803c-6f1b90579dde.png)

> DBMS:
> pdw
> 
> Error:
> com.microsoft.sqlserver.jdbc.SQLServerException: 'c' is not a recognized built-in function name.
> 

SQL that caused error:
```
SELECT concept.concept_id,
	concept_name,
	concept_count
FROM (
	SELECT measurement_concept_id AS concept_id,
		COUNT(*) AS concept_count
	FROM scratch.ashoaibi.cohort
	INNER JOIN CDM.dbo.measurement
		ON subject_id = person_id
			AND cohort_start_date = measurement_date
	INNER JOIN #Codesets
		ON measurement_concept_id = concept_id
	WHERE cohort_definition_id = 14992
		AND codeset_id IN (c(1, 2))
	GROUP BY measurement_concept_id
	) concept_counts
INNER JOIN CDM.dbo.concept
	ON concept_counts.concept_id = concept.concept_id;
```

Error was because of 'c' in below - not SQL syntax
> AND codeset_id IN (c(1, 2))

probably came from
`primary_codeset_ids` referenced here
https://github.com/OHDSI/CohortDiagnostics/blob/29aaaf756e86f1a285461c7cba220cb2f5894675/inst/sql/sql_server/CohortEntryBreakdown.sql#L14

from here
https://github.com/OHDSI/CohortDiagnostics/blob/29aaaf756e86f1a285461c7cba220cb2f5894675/R/CohortLevelDiagnostics.R#L173

[json.txt](https://github.com/OHDSI/CohortDiagnostics/files/4396473/json.txt)

@gowthamrao
@pbr6cornell 
@schuemie

**Comment by schuemie** [comment]
Thanks! Should be fixed now in the develop branch.
