### ISSUE TITLE
Cohorts with 0 persons causes error in merge

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#24]
![image](https://user-images.githubusercontent.com/13936600/77862947-c20bdf80-71ec-11ea-920d-0c293ec5a771.png)

If one of the data sources creates a cohort that is emptye (0 records) e.g. `Warning: Target cohort with ID 15000 appears to be empty. Was it instantiated?` , i think it causes an error in the merge. In this example Fatigue has 0 records in one data source (see row 2). This some how led to rows 1, 3 & 4 all having the same numbers.

**Comment by schuemie** [comment]
I'm not able to reproduce that problem. Could you e-mail me your result zip files?

**Comment by gowthamrao** [comment]
Cant seem to reproduce - for now. Closing issue. Will reopen if it comes back
