### ISSUE TITLE
Resuming between "getCohortCounts" and "runCohortCharacterization" gives an error

### ISSUE THREAD

**Issue by hms1** [OHDSI/CohortDiagnostics#25]
Aborting code after `getCohortCounts` and resuming before `runCohortCharacterization` gives the following error:

> 2020-03-30 08:26:06	[Main thread]	FATAL	CohortDiagnostics	runCohortDiagnostics	Error in as.data.frame(y) : object 'counts' not found   
> 2020-03-30 08:34:05	[Main thread]	FATAL	CohortDiagnostics	runCohortDiagnostics	subscript out of bounds  
> 2020-03-30 08:34:05	[Main thread]	FATAL	CohortDiagnostics	runCohortDiagnostics	subscript out of bounds

I think this is because the local object  `counts` does not get created if `getCohortCounts` has completed successfully and `nrow(subset) == 0` when the code is resumed:

https://github.com/OHDSI/CohortDiagnostics/blob/29aaaf756e86f1a285461c7cba220cb2f5894675/R/RunDiagnostics.R#L135-L155

Later on `runCohortCharacterization` attempts a merge using the local `counts` object, which does not exist:

https://github.com/OHDSI/CohortDiagnostics/blob/29aaaf756e86f1a285461c7cba220cb2f5894675/R/RunDiagnostics.R#L428

I guess an easy fix would be to reassign `counts` using the save csv after line  155.

Apologies if I'm on the wrong trail here - still getting familiar with the code.

**Comment by gowthamrao** [comment]
hi @hms1 I recently took on from @schuemie  as package maintainer and still catching up. Apologies for not responding earlier.

I think i have addressed this issue here https://github.com/OHDSI/CohortDiagnostics/issues/58

Closing this issue and marking as resolved. Please reopen if this is not fixed.
