### ISSUE TITLE
Use of deprecated function

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#27]
https://github.com/OHDSI/CohortDiagnostics/blob/29aaaf756e86f1a285461c7cba220cb2f5894675/R/Incremental.R#L94

tibble::as.tibble() is deprecated in tibble 3.0

> Use as_tibble() instead of as_data_frame() or as.tibble(), but mind the new signature and semantics.

https://tibble.tidyverse.org/reference/deprecated.html

Causing https://github.com/ohdsi-studies/Covid19CohortEvaluation/issues/4

**Comment by schuemie** [comment]
Thanks!
