### ISSUE TITLE
Included Source Concepts - Shows Entries from First DB

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/CohortDiagnostics#277]
Only the Source Concepts from the first DB are shown, so if your first DB is CPRD then you only see READ codes regardless of how many DBs are selected.

**MISSING ICD CODES BECAUSE CPRD IS FIRST**
![image](https://user-images.githubusercontent.com/6305439/94714474-2df50f00-031a-11eb-8d6c-5b0b7f7cc5b6.png)

**HAS ICD CODES BECAUSE CCAE IS FIRST**
![image](https://user-images.githubusercontent.com/6305439/94714506-39e0d100-031a-11eb-974f-11069d08e105.png)

**Comment by gowthamrao** [comment]
Did u scroll to the next page?
