### ISSUE TITLE
databaseName and databaseDescription default values should be non-NULL

### ISSUE THREAD

**Issue by katy-sadowski** [OHDSI/CohortDiagnostics#301]
Running CohortDiagnostics v2.0.0

Currently, these parameters for `runCohortDiagnostics` have NULL default values, but both are required to have a non-NULL value.  Would be good to update the default values so that folks don't hit an error (the error for `databaseName` is not straightforward to debug; it does not simply state that a value is required).

Error for `databaseDescription`:
`Variable 'databaseDescription': Must be of type 'character', not 'NULL'`

Error for `databaseName`:
```
Error: Must subset elements with a valid subscript vector.
i Logical subscripts must match the size of the indexed input.
x Input has size 1 but subscript has size 0.
```

**Comment by gowthamrao** [comment]
related to https://github.com/OHDSI/CohortDiagnostics/issues/303
