### ISSUE TITLE
Error in getDefinitionsMetaData

### ISSUE THREAD

**Issue by ChenyuL** [OHDSI/CohortDiagnostics#310]
Hi Everyone: 
I was trying to run the CohortDiagnostics package using WebAPI followed the instruction. I’m not able to figure out how to fix this problem.
The baseUrl I used is the one shows on ATLAS Configuration.  WebAPI version is 2.7.7 
And I'm unable to to retrieve meta data. 
<img width="709" alt="image" src="https://user-images.githubusercontent.com/17032366/100931890-220fff80-34b9-11eb-808f-ccccfa69cb1b.png">

<img width="754" alt="image" src="https://user-images.githubusercontent.com/17032366/100931863-17556a80-34b9-11eb-8385-4becca6e8d71.png">

The cohorts in ATLAS run successfully. 
![image](https://user-images.githubusercontent.com/17032366/100932812-6e0f7400-34ba-11eb-98d8-586460d1cc03.png) 

How can I troubleshoot this issue? 
Thank you !

**Comment by gowthamrao** [comment]
@ChenyuL  would it be possible for you to please share the json expression of the cohort? 
you can go to export tab (in above screenshot) - copy the json, paste it to notepad and save as death.json file
upload that json to this conversation

**Comment by ChenyuL** [comment]
Thank you Gowtham!
I upload the .json file here
[[outcome]death.json](https://github.com/ChenyuL/OHDSI_packages/commit/545eb7a80a77042891f6b4294788a02987dae9a8 )

I tried to run this study https://github.com/ohdsi-studies/Covid19CharacterizationCharybdis on my database, and have this error
![image](https://user-images.githubusercontent.com/17032366/101389300-37a57080-388f-11eb-807d-7477b5385f1a.png)

**Comment by gowthamrao** [comment]
@ChenyuL regarding the death cohort and json -- looks like this is a special edge case. I am tagging @schuemie @anthonysena as they may have some experience with the death table

**Comment by ChenyuL** [comment]
Hi @gowthamrao  and @schuemie 
I run a PLP study used the same [outcome]death cohort, it has an error alert and I don't know how to troubleshoot it. Could it be a cohort design problem or a database table problem? 
my cohort design is as below: 
![image](https://user-images.githubusercontent.com/17032366/102825982-d8c31980-43ad-11eb-8d66-24d9224289dd.png)
.json file: https://github.com/ChenyuL/OHDSI_packages/commit/545eb7a80a77042891f6b4294788a02987dae9a8 
error: 
![image](https://user-images.githubusercontent.com/17032366/102825830-97326e80-43ad-11eb-86e8-4008e7b59962.png)


Thank you for helping me!

**Comment by gowthamrao** [comment]
Hi @ChenyuL has this been resolved?

**Comment by ChenyuL** [comment]
> Hi @ChenyuL has this been resolved?

Hi @gowthamrao, 
The PLP study I run constructed cohorts correctly and got the Results.zip, only the shiny app doesn't work for me. 

The getDefinitionsMetadata function problem still exists(using WebApi). I'm wondering what version of those dependencies should I download? I run too many other studies that required different versions of dependencies. I don't know if it's a problem.
![image](https://user-images.githubusercontent.com/17032366/110798792-82e16d80-8248-11eb-8e58-6ed031c4f5e3.png)

**Comment by gowthamrao** [comment]
Closing the issue. Please let us know if this is unresolved
