### ISSUE TITLE
Error on Visit Context Tab

### ISSUE THREAD

**Issue by katy-sadowski** [OHDSI/CohortDiagnostics#313]
When I click anything on the Visit Context page (sort a column, show more entries, move between pages) I get the following error in a pop-up:

```
DataTables warning: table id=DataTables_Table_5 - Error in rank(x, ties.method = "min", na.last = "keep"): unimplemented type 'list' in 'greater'
```

I'm only testing the app on a single cohort and a single database.

I'm on MacOS Catalina 10.15.5 and CohortDiagnostics v2.0.0.

Thanks!

**Comment by gowthamrao** [comment]
I have seen this before and don't know the reason why it happens. Many times it just disappears :) Please try updating packages, maybe it is because one of the dependency. I will tag @schuemie if he knows.

**Comment by gowthamrao** [comment]
Looks like this is no longer an observed issue. If it comes back we will revisit
