### ISSUE TITLE
Adding functions to NAMESPACE

### ISSUE THREAD

**Issue by AniekMarkus** [OHDSI/CohortDiagnostics#314]
In another R package, I would like to get some basic characteristics for already created cohorts. Is it possible to add the functions getCohortCharacteristics and exportCharacterization to the NAMESPACE so that I can re-use just this part of the implementation in that package?

**Comment by gowthamrao** [comment]
Thank you @AniekMarkus . Could u elaborate this a little bit more please. 

An idea i have been thinking of for sometime is a interactive version of cohort diagnostics, i.e. imagine a shiny app that allows you to pull a cohort definition from atlas/phenotype library, select a diagnostics to run (e.g. incidence rate analysis, or temporal characterization) and execute. App will then run ONLY the selected diagnostic for the selected cohort - and return results.

**Comment by AniekMarkus** [comment]
Hi @gowthamrao, such an interactive version - where only a selection of the results can be executed sounds valuable. My comment was actually very much related to this, I wanted to re-use only a part of the functionalities of this characterisation package in a study package. Hence, the request to add these two functions to the NAMESPACE because that would make that possible. 

I have solved my issue now by borrowing the functions in this package, but hard-coding them in my package. We can close this issue now, but allowing re-use of particular components either in a shiny or as part of other study packages would be helpful.
