### ISSUE TITLE
Ability to pass FeatureExtraction::createCovariateSettings to getCohortCharacteristics

### ISSUE THREAD

**Issue by edward-burn** [OHDSI/CohortDiagnostics#32]
At the moment, I believe getCohortCharacteristics uses createDefaultCovariateSettings() from FeatureExtraction as the default for covariateSettings for getCohortCharacteristics(). It would be great if it were also possible to have the ability to use FeatureExtraction::createCovariateSettings() here, so as to include features not included in the default set.

**Comment by gowthamrao** [comment]
@schuemie  seems like a good enhancement to have. I have noticed that the default cohort characterization specification is not sufficient to feel confident in the diagnostics of a cohort.

e.g. if we are building the phenotype of 'joint swelling' - i would be interested in having detailed information in table 1 of concepts that may cause joint swelling e.g. Rheumatoid arthritis, trauma, knee infection, etc. Only Rheumatoid arthritis would be in default table 1.

**Comment by schuemie** [comment]
So I think there are two issues:
1. The need to use different covariateSettings when building the cohort characterization
2. The need to show different concepts in the default 'table 1'.

For 2, a solution is to simple replace the [Table1Specs](https://github.com/OHDSI/CohortDiagnostics/blob/master/inst/shiny/DiagnosticsExplorer/Table1Specs.csv). The format of these specifications is taken from FeatureExtraction. It could use some documentation. Any volunteers?

Adding covariateSettings as an argument to [runCohortDiagnostics](https://github.com/OHDSI/CohortDiagnostics/blob/master/R/RunDiagnostics.R#L58) (defaulting to the default covariate settings) sounds fine to me. @gowthamrao : you want to take that on?

**Comment by gowthamrao** [comment]
> For 2, a solution is to simple replace the Table1Specs. The format of these specifications is taken from FeatureExtraction. It could use some documentation. Any volunteers?

Happy to. I will create an issue in FeatureExtraction

**Comment by gowthamrao** [comment]
https://github.com/OHDSI/CohortDiagnostics/commit/155b5bbaac3c90f00a52ae4f0924f877bf3af92f
