### ISSUE TITLE
Unit tests not executing on R check

### ISSUE THREAD

**Issue by schuemie** [OHDSI/CohortDiagnostics#321]
For some reason the unit tests are not executing at all. One possible reason might be that [this file](https://github.com/OHDSI/CohortDiagnostics/blob/develop/inst/settings/CohortsToCreateForTesting.csv) used [here](https://github.com/OHDSI/CohortDiagnostics/blob/develop/tests/testthat/test-againstEunomia.R#L23) references cohorts that are not included in the package.

I recommend running the unit tests manually line by line and resolve all issues.

**Comment by gowthamrao** [comment]
Fixed
