### ISSUE TITLE
Pull Cohorts from public Atlas or Study Packages

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/CohortDiagnostics#324]
A very powerful addition would be these functions:

CohortDiagnostics::execute(webApI,list of cohorids)
This would pull a list of cohorts and run on those. This is very useful when you are updating phenotypes with a group of databases.

CohortDiagnostics::execute(StudyPackage)
This would facilitate cohortdiagnostics for all studies! Can even work on those already installed locally and those on GitHub.

For those that do not have internet connection we can make an addition that you can download the cohorts only and then use

CohortDiagnostics:execute(folderName)

I think this would help a lot for all our studies.

@anthonysena what do you think?

**Comment by anthonysena** [comment]
I like this idea a lot @PRijnbeek - I think these would be powerful additions. Just a few thoughts on each:

`CohortDiagnostics::execute(webApiUrl, cohortIds)`: I think some form of this may already exist in the package but it may be scoped to the cohort creation step. So perhaps @gowthamrao can speak to that.

`CohortDiagnostics::execute(StudyPackage)` and `CohortDiagnostics:execute(folderName)`: I think these could be collapsed such that we'd only need `CohortDiagnostics:execute(folderName)`. In the case of running on a study package, the `folderName` parameter could be `list.files(system.files("folder/to/cohorts", packageName=StudyPackage))` (R pseudo-code). One challenge we may face there is that our packages are not consistent in the way that we enumerate the cohorts. So it may be easier to have the calling code assemble a data frame such as: `cohortId, cohortFullName, json, sql` as the input to run.

**Comment by PRijnbeek** [comment]
Yes indeed some of it may be there already let me dive more in the vignette to see. All the better.. :)

**Comment by gowthamrao** [comment]
Hi @PRijnbeek many of these already exists, but may not be easily apparent. We use the very powerful ROhdsiWebApi package to pull cohorts from Atlas and run diagnostics on it.

We currently have two ways of running cohort diagnostics:
1. Package mode - like any OHDSI study. we create a study package e.g https://github.com/OHDSI/CohortDiagnostics/blob/develop/example/eunomiaPhenotypeLibrary/
2. WebApi mode - this is what you are referring to. basically give the list of atlasId and webApis - and package does everthing else
3. Interactive mode - i have experimented this but not pushed code. basically like 2, but you can run in interactive mode on a shiny app where you select 1 cohort + 1 diagnostics -- view results immediately on shiny. 

I am maturing 1 now, then will tackle 2 and 3. 

You should use ROhdsiWebApi to pull cohort json

**Comment by gowthamrao** [comment]
@PRijnbeek we are going to use Hydra to build the study package. I am thinking of building a shiny app to give the study package. The shiny app would pull cohort definitions from one or more webapi endpoints (atlas/atlases)

**Comment by gowthamrao** [comment]
How to is now documented in vignette - in package mode
