### ISSUE TITLE
Cohort Characterization fails when calling feature extraction

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#329]
Characterizing cohorts
Starting large scale characterization of 26 cohort(s)
Constructing features on server
  |======================================================================================================================| 100%
Executing SQL took 51.2 mins
Fetching data from server
Fetching data took 14.4 secs
Error: Domain error

**Comment by gowthamrao** [comment]
The issue seems to be here

https://github.com/OHDSI/CohortDiagnostics/blob/develop/R/CohortCharacterizationDiagnostics.R#L91
![image](https://user-images.githubusercontent.com/13936600/113207337-7d22ea80-923e-11eb-9ff7-bb3cd0fc8ce9.png)

While in debug mode - if run just `covariates` i get
```
# Source:   lazy query [?? x 4]
# Database: sqlite 3.34.1
#   [D:\git\bitbucket\epi_856\inst\CohortDiagnostics\output\OPTUM_PANTHER\andromedaTemp\file26245a0a1662.sqlite]
   cohortId covariateId    mean     sd
      <dbl>       <dbl>   <dbl>  <dbl>
 1    21521  4134593212 0.0451  0.208 
 2    21516  4043371212 0.574   0.494 
 3    21507  4228686212 0.0157  0.124 
 4    21494  4272488212 0.170   0.376 
 5    21516  4167354212 0.00316 0.0561
```

but when i do `covariates %>% dplyr::collect()`

```
Browse[4]>  covariates %>% dplyr::collect()
Error: Domain error
```

**Comment by gowthamrao** [comment]
Code not in master branch - this change was introduced here

**Comment by anthonysena** [comment]
I looked at the code on the develop branch [here](https://github.com/OHDSI/CohortDiagnostics/blob/develop/R/CohortCharacterizationDiagnostics.R#L81-L93) and do not see the `dplyr::collect()` reference as mentioned above. Tracing that code, it looks like you are aiming to set the `results$covariates` if that attribute does not already exist on the `results` Andromeda object otherwise you are appending the results. Not sure why you would need the `dplyr::collect()` in this case?

**Comment by gowthamrao** [comment]
Thanks @anthonysena . I dont think dplyr::collect() is the issue here. I had put collect() before because i wanted extract the result to a non andromeda object. I am not sure if that was needed (@schuemie can you weigh in).

Please see full trace - i get the 'Domain error' with and without dplyr::collect()
```

Thread: Main
Message:  Error: Domain error 
Level:  FATAL
Time:  2021-03-31 17:54:39

Stack trace:
16: stop(list("Domain error", NULL, NULL))
15: result_fetch(res@ptr, n = n)
14: .local(res, n, ...)
13: DBI::dbFetch(result, n = batchSize)
12: DBI::dbFetch(result, n = batchSize)
11: tryCatchList(expr, classes, parentenv, handlers)
10: tryCatch({
    while (!DBI::dbHasCompleted(result)) {
        batch <- DBI::dbFetch(result, n = batchSize)
        output[[
9: batchApply(value, doBatchedAppend)
8: .local(x, i, ..., value)
7: `[[<-`(`*tmp*`, name, value = list(list(new("CovariateData", ptr = <pointer: 0x000000ce1ed51240>, dbname = "D:\\git\\bitbuc
6: `[[<-`(`*tmp*`, name, value = list(list(new("CovariateData", ptr = <pointer: 0x000000ce1ed51240>, dbname = "D:\\git\\bitbuc
5: `$<-`(`*tmp*`, covariates, value = list(list(new("CovariateData", ptr = <pointer: 0x000000ce1ed51240>, dbname = "D:\\git\\b
4: CohortCharacterizationDiagnostics.R#91: `$<-`(`*tmp*`, covariates, value = list(list(new("CovariateData", ptr = <pointer: 0
3: RunDiagnostics.R#677: getCohortCharacteristics(connection = connection, cdmDatabaseSchema = cdmDatabaseSchema, oracleTempSc
2: CohortDiagnostics.R#123: CohortDiagnostics::runCohortDiagnostics(packageName = packageName, phenotypeDescriptionFile = phen
1: runCohortDiagnostics(packageName = packageName, connectionDetails = connectionDetails, cdmDatabaseSchema = cdmDatabaseSchem

R version:
R version 4.0.4 (2021-02-15)

Platform:
x86_64-w64-mingw32

Attached base packages:
- stats
- graphics
- grDevices
- utils
- datasets
- methods
- base

Other attached packages:
- CohortDiagnosticsEpi856 (0.0.1)
- DatabaseConnector (4.0.0)
- magrittr (2.0.1)



```

**Comment by gowthamrao** [comment]
> results$covariates
is NULL

when i execute this line
> results$covariates <- covariates
i get the error

```
Browse[3]>   results$covariates <- covariates
Error: Domain error
An error report has been created at  D:/git/..../errorReportR.txt
```

**Comment by gowthamrao** [comment]
Maybe a different issue


But if i do `dplyr::count(results$covariates)` i get 

```
# Source:   lazy query [?? x 1]
# Database: sqlite 3.34.1
#   [D:\git\........\andromedaTemp\file1a48..d91233.sqlite]
        n
    <int>
1 2300000
```

which is different from

```
Browse[3]> dplyr::count(covariates)
# Source:   lazy query [?? x 1]
# Database: sqlite 3.34.1
#   [D:\git\..\file1a48..d91233.sqlite]
        n
    <int>
1 2776756
```

**Comment by gowthamrao** [comment]
I am beginning to suspect this is an Andromeda issue

**Comment by schuemie** [comment]
@gowthamrao : could you share with me the code that fully reproduces this error? So all steps that I would need to reproduce this problem on my machine.

**Comment by ablack3** [comment]
I ran the development version of cohort diagnostics on one cohort in WebAPI mode and did not encounter this error.

```
Characterizing cohorts
Starting large scale characterization of 1 cohort(s)
Constructing features on server
  |===============================================================| 100%
Executing SQL took 4.77 mins
Fetching data from server
Fetching data took 4.86 secs
Cohort characterization took 4.99 mins
Running Characterization took 5.03 mins
```

**Comment by gowthamrao** [comment]
Fixed these issues that were discovered while trouble shooting this issue
https://github.com/OHDSI/CohortDiagnostics/commit/cc15504821d03544816fd6db8cf47fbbfb920928

**Comment by schuemie** [comment]
We found the root cause in FeatureExtraction, which is documented [here](https://github.com/OHDSI/FeatureExtraction/issues/121). This bug can cause the sum of a binary covariate to exceed the population size in very exceptional cases. This caused the computed proportion to be become greater than 1 [here](https://github.com/OHDSI/CohortDiagnostics/blob/develop/R/CohortCharacterizationDiagnostics.R#L75), causing the square root to be taken of a negative number in the next line. This caused the Andromeda object to become invalid.

**Comment by gowthamrao** [comment]
Excellent! Thank you @schuemie I will test this commit https://github.com/OHDSI/FeatureExtraction/commit/c08734df167e72cd71c55884d0f73d79884ae4b7#diff-ffaa986989416ff38f5a56c5c2933e45d36bf6afc390216dce19516414cce6dd

I could not tell where you committed this (which branch) - it wasnt in develop

**Comment by anthonysena** [comment]
@gowthamrao - this set of changes is on on https://github.com/OHDSI/FeatureExtraction/tree/fix_aggregated_measurement_group. I'm giving it a review now so we can get it into the `develop` branch.

**Comment by gowthamrao** [comment]
The error is here
```

featureExtractionOutput$covariates %>% 
+   dplyr::rename(cohortId = .data$cohortDefinitionId) %>% 
+   dplyr::left_join(populationSize, by = "cohortId", copy = TRUE) %>% 
+   dplyr::mutate(p = .data$sumValue / .data$populationSize)  %>%  
+   dplyr::collect() %>% 
+   dplyr::mutate(sd = sqrt(.data$p * (1 - .data$p))) 
Warning: warning: Problem with `mutate()` input `sd`.
i NaNs produced
i Input `sd` is `sqrt(.data$p * (1 - .data$p))`.
```

**Comment by gowthamrao** [comment]
The changes in FF has fixed this issue

**Comment by gowthamrao** [comment]
Pending the release of Feature Extraction, i added an informative error message to Cohort Diagnostics here

https://github.com/OHDSI/CohortDiagnostics/commit/be25f268296afcbec88a8da857d6f4b5d9a0a883

**Comment by gowthamrao** [comment]
Closing issue with new release of FE. Thank you @anthonysena  @schuemie
