### ISSUE TITLE
If we want to execute ohdsi-studies using R-packages, how do we make it easier to create study R-packages!?

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#33]
It might be useful to be able to load json/sql directly from a local folder. 

https://github.com/OHDSI/CohortDiagnostics/blob/29aaaf756e86f1a285461c7cba220cb2f5894675/R/RunDiagnostics.R#L764

In current implementation, we have to create a R-package with cohort definitions and install them in R.  Instead, if are able to point to a folder in local drive that has the JSON/SQL specifications for cohort - it might be useful.

**Comment by schuemie** [comment]
I'm on the fence about this one. Yes, I understand people may want to do this, but this opens up the possibility to many potential mistakes being made. We should perhaps make it easier to create study packages, which is the preferred way of storing JSON and SQL locally.

**Comment by gowthamrao** [comment]
Agree - if we are able to make study packages easily that would probably be best option.  

One approach i spent some time on was to create a study-management package that specifies a template. The template may specify default folder structure and create some default content. e.g. extras, specifications folders.  It can also have package level instructions like what content goes where to be part of standard OHDSI study package. If there is a need to include data objects, we may require them to be in Sqllite (or rds). 

Do we have such a template (between the past works, hydra work etc?)

**Comment by schuemie** [comment]
I agree making study packages easier is an important goal.  We could have package templates as you suggest, or maybe some R functions that create a package for you? I honestly don't know the best solution.

I do think of the [PLE skeleton](https://github.com/OHDSI/SkeletonComparativeEffectStudy) as a template, complete with a [vignette](https://github.com/OHDSI/SkeletonComparativeEffectStudy/raw/master/inst/doc/UsingSkeletonPackage.pdf) on how to modify it for your study. I also try to include similar templates with other tools. CohortDiagnostics has two: a [generic template](https://github.com/OHDSI/CohortDiagnostics/tree/master/examplePackage) and [a template specific to PLE studies](https://github.com/OHDSI/CohortDiagnostics/tree/master/exampleComparativeCohortStudy), both with some instructions in the README.

**Comment by gowthamrao** [comment]
@schuemie  are you referring to a more generic OHDSI studies template package, or are you referring to a template for cohort diagnostics package that is able to create study package like the covid19 package?

Agree with you - making study packages is an important goal.

**Comment by schuemie** [comment]
I'm not sure what I'm referring to ;-)

All I know is that, in order to perform OHDSI network studies, we expect folks to create study packages that contain the cohort definitions, and support various tasks such as cohort diagnostics, characterization, estimation, etc. Creating such packages is non-trivial, and users could benefit from some help. 

For PLP and PLE, we have neat ATLAS editors that spit out these packages. Ideally we'd have the same for CohortDiagnostics (and PheValuator, etc.). Or we provide people with template packages for each, with instructions on how to modify them. Maybe we create Shiny editors equivalent to the ATLAS editors. Or we create some other process to do this. 

Ideas?

**Comment by gowthamrao** [comment]
I think we create some meta-process to do this.

I started thinking about creating a package called '[StudyManagement](https://github.com/gowthamrao/studymanagement)'  , the idea being it is a meta-package that is able to achieve this vision. (the current implementation is only remotely close to that vision as it has waivered)

Straw man principles
- From end-user perspective, the 'CodeToRun.R' should just run the whole study. 
-  It would instantiate the cohort, run diagnostics/phevaluator, characterization, IR, estimation, prediction etc. all coordinated. 
- Information such as connections, passwords etc should all be either requested at run-time or securely packaged/sourced. We could have a shiny app instead of codeToRun.
- Package management is solved - somehow like Docker.
- The results should be collected in standard, portable manner (preferably in csv, SqlLite and/or rds) into some extension of results CDM like that of SkeletonComparativeEffectStudy. This data model would apply for every analytics category - not just estimation. The results from various networks may be appended and put in a rdms or local (similar to how we are doing in skeleton comparative effect study).
- We support standard and custom visualization/reporting - based on results in this extended results data model. i.e. we create tables/visual even text reports. During package creation, we allow standard set and custom reports - generated from results in this results data model.
- R is the primary tool to do this. 


I think it is possible to do and is needed.

**Comment by schuemie** [comment]
I agree with most of these ideas, although it is not obvious how most of these things should be implemented. I'm not sure how to move this forward. Ideas?

Quick note: results that will be shared across sites **must** be human-reviewable. No site should agree to share data if they don't know (basically at a byte-level) what they are sharing. For that reason, any binary format (rds, SQLite) is out of the question. I've standardized my packages to output zipped CSV files. I currently ensure that no cell count in these CSV files are below a user-specified threshold, to guarantee we don't share patient-level data.

**Comment by cgreich** [comment]
Friends: 
We need to step back here. I know right now we are cutting every corner to get the study-a-thon done, but I repeat my caveat that R packages are not a good way of distributing analytics through Github. Reasons:

- It is not secure. Many institutions will not allow for some code to come in and run on the patient data. My organization doesn't. I have to vouch personally for the trustworthiness of the code. They just opened up Github, before it was blocked.
- It doesn't scale in the OHDSI stack. R of course runs everywhere, but the whole situation with having SQL code embedded and then translated to any possible backend is robbing @schuemie of development time for real solutions.

Can we start having those conversations of how we are going to do it?

**Comment by gowthamrao** [comment]
@cgreich i know some institutions are resistant to R, but professionally managed R-environments such as R-studio enterprise are becoming more common. Those are considered "enterprise grade" solutions that many institutions have embraced ~ motivated by the increased security/log/role based access control etc.. There are similar managed solutions from big name vendors such as Microsoft, AWS, and IBM too. Plus, as @schuemie pointed out - the output is in csv which is human readable and can be opened for audit reviews. 

> It doesn't scale in the OHDSI stack. R of course runs everywhere, but the whole situation with having SQL code embedded and then translated to any possible backend is robbing @schuemie of development time for real solutions.

is the suggestion to use SQL for complex statistics (instead of R?).
