### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/CohortDiagnostics#34]
Figured I'd just log instead of doing a PR - but happy to do that if you want.

(1)
https://github.com/OHDSI/CohortDiagnostics/blob/c3f2b7a0e67c2e793c518e3d307d2dbd279372d4/inst/shiny/DiagnosticsExplorer/html/timeDistribution.html#L32

within is spelled wrong.

(2)
https://github.com/OHDSI/CohortDiagnostics/blob/c3f2b7a0e67c2e793c518e3d307d2dbd279372d4/inst/shiny/DiagnosticsExplorer/html/includedConcepts.html#L11

included is spelled wrong.

Also convert shouldn't to should not.

(3)
https://github.com/OHDSI/CohortDiagnostics/blob/c3f2b7a0e67c2e793c518e3d307d2dbd279372d4/inst/shiny/DiagnosticsExplorer/html/inclusionRuleStats.html#L21

inclusion is spelled wrong.

(4)
https://github.com/OHDSI/CohortDiagnostics/blob/88c4406144caaeb34616eb47acd16e9c7e3aabe6/inst/shiny/DiagnosticsExplorer/html/indexEventBreakdown.html#L10

identifies is spelled wrong.

**Comment by schuemie** [comment]
Thanks! Now fixed in the develop branch. Will be included in the next release.
