### ISSUE TITLE
Error converting from `double` in zip to `bigint` in schema when uploading to remote db

### ISSUE THREAD

**Issue by msuchard** [OHDSI/CohortDiagnostics#341]
This snippet:

```
createResultsDataModel(connectionDetails = connectionDetails,
                                          schema = schema)

uploadResults(
  connectionDetails = connectionDetails,
  schema = schema,
  zipFileName = "Results_DB.zip")
```

causes

```
Error: Can't join on `x$analysis_id` x `y$analysis_id` because of incompatible types. 
ℹ `x$analysis_id` is of type <integer64>>. 
ℹ `y$analysis_id` is of type <double>>. 
```

because `readr::read_csv` reads `id` columns as `double` by default.   Changing the `bigint` -> `int` in `resultsDataModelSpecification.csv` avoids the error, but is suboptimal because we'd like to allow `int64` ids.  

... in need a fix.

**Comment by msuchard** [comment]
Seem like the fix should go somewhere around here: https://github.com/OHDSI/CohortDiagnostics/blob/6d863fc9c68856b9577d5b45eebccf84f6e9b2bc/R/ResultsDataModel.R#L89

**Comment by gowthamrao** [comment]
@msuchard  just curious what db are you experiencing this? i had not experienced this before

**Comment by msuchard** [comment]
Hi @gowthamrao -- let me send you the `*.zip` file.

**Comment by gowthamrao** [comment]
Hi @msuchard . i am unable to reproduce this. 

There is an issue with date with DatabaseConnector (maybe totally unrelated) that is fixed in develop branch of databaseconnector
https://github.com/OHDSI/DatabaseConnector/issues/137
https://github.com/OHDSI/CohortDiagnostics/issues/343

**Comment by msuchard** [comment]
This magically went away by re-installing the same (?) version of `DatabaseConnector` (v4.0).
