### ISSUE TITLE
Differences in cohort.csv can create duplicate entries in shiny results viewer

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/CohortDiagnostics#36]
When Cohort Diagnostics is run across a network, one of the files produced is the `cohort.csv` which at this time consists of the following columns:

````
cohort_full_name,
cohort_id,
cohort_name,
sql,
json
````

During our experiencing in running the COVID characterization study, I noted differences in this file coming from different sites. These differences were immaterial but I thought it would be good to note them here. Specifically:

- The sql produced between the sites used difference approaches for constructing the cohort concept sets as detailed in OHDSI/circe-be#114 
- The JSON serialization had differences in the way attributes were listed. Specifically, the attributes of concepts in the concept sets were in different orders for some reason. 

When differences occur between sites in these fields, the result is that the Shiny app treats these as different cohorts so we wind up seeing duplication of cohorts with the same name but underlying that differences in the JSON/SQL fields. 

I think it makes sense to share the specific JSON/SQL used at each site but perhaps these fields should be ignored for the purposes of presenting the results?

**Comment by schuemie** [comment]
If you're running a network study, I would think the best practice is to use the package approach, where JSON and SQL are embedded in the study package. That guarantees everyone is running the same analysis. Would you agree?

**Comment by anthonysena** [comment]
> If you're running a network study, I would think the best practice is to use the package approach, where JSON and SQL are embedded in the study package. That guarantees everyone is running the same analysis. Would you agree?

Totally agreed. We've embedded the SQL & JSON for the https://github.com/ohdsi-studies/Covid19HospitalizationCharacterization/ packages. Looking at the code [here](https://github.com/OHDSI/CohortDiagnostics/blob/master/R/RunDiagnostics.R#L109-L119), the `cohorts.csv` should simply return the cohorts loaded from the package (which should always be the same). So, it sounds like I may need to talk with the partners running the package to see why their `cohort.csv` differs from the one that is embedded in the package. Thanks!
