### ISSUE TITLE
Remove code duplication in preparing data for Shiny app

### ISSUE THREAD

**Issue by schuemie** [OHDSI/CohortDiagnostics#38]
There are currently two places where data is prepared (premerged) for the Shiny app: [here](https://github.com/OHDSI/CohortDiagnostics/blob/master/R/Shiny.R#L58) and [here](https://github.com/OHDSI/CohortDiagnostics/blob/master/inst/shiny/DiagnosticsExplorer/global.R#L16). 

I suggest we drop the code in `global.R`, and make running `preMergeDiagnosticsFiles` required. (We may also want to rename it to something like `prepareForShiny`.

**Comment by gowthamrao** [comment]
Done as part of version 2

**Comment by katy-sadowski** [comment]
The CohortDiagnostics Using WebAPI document needs to be updated to indicate that `preMergeDiagnosticsFiles` is now required :) thanks!
