### ISSUE TITLE
readr::read_csv by default trims white space

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#39]
https://github.com/OHDSI/CohortDiagnostics/blob/0dda7c80f1853d804461c9e936b0b61ec0cc92d2/R/RunDiagnostics.R#L774

Atlas allows trailing white spaces in definition names (its also allows names that are not legal in Windows). This causes issues, if the trailing white space is also present in 'cohortSetReferences' or 'CohortsToCreate.csv'

readr::read_csv by default trims the white space. it throws an error of file not found.

Solution: override the default behavior of readr::read_csv with trim_ws = FALSE (default TRUE); or make sure cohortSetReferences and/or CohortsToCreate.csv dont accept WS.

I think the simplest is to change the default behavior of readr. @schuemie

**Comment by schuemie** [comment]
I don't think not trimming white space is the solution. This will cause many issues downstream. 

Can you help me understand the problem a bit better? If CohortDiagnostics is trimming the white spaces, I'd say that is the right behavior, and if done consistently, all should be fine. Are there other tools not trimming white spaces? Where exactly does the problem occur? Are there SQL files being generated with trailing white spaces?

**Comment by gowthamrao** [comment]
Thanks. So we have atlasName & name in cohortSetReferences/CohortsToCreate.csv 

> 
> atlasName
> The full name of the cohort. This will be shown in the Shiny app.
> 
> name
> A short name for the cohort, to use to create file names. do not use special characters.
> 

If name has a trailing white-space, then it would cause this error. Trailing white space is a valid file name in windows, so we could have an sql file in package that is 'abcde   .sql'. (i am not sure - is space a special character, but it is valid file name)

I experienced a situation where there was trailing white space in the sql name - and the error message took sometime to debug.

**Comment by schuemie** [comment]
So the problem is that ROhdsiWebApi is [not using readr](https://github.com/OHDSI/ROhdsiWebApi/blob/develop/R/CohortDefinition.R#L188), and therefore introduces these white spaces?

Having a trailing white space in a file name is bad. I'm sure there are file systems that will choke on that.

**Comment by gowthamrao** [comment]
Not just ROhdsiWebApi, but also Atlas. Atlas accepts names with trailing spaces. 

I think one implicit assumption is that all studies flow out from Atlas, i.e. atlas is the starting place to name objects. Atlas allows trailing spaces - so if we dont want trailing spaces we need to fix it in Atlas. If we fix it downstream only, we may have errors like i experienced.

Agree with you though - we should not be using trailing white space or allow names that have certain special characters. But, i think the better practice is that this rule should be applied to Atlas and be explicitly stated upfront as a OHDSI convention (instead of making assumptions or fixing downstream).

So, i propose we don't remove trailing white space in cohort-diagnostics or ROhdsiWebApi but create a naming convention and enforce that in Atlas.

**Comment by schuemie** [comment]
I agree we should create an issue about this in WebAPI, but at the same time we should also just always be consistent. In theory, there's nothing wrong with a WebAPI universe that allows trailing white spaces, and an R / file system universe where we don't, as long as we're consistent at the boundary between the two. 

In other words, I recommend changing ROhdsiWebApi to use readr, in addition to raising an issue for WebAPI.

**Comment by gowthamrao** [comment]
Closing PR - in favor of assuming that file name wont have trailing white space.
