### ISSUE TITLE
Add a vignette documenting how to use CohortDiagnostics in a study package

### ISSUE THREAD

**Issue by schuemie** [OHDSI/CohortDiagnostics#41]
There's already one for when using WebAPI to store the cohort definitions. Need a similar one for when storing them in a study package.

Could reference the [example package](https://github.com/OHDSI/CohortDiagnostics/tree/master/examplePackage).

**Comment by gowthamrao** [comment]
We will use hydra as explained here

https://github.com/OHDSI/CohortDiagnostics/issues/8
