### ISSUE TITLE
characterization table - drugs truncate at the letter P

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/CohortDiagnostics#42]
In the cohort diagnostics characterization table under pretty view the drugs truncate at the letter P. If the table is switched to the raw view there are drugs through the letter Z. 

Question - is the pretty characterization table filtered by a mean value? If so can there please be a footnote in the table that indicates the filtering threshold being applied? 

If it is not a filtering issue can you please add language explaining the criteria being used to generate the pretty characterization table?

**Comment by schuemie** [comment]
The covariates shown in the pretty table were hand-picked to be part of a standard OHDSI-wide human-readable characterization table. You can view the discussion that led to the selection of these concepts [here](https://forums.ohdsi.org/t/standard-table-1/2797/21). All our Shiny apps (and many of our papers) currently use this selection. The fact that the last drug name starts with a 'p' is a coincidence.

I'll try and make this clearer in the text behind the info button for this diagnostic.

**Comment by gowthamrao** [comment]
@schuemie  would this be related to https://github.com/OHDSI/CohortDiagnostics/issues/32

**Comment by jhardin29** [comment]
Thanks for the clear explanation and background @schuemie this is helpful information in explaining this to our internal cohort diagnostics users :)
