### ISSUE TITLE
Shiny mode message determined by default, not actual choice

### ISSUE THREAD

**Issue by schuemie** [OHDSI/CohortDiagnostics#422]
See https://github.com/OHDSI/CohortDiagnostics/blob/master/inst/shiny/DiagnosticsExplorer/global.R#L27

**Comment by gowthamrao** [comment]
@azimov have you had a chance to work on this?

**Comment by azimov** [comment]
@gowthamrao  not yet!

**Comment by gowthamrao** [comment]
remediated in 2.2
