### ISSUE TITLE
Optimize the computation of incidence rate

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#429]
Current implementation is to compute IR one cohort at a time. This seems to take time.

Compare to timSeries https://github.com/OHDSI/CohortDiagnostics/blob/master/inst/sql/sql_server/ComputeTimeSeries.sql which computes many cohorts at the same time and is exponentially faster.

Comparisons:

**Advantages of TimeSeries approach**
- timeSeries approach is fast (100x) and does multiple cohorts at the same time. `Running Incidence Rate took 7.05 mins; Running PrevalenceRate took 7 secs`
- but it has no age/gender strata as in IR, this may be added
- timeSeries has additional counts and prevalence statistics
- timeSeries gives by calendar month and year (can give weeks too - if we want, not sure why we would need that)
- both only do first occurrence of cohort

**Disadvantages of TimeSeries approach**
- does not support washout
- not using observation_period (i.e. persons in database) as denominator - so its not a rate at this time

Can an enhanced version of TimeSeries replace IR computation. Plus, we have a roadmap item to implement an external callable package that can support robust computation of IR (i.e. a standalone package) - that new package would replace the built in IR calculator in Cohort Diagnostics https://github.com/ohdsi-studies/Covid19VaccineAesiIncidenceCharacterization

**Comment by gowthamrao** [comment]
Related to https://github.com/OHDSI/CohortDiagnostics/issues/97

**Comment by azimov** [comment]
@anthonysena and @chrisknoll Weren't you working on the standard IR calculation?

I don't know where they got with this but it would definitly be ideal to move towards having a single method used across packages.
