### ISSUE TITLE
Add field for cohort person count, record count and person time to characterization output

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#44]
It would be informative to add cohort person count, record count and person time in cohort characterization section

**Comment by schuemie** [comment]
Record count can easily be added, as it is included the FeatureExtraction aggregate covariate output. Person count would require a change in FeatureExtraction, which would require a LOT of work (changes to all SQL files). 

Person time in cohort is just another covariate, which is not part of the default set, but is one of the prespecified analyses, as shown [here](https://github.com/OHDSI/FeatureExtraction/blob/master/inst/csv/PrespecAnalyses.csv#L11). 

I don't think any of these have very high priority for CohortDiagnostics (which is not a clinical characterization tool). Record count might be informative and easy to add.
