### ISSUE TITLE
Ordering of temporal characterization plots in 'Compare Temporal Char.' should be corrected

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/CohortDiagnostics#444]
Expected:

Graphs ordered as:  1)  -365 to -31d,    2) -30d to -1d,   3)  0d,   4)  1d to 30d,  5)  31d to 365d,  

reading left to right from furthest back in time to latest post-index.

Current:   graphs sorted by alphanumeric , so out of order,  2, 1, 3, 4, 5

![image](https://user-images.githubusercontent.com/731930/121780230-71707000-cb6d-11eb-98c6-832cba75fdbc.png)

**Comment by gowthamrao** [comment]
Can't solve using ggplot. Will use plotly

**Comment by gowthamrao** [comment]
Solved using plotly  - currently in develop

![image](https://user-images.githubusercontent.com/13936600/136215129-a653ce96-b249-4327-81fe-58dfd984f7a5.png)
