### ISSUE TITLE
Diagnostics Explorer exits when includedSourceConcept empty

### ISSUE THREAD

**Issue by MaximMoinat** [OHDSI/CohortDiagnostics#445]
If there are no included source concepts (e.g. when the cohort is just defined by deaths), then the Diagnostics Explorer exits with 'Problem with joining on databaseId and cohortId'. Probably on the following lines:
https://github.com/OHDSI/CohortDiagnostics/blob/93e8915b504318300c68a565945dd17807a88567/inst/shiny/DiagnosticsExplorer/R/Results.R#L316-L338

It would be good to make the code robust to empty data frames.

**Comment by gowthamrao** [comment]
Yes. I am changing the pattern for 2.2 here

the steps are

https://github.com/OHDSI/CohortDiagnostics/blob/developStaging/inst/shiny/DiagnosticsExplorer/R/ResultsDataModelQueries.R#L499

which is a wrapper on

https://github.com/OHDSI/CohortDiagnostics/blob/developStaging/inst/shiny/DiagnosticsExplorer/R/ResultsDataModelQueries.R#L163

that will return NULL if

https://github.com/OHDSI/CohortDiagnostics/blob/developStaging/inst/shiny/DiagnosticsExplorer/R/ResultsDataModelQueries.R#L210

which should then, hopefully be handled by

https://github.com/OHDSI/CohortDiagnostics/blob/447a1bf53d86639322218c2b314e6374e4c7b517/inst/shiny/DiagnosticsExplorer/server.R#L2027


@MaximMoinat  could you please test if that holds true by running your project on develop branch?

**Comment by gowthamrao** [comment]
@MaximMoinat  i am going to close this.. please let me know if the issue persists even in develop branch

**Comment by MaximMoinat** [comment]
Thanks a lot @gowthamrao !
