### ISSUE TITLE
not able to use launchDiagnosticsExplorer()

### ISSUE THREAD

**Issue by ChenyuL** [OHDSI/CohortDiagnostics#458]
Hi, 
I have a cohort diagnostics result run from WebApi mode, the launchDiagnosticsExplorer() function worked well a few days ago.  Today I tried to get the Shiny result again but failed: 
![image](https://user-images.githubusercontent.com/17032366/124159361-1396c000-da69-11eb-9435-ef0bc7ee8796.png)

Could someone help with this issue, Thank you!
Chenyu

**Comment by gowthamrao** [comment]
hi @ChenyuL  are you able to load the premerged file into R memory? Can you make sure that is not corrupted. Please also reinstall Cohort Diagnostics master branch. 

Just looking at the Error message at the bottom - i dont think it indicates an issue in Cohort Diagnostics

**Comment by ChenyuL** [comment]
Thank you I reinstalled the master branch and it works now!
