### ISSUE TITLE
Error / execution stops when: CDM_SOURCE has multiple entries

### ISSUE THREAD

**Issue by msuchard** [OHDSI/CohortDiagnostics#491]
This (https://github.com/OHDSI/CohortDiagnostics/blob/93e8915b504318300c68a565945dd17807a88567/R/RunDiagnostics.R#L1206) causes an error (since tibbles only recycle when length = 1) when `CDM_SOURCE` contains multiple entries.  

The error, unfortunately, stops execution.

**Comment by gowthamrao** [comment]
https://github.com/OHDSI/CohortDiagnostics/commit/15fe8bd45f32f08a993224a15af7142acd112ea0
