### ISSUE TITLE
Cohort diagnostic - Translation error for query in  ComputeTimeSeries.sql

### ISSUE THREAD

**Issue by Linasulieman** [OHDSI/CohortDiagnostics#503]
I am trying to run the CohortDiagnostic function on a database that is saved in a BigQuery schema. When I ran the the runCohortDiagnostics function I got this error that was generated for the query in  ComputeTimeSeries.sql
**The error that I got was:**
Error:
java.sql.SQLException: [Simba]BigQueryJDBCDriver Error executing query job. Message: Column 6 contains an aggregation function, which is not allowed in GROUP BY at [53:19]

SQL:
select cohort_definition_id cohort_id
,period_begin
,calendar_interval
,count() records
,count(distinct subject_id) subjects
,sum(date_diff(if(safe_cast(case 
  		when cohort_end_date >= period_end
  			then period_end
  		else cohort_end_date
  		end  as date) is null,parse_date('%Y%m%d', cast(case 
  		when cohort_end_date >= period_end*
  			then period_end
  		else cohort_end_date
  		end  as string)),safe_cast(case 
  		when cohort_end_date >= period_end
  			then period_end
  		else cohort_end_date
  		end  as date)), if(safe_cast(case 
  		when cohort_start_date >= period_begin
  			then cohort_start_date
  		else period_begin
  		end  as date) is null,parse_date('%Y%m%d', cast(case 
  		when cohort_start_date >= period_begin
  			then cohort_start_date
  		else period_begin
  		end  as string)),safe_cast(case 
  		when cohort_start_date >= period_begin
  			then cohort_start_date
  		else period_begin
  		end  as date)), day) + 1) person_days
,count(case when cohort_start_date >= period_begin
  		and cohort_start_date <= period_end
  		then subject_id
  	else null
  	end) records_incidence
,count(distinct case 
  	when cohort_start_date >= period_begin
  		and cohort_start_date <= period_end
  		then subject_id
  	else null
  	end) subjects_incidence
from test_writable_sulieman.cohorttabletest
inner join ofcjbawzcalendar_periods cp on (
  cohort_start_date >= period_begin
  and cohort_start_date <= period_end
  )
or (cohort_end_date >= period_begin and cohort_end_date <= period_end )
where cohort_definition_id in (101431)
group by 2, 3, 6 ;

**Reason**
After investigating, I realized that the query is suppose to group on column 1,2, and 3. The query rename  column 1 as shown earlier in the query. Apparently the renaming of column 1 misses up the order or numbering in GROUP BY and always replaces 1 with 6. So renaming a column that will be used in GROUP BY will mess up the order during translation.

**Fix**
To fix this, I rewrote the query to have an outer and an inner query. All the renaming processes for columns that will be used in GROUP BY should happen in the inner query. I moved the GROUP BY to the outer query to avoid renaming and grouping on the same column in the same query. After rewriting the query, the function worked.  the I included below the query that I wrote to solve this error:

SELECT cohort_id,period_begin,calendar_interval, 
COUNT_BIG(*) records,
COUNT(DISTINCT subject_id) subjects,
SUM(days) person_days,COUNT_BIG(r_incidence) records_incidence,COUNT_BIG(DISTINCT s_incidence) subjects_incidence
FROM 
(SELECT cohort_definition_id cohort_id
  ,period_begin
	,calendar_interval
	
	,subject_id
	,(datediff(dd, CASE 
				WHEN cohort_start_date >= period_begin
					THEN cohort_start_date
				ELSE period_begin
				END, CASE 
				WHEN cohort_end_date >= period_end
					THEN period_end
				ELSE cohort_end_date
				END) + 1) days
	,(CASE 
			WHEN cohort_start_date >= period_begin
				AND cohort_start_date <= period_end
				THEN subject_id
			ELSE NULL
			END) r_incidence
	,( CASE 
			WHEN cohort_start_date >= period_begin
				AND cohort_start_date <= period_end
				THEN subject_id
			ELSE NULL
			END) s_incidence
FROM @cohort_database_schema.@cohort_table
INNER JOIN #calendar_periods cp ON (
		cohort_start_date >= period_begin
		AND cohort_start_date <= period_end
		)
	OR (
		cohort_end_date >= period_begin
		AND cohort_end_date <= period_end
		)
WHERE cohort_definition_id IN (@cohort_ids)
)
GROUP BY cohort_id,period_begin,calendar_interval;

**Comment by gowthamrao** [comment]
Thank you. I plan to work on this mid August.

**Comment by Linasulieman** [comment]
You are welcome. I believe there are other queries or files that might have the same problem. I will post the names of the files

**Comment by gowthamrao** [comment]
Excellent. Thank you

**Comment by gowthamrao** [comment]
@Linasulieman  i am thinking this is more complicated and we may need a different approach for time series computation. Because of complexity, i would like to propose that we handle the SQL changes in 2.2 release.

For 2.1.1 hot fix, I propose that we do a simple solution - that is to turn off timeSeries when using BigQuery and issue a warning. 

Please let me know if these changes are acceptable. See commit here https://github.com/OHDSI/CohortDiagnostics/commit/bb6386eb64e4a6ec887067dee031bc2ac92746ce
