### ISSUE TITLE
<Creating internal concept counts table> How long it should take

### ISSUE THREAD

**Issue by lofung** [OHDSI/CohortDiagnostics#517]
We have some slightly larger tables, around 2TB in total and about 2 billion records on the bigger ones. Our code has been stuck there for about 36 hours and the SQL shows the code is still actively running.

  Instantiating concept sets
  |======================================================================| 100%
Creating internal concept counts table
  |=======================                                               |  33%

"Creating internal concept counts table" has been in 33% for long already. How long is everyone running "Creating internal concept counts table"?

**Comment by gowthamrao** [comment]
The SQL is here https://github.com/OHDSI/CohortDiagnostics/blob/master/inst/sql/sql_server/CreateConceptCountTable.sql

What it is
```

	SELECT condition_concept_id AS concept_id,
		COUNT_BIG(*) AS concept_count,
		COUNT_BIG(DISTINCT person_id) AS concept_subjects
	FROM @cdm_database_schema.condition_occurrence
	GROUP BY condition_concept_id
	
	UNION ALL
	
	SELECT condition_source_concept_id AS concept_id,
		COUNT_BIG(*) AS concept_count,
		COUNT_BIG(DISTINCT person_id) AS concept_subjects
	FROM @cdm_database_schema.condition_occurrence
	GROUP BY condition_source_concept_id
	
	UNION ALL
	
	SELECT drug_concept_id AS concept_id,
		COUNT_BIG(*) AS concept_count,
		COUNT_BIG(DISTINCT person_id) AS concept_subjects
	FROM @cdm_database_schema.drug_exposure
	GROUP BY drug_concept_id
	
	UNION ALL
	
	SELECT drug_source_concept_id AS concept_id,
		COUNT_BIG(*) AS concept_count,
		COUNT_BIG(DISTINCT person_id) AS concept_subjects
	FROM @cdm_database_schema.drug_exposure
	GROUP BY drug_source_concept_id
	
	UNION ALL
	
	SELECT procedure_concept_id AS concept_id,
		COUNT_BIG(*) AS concept_count,
		COUNT_BIG(DISTINCT person_id) AS concept_subjects
	FROM @cdm_database_schema.procedure_occurrence
	GROUP BY procedure_concept_id
	
	UNION ALL
	
	SELECT procedure_source_concept_id AS concept_id,
		COUNT_BIG(*) AS concept_count,
		COUNT_BIG(DISTINCT person_id) AS concept_subjects
	FROM @cdm_database_schema.procedure_occurrence
	GROUP BY procedure_source_concept_id
	
	UNION ALL
	
	SELECT measurement_concept_id AS concept_id,
		COUNT_BIG(*) AS concept_count,
		COUNT_BIG(DISTINCT person_id) AS concept_subjects
	FROM @cdm_database_schema.measurement
	GROUP BY measurement_concept_id
	
	UNION ALL
	
	SELECT measurement_source_concept_id AS concept_id,
		COUNT_BIG(*) AS concept_count,
		COUNT_BIG(DISTINCT person_id) AS concept_subjects
	FROM @cdm_database_schema.measurement
	GROUP BY measurement_source_concept_id
	
	UNION ALL
	
	SELECT observation_concept_id AS concept_id,
		COUNT_BIG(*) AS concept_count,
		COUNT_BIG(DISTINCT person_id) AS concept_subjects
	FROM @cdm_database_schema.observation
	GROUP BY observation_concept_id
	
	UNION ALL
	
	SELECT observation_source_concept_id AS concept_id,
		COUNT_BIG(*) AS concept_count,
		COUNT_BIG(DISTINCT person_id) AS concept_subjects
	FROM @cdm_database_schema.observation
	GROUP BY observation_source_concept_id
```

**Comment by gowthamrao** [comment]
This sql ofcourse should be optimized and i will be optimizing it for next release -- but for now

are you able to confirm that all the tables above have the proper keys/constraints established on your database system. What database system are you using (e.g. postgres, redshift etc)

**Comment by gowthamrao** [comment]
For next version of Cohort Diagnostics my plan is:

- remove dependency on generation of this count for concept set diagnostics (i.e. orphan concepts mostly)
- get all the conceptIds that the cohorts being diagnosed depends on (resolved/excluded/mapped/orphan etc) and perform counts for only those conceptIds. While couting, do the counts one table at a time (appending them on R) - thus reducing the CPU needs on the database side

In my testing it runs so much faster

**Comment by lofung** [comment]
The last minute on Friday I realize we have never optimized our postgreSQL postgresql.conf

So it is still exactly like this
https://github.com/postgres/postgres/blob/master/src/backend/utils/misc/postgresql.conf.sample

The database was installed by the vendor and by some seniors. And it looks like they had not touched postgresql.conf at all. I guess it is the reason why it took so long to do anything. (What odd was that general SELECT * FROM TABLE table would work though).
