### ISSUE TITLE
Deduplicate cohorts in Shiny app

### ISSUE THREAD

**Issue by schuemie** [OHDSI/CohortDiagnostics#52]
When CohortDiagnostics is run across both Windows and non-Windows machines, the cohort.csv files are different because one uses `\n` and the other uses `\r\n` as end-of-line. This causes duplication of the cohorts in the Shiny app.

One quick fix is to switch [this line](https://github.com/OHDSI/CohortDiagnostics/blob/master/inst/shiny/DiagnosticsExplorer/global.R#L63) with the next.

**Comment by gowthamrao** [comment]
https://github.com/OHDSI/CohortDiagnostics/blob/e1cf412b3a9d56e069cbe2924250f1b8e2311573/inst/shiny/DiagnosticsExplorer/global.R#L63
