### ISSUE TITLE
Error: Can’t combine `database_id` <double> and `database_id` <character>

### ISSUE THREAD

**Issue by lofung** [OHDSI/CohortDiagnostics#521]
I have come to such error when running ````CohortDiagnostics:::runConceptSetDiagnostics(...)````

````
- Censoring 257 values (13.7%) from conceptCount because value below minimum
- Censoring 259 values (13.8%) from conceptSubjects because value below minimum
Finding orphan concepts took 8.13 mins

Error: Can't combine `database_id` <double> and `database_id` <character>.
````

Given the context, I assume it is after line 862 of https://github.com/OHDSI/CohortDiagnostics/blob/master/R/ConceptSets.R

Just interested, how do you mitigate such error? There is very little documentation how we should fill in our databaseId, and I am not sure if it is our fault. 

Thanks

**Comment by gowthamrao** [comment]
databaseId is expected to a character string name. 

Are you running in incremental mode? I think maybe you have a csv file in output folder called database, and that has a NA/integer value for databaseId field?

**Comment by lofung** [comment]
I am not entirely sure.

Currently these are the lines

````
"database_id","database_name","description","vocabulary_version_cdm","vocabulary_version","is_meta_analysis"
"HKU CSMPR","HKU_database","what_description_i_need","v5.0 17-DEC-19","v5.0 17-DEC-19",0
````

Previously, it was

````
"database_id","database_name","description","vocabulary_version_cdm","vocabulary_version","is_meta_analysis"
"999","HKU_database","what_description_i_need","v5.0 17-DEC-19","v5.0 17-DEC-19",0
````

````999```` is something I put in randomly. Not sure if it would lead to an error

**Comment by gowthamrao** [comment]
OK - thank you. Glad it worked for you. I will add a line in code in future version that ensure database_id is character
