### ISSUE TITLE
Interpreting the incidence rate output

### ISSUE THREAD

**Issue by Ak784** [OHDSI/CohortDiagnostics#54]
Hi,

I recently came across this package and was trying the `getIncidenceRate` function.

Is there any simple tutorial on explaining the output? Meaning for ex, when I ran the incidence rate function, my output was like as shown below. Is anything wrong with my data? In our data, the dates are shifted but chronological order is maintained as such for the patients.

![image](https://user-images.githubusercontent.com/61312399/81276253-563b5300-9085-11ea-9b5e-18d2d0028dc8.png)

1)  I am wondering why IncidenceRate column has such unusual value? What can be the issue that is causing this?

2) As you can see above in screenshot, the records are repeating. Once with `gender = NA` and once with `gender value as male or female`. May I know the reason behind why we see it as two records when we could retain only the latter?

3) As you can see that Age group values are bit off as well. Does it mean my data has age values like 120,190, 220 or 290 etc?

4) When I run this function and sort the calendar year based on ascending order, it starts with `NA` in first three rows and then has `2016, 2017 etc`. May I know how was 2016 chosen? Because my data has no records with year component as 2016. Though I see cohort count as 0 but I see some values in person_years column. Hence was bit confused. 

![image](https://user-images.githubusercontent.com/61312399/81277037-6bfd4800-9086-11ea-8043-cde7a8b72ee8.png)

5) How to also launch the UI version/web version of this output with graphs as shown readme page? Right now when I run the function, it outputs a dataframe.

Can help please?

**Comment by gowthamrao** [comment]
Good morning @Ak784 

I think it is possible that you have a data quality issue. Do you have the Achilles or Data Quality report for your datasource? Maybe that is the first place to check.

- Could you confirm if for those age category, both gender exist in the data
- the age groups seem to have ranges that are not possible 290-299?
- the sql that computes the incidence rate is [here](https://github.com/OHDSI/CohortDiagnostics/blob/master/inst/sql/sql_server/ComputeIncidenceRates.sql)  . The calendar year are determined by simple `year(cohort_start_date)` . So the 2016 choice should be determined by your cohort table.
- UI is a R shiny application. It relies on the output this [function](https://github.com/OHDSI/CohortDiagnostics/blob/master/R/RunDiagnostics.R). Incidence rate is one of the parameters of this function.

Hope that helps

**Comment by Ak784** [comment]
Hi @gowthamrao ,

Thanks for your response. But can I check with you on few quick things?

I am using a specific cohort (from cohort table) to generate the incidence rate.

When I manually write the query to get their Age, it only ranges from 16-90 years.

```
select a.subject_id, a.cohort_start_date, b.year_of_birth, 
(EXTRACT('year' FROM cohort_start_date) - EXTRACT('year' FROM BIRTH_DATETIME)) as age 
from results.cohort a
inner join cdm.person b
on a.subject_id = b.person_id
where cohort_definition_id = 71 
order by (EXTRACT('year' FROM cohort_start_date) - EXTRACT('year' FROM BIRTH_DATETIME)) 
```

But when I use the `getIncidenceRate`, In the dataframe I am able to see `AgeGroups` from 0-9 till 290-299. 

I am curious to know why do I see these unusual age groups?

I believe the CohortDiagnostics package generates Age group only based on the cohort Id mentioned in the `getIncidenceRate` function and not for the full dataset.

**Comment by gowthamrao** [comment]
> I believe the CohortDiagnostics package generates Age group only based on the cohort Id mentioned in the getIncidenceRate function and not for the full dataset.

The age groups are computed by the SQL directly from your cohort here
https://github.com/OHDSI/CohortDiagnostics/blob/0dda7c80f1853d804461c9e936b0b61ec0cc92d2/inst/sql/sql_server/ComputeIncidenceRates.sql#L13

It uses `year_of_birth` - could you cross check year_of_birth field in your omop person table

**Comment by Ak784** [comment]
Hi @gowthamrao,

I tried with `year_of_birth` as well to calculate age and it remains the same. Meaning the age range from subjects in my cohort (for which I am trying to find the incidence rate) is from 16 years to 90 years.  Yes, I do have some subjects (like 6-8 people) in person table imputed with fake year_of_birth like 1900 due to missingness. But they aren't present in the cohortId =71 that I inputted to the GetIncidenceRate function. 

```
select a.subject_id, a.cohort_start_date, b.year_of_birth, 
(EXTRACT('year' FROM cohort_start_date) - year_of_birth) as age 
from results.cohort a
inner join cdm.person b
on a.subject_id = b.person_id
where cohort_definition_id = 71
order by (EXTRACT('year' FROM cohort_start_date) - year_of_birth)
```

I might be wrong here but when I had a quick look at the query that you shared and as there is an inner join, I was thinking that the Age groups are calculated on a cohort by cohort basis. Meaning the package will start calculating the Age group only after we input the cohortId (ex:71 in this case). Or Is it like Age group is calculated for the whole dataset and then those Age groups are applied to each cohort (71 in this case) configured in the function?. 

Can guide me on this?

**Comment by Ak784** [comment]
Hi @gowthamrao, Just a follow up, Can I check with you on this?

If this isn't really an issue, I can close it. Thanks for your time.

**Comment by gowthamrao** [comment]
>  Meaning the package will start calculating the Age group only after we input the cohortId (ex:71 in this case). Or Is it like Age group is calculated for the whole dataset and then those same Age groups are applied across to all cohorts (71 in this case) configured in the function?.

The age groups are computed separately for #numerator and #denominator and then joined in this script
https://github.com/OHDSI/CohortDiagnostics/blob/master/inst/sql/sql_server/ComputeIncidenceRates.sql

The only explanation i can think of is that some how the SQL is not working as expected in your db.

What is you database system?

**Comment by Ak784** [comment]
PostgreSQL is the DB that I use.

**Comment by gowthamrao** [comment]
@Ak784 i am closing this issue, because i am assuming it is resolved.
