### ISSUE TITLE
StratifyByAge only parameter issue with PlotIncidenceRate function?

### ISSUE THREAD

**Issue by Ak784** [OHDSI/CohortDiagnostics#55]
Hi,

I was trying to plot incidence rate for my data. When I ran the function `PlotIncidenceRate` with default parameters, it worked fine but wasn't clear (in terms of screen display). So I decided to play around with `TRUE` and `FALSE`  for `stratify*` paramters.

When I wrote a function with below configuration, it throws error

```
plotincidenceRate(
  incidenceRate = OP,   #OP is the object from `GetIncidenceRate function`
  minPersonYears = 1000,
  stratifyByAge = TRUE,
  stratifyByGender = FALSE,
  stratifyByCalendarYear = FALSE,
  fileName = NULL
)
```

I get the below error

`Error in FUN(X[[i]], ...) : object 'dummy' not found`

Whereas am able to execute the function by setting `TRUE` to `stratifyByGender` and setting other two parameters `FALSE` or by setting `TRUE` to `stratifyByCalendarYear` and setting other two paramters `FALSE`

May I know whether this is actually an issue or am I making any mistake here?

**Comment by SSMK-wq** [comment]
@Ak784 I am also encountering this issue. Do we have any updates on this?

**Comment by gowthamrao** [comment]
Hi @Ak784 @SSMK-wq - I will try to answer this question, but @schuemie  is the original developer of the package who wrote this code. I took on responsibility as package maintainer recently and am still learning.

My initial thoughts are that if we
```
stratifyByCalendarYear = FALSE
stratifyByGender = FALSE
```
leaving `stratifyByAge = TRUE`
then the x-axis is not calendarYear anymore i.e. there is no plot. All we have is incidence rate by Age-strata, not incidence rate by Age-strata/gender-strata/no-strata over calendar years. The `plotincidencerate` function is designed to output plot over calendarYears on x-axis.

**Comment by gowthamrao** [comment]
Given the chosen parameters, you would expect to receive a bar plot, not a line plot. That would be determined using this logic

https://github.com/OHDSI/CohortDiagnostics/blob/0dda7c80f1853d804461c9e936b0b61ec0cc92d2/R/IncidenceRates.R#L262

`dummy` is assigned to x-axis in this logic.

and plot is created here
https://github.com/OHDSI/CohortDiagnostics/blob/0dda7c80f1853d804461c9e936b0b61ec0cc92d2/R/IncidenceRates.R#L279

My high level review - does not show any bugs. Could you please confirm you have data in your `OP` object after applying the parameters?


I think @schuemie wrote the dummy to be a catch

**Comment by Ak784** [comment]
Yes, I do have data on my OP object.  

For ex:

a) If we stratify only by Age (Gender), on X-axis we have Gender and on Y-axis we have incidence rate. ex: In our dataset, Male had an incidence rate of 310.12.

b) If we stratify only by calendar year (TRUE), on X-axis we have Calendar year and on Y-axis we have an incidence rate... Works fine... ex: In the calendar year between 2010-2015, incidence rate was 323.34, etc

Based on the above two examples, I was expecting that we can get an incidence rate based on Age as well.

ex: Between Age 60-65, the incidence rate was 305.23

Please note all the numbers above are just for example. But just wondering why can't we have like shown in the example above when other parameters don't depend on calendar year?
