### ISSUE TITLE
Why do we get NA's during comparing characteristics of cohorts?

### ISSUE THREAD

**Issue by SSMK-wq** [OHDSI/CohortDiagnostics#60]
Hi,

I first ran the `getCohortCharacteristics()` function for 2 of my cohorts (c1 and c2) and it outputted me a data frame with **no NA values in my mean, std dev columns**.

For ex:  

c1 cohort characteristics have the below

`17003 | 0.004943297 | 0.070318809 | age group: 85-89`

c2 cohort characteristics have the below

`17003 | 0.004655099 | 0.068235507 | age group: 85-89`

Later when I ran `compareCohortCharacteristics()` by inputting the objects generated through the above function, I see `NA` values in the output data frame for Mean and std dev.

For ex, the comparison object has the below output

`57003 | age group: 85-89 | NA | NA | 0.000211595 | 0.014547859 | NA | NA`

May I know why do we see `NA` when we try to compare cohorts but not while we get the characteristics of individual cohorts?

Am I missing something here?

**Comment by gowthamrao** [comment]
@SSMK-wq please check the develop version. Issue should be fixed

**Comment by gowthamrao** [comment]
resolved in version 2
