### ISSUE TITLE
Opaque error when running cohort diagnostitcs due to large observation_period_end_date in CDM

### ISSUE THREAD

**Issue by Jake-Gillberg** [OHDSI/CohortDiagnostics#613]
Hello, recently when running Pioneer, I ran into an opaque error, which propagated as a warning but appeared to be non-fatal bubbling up from cohort diagnostics. https://github.com/ohdsi-studies/PioneerWatchfulWaiting/issues/79

It looks like this stems from a few rows in our CDM which have an end_date of 9999 in our CDM, flowing over from some max date value that got populated somewhere in source data.

I know it's probably not recommended to have dates of 9999 as an end_date in the CDM, but it might be good to be defensive against this.

Can #calendar_years be updated to only contain the years relevant to the cohort? Or maybe this edge case can be dealt with in ComputeIncidenceRates? (the issue comes when we try to add 1 to the year 9999)

https://github.com/OHDSI/CohortDiagnostics/blob/2963a5db6b301ec8fd93fa3698cf1f1a5bfcf9ac/inst/sql/sql_server/GetCalendarYearRange.sql#L3-L5

https://github.com/OHDSI/CohortDiagnostics/blob/93e8915b504318300c68a565945dd17807a88567/R/IncidenceRates.R#L69-L80

https://github.com/OHDSI/CohortDiagnostics/blob/2963a5db6b301ec8fd93fa3698cf1f1a5bfcf9ac/inst/sql/sql_server/ComputeIncidenceRates.sql#L74

**Comment by gowthamrao** [comment]
@clairblacketer I was wondering if you would opine on this from DQ and (maybe themis conventions) perspective. 

Can Observation_period_end_date > current_date? Is that acceptable? If yes, do you think its reasonable to truncate to current_date at analysis time

(in this case, a data partner has observation_end_date year at 9999 - which makes SQL queries fail)

**Comment by Jake-Gillberg** [comment]
Sure @clairblacketer, this makes sense. At the same time, what do we gain by using future years when doing incidence rate analysis?

**Comment by gowthamrao** [comment]
@Jake-Gillberg  agree about 
> if we aren't defensive against this, we should probably elevate a clearer error to the end user in this case.

CohortDiagnostics (next version) is designed to capture some basic datasource level diagnostics to aid the interpretation of CohortDiagnostics. It does capture observation_period_start and observation_period_end information. Maybe we should use that as a piece of information about fit for use and not use datasources that dont follow best practices during ETL?

**Comment by gowthamrao** [comment]
Observation period range captured in version 3
