### ISSUE TITLE
CD crashes on shiny server when  runBreakdownIndexEvents = FALSE

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/CohortDiagnostics#643]
If I try to post to the J&J shiny server the premerge file when the above option is set to False it won't load/run. 

If i instead set the above to TRUE and post the premerge file to the server it loads fine. 

The ATLAS cohort ids are: 3609, 3610, 3612, 3613

The shiny link with the corrected premerge is here: https://sharedshiny-prod.jnj.com/user/jhardi10/EPI_916/

Tagging @aandryc

**Comment by gowthamrao** [comment]
what version of CD do you have?

**Comment by gowthamrao** [comment]
Can not reproduce - closing for now
