### ISSUE TITLE
Exported `covariate_value.csv` is not truncated for `sum` < `minCellCount`

### ISSUE THREAD

**Issue by msuchard** [OHDSI/CohortDiagnostics#658]
While the `mean` column is appropriately truncated for small cell counts via
```
dplyr::mutate(
        mean = dplyr::case_when(
          .data$mean != 0 &
            .data$mean < !!minCellCount / .data$cohortEntries ~ -!!minCellCount / .data$cohortEntries,
          TRUE ~ .data$mean
        )
      )
```
the `sum` column is not.   I just adding
```
dplyr::mutate(
        mean = dplyr::case_when(
          .data$sumValue != 0 &
            .data$sumValue < !!minCellCount ~ -!!minCellCount,
          TRUE ~ .data$sumValue
        )
      )
```
in two places in `ExportCharacterization.R`

However, I want to first confirm with @gowthamrao that this won't cause any down-stream issues in the shiny app.

**Comment by msuchard** [comment]
This issue appears much worse than I initially thought.   Not only is `sum_value` not getting truncated, but `mean` is not truncated as well.   I believe users of `CohortDiagnostics` are releasing public results that are *not* appropriately truncated to preserve privacy.  Here is a minimally reproducible example:

```
library(testthat)
library(CohortDiagnostics)
library(Eunomia)

connectionDetails <- Eunomia::getEunomiaConnectionDetails()
cdmDatabaseSchema <- "main"
cohortDatabaseSchema <- "main"
vocabularyDatabaseSchema <- cohortDatabaseSchema
cohortTable <- "cohort"
tempEmulationSchema <- NULL
folder <- tempfile()
dir.create(folder, recursive = TRUE)

  instantiateCohortSet(
    connectionDetails = connectionDetails,
    cdmDatabaseSchema = cdmDatabaseSchema,
    vocabularyDatabaseSchema = vocabularyDatabaseSchema,
    cohortDatabaseSchema = cohortDatabaseSchema,
    cohortTable = cohortTable,
    cohortIds = c(17492, 17692),
    packageName = "CohortDiagnostics",
    cohortToCreateFile = "settings/CohortsToCreateForTesting.csv",
    generateInclusionStats = TRUE,
    createCohortTable = TRUE,
    inclusionStatisticsFolder = file.path(folder, "incStats")
  )
  
  runCohortDiagnostics(
    connectionDetails = connectionDetails,
    cdmDatabaseSchema = cdmDatabaseSchema,
    vocabularyDatabaseSchema = vocabularyDatabaseSchema,
    cohortDatabaseSchema = cohortDatabaseSchema,
    cohortTable = cohortTable,
    cohortIds = c(17492, 17692),
    packageName = "CohortDiagnostics",
    cohortToCreateFile = "settings/CohortsToCreateForTesting.csv",
    inclusionStatisticsFolder = file.path(folder, "incStats"),
    exportFolder = file.path(folder, "export"),
    databaseId = "cdmv5",
    runInclusionStatistics = FALSE,
    runBreakdownIndexEvents = FALSE,
    runCohortCharacterization = TRUE,
    runTemporalCohortCharacterization = TRUE,
    runCohortOverlap = FALSE,
    runIncidenceRate = FALSE,
    runIncludedSourceConcepts = FALSE,
    runOrphanConcepts = FALSE,
    runTimeDistributions = FALSE,
    incremental = FALSE
  )
```
The current output in `<tempfolder>/export/covariate_value.csv` reads:
```
cohort_id,covariate_id,sum_value,mean,sd,database_id
17492,80180212,164,0.3424,0,cdmv5
17492,134438212,1,0.0021,0,cdmv5
17492,192671212,479,1,0,cdmv5
17492,257012212,1,0.0021,0,cdmv5
```

However, the correct output  _should_ read:
```
cohort_id,covariate_id,sum_value,mean,sd,database_id
17492,80180212,164,0.3424,0,cdmv5
17492,134438212,-5,-0.0104,0,cdmv5
17492,192671212,479,1,0,cdmv5
17492,257012212,-5,-0.0104,0,cdmv5
```
(note cohort size for 17492 is 479, so -0.0104 == -5 / 497)

Here is my code proposed code fix:

```
    characteristics$filteredCovariates <-
      characteristics$covariates %>%
      dplyr::filter(mean >= cutOff) %>%
      dplyr::mutate(databaseId = !!databaseId) %>%
      dplyr::left_join(counts,
                       by = c("cohortId", "databaseId"),
                       copy = TRUE) %>%
      dplyr::mutate(sd = dplyr::case_when(.data$mean >= 0 ~ sd)) %>%
      dplyr::mutate(
        mean = dplyr::case_when(
          .data$mean != 0 &
            .data$mean < !!minCellCount / as.double(.data$cohortEntries)  ~ -!!minCellCount / as.double(.data$cohortEntries),
          TRUE ~ .data$mean
        )
      ) %>%
      dplyr::mutate(
        sumValue = dplyr::case_when(
          .data$sumValue != 0 &
            .data$sumValue < !!minCellCount ~ -!!minCellCount,
          TRUE ~ .data$sumValue
        )
      ) %>%
      dplyr::mutate(mean = round(.data$mean, digits = 4),
                    sd = round(.data$sd, digits = 4)) %>%
      dplyr::select(-.data$cohortEntries, -.data$cohortSubjects)
```

@gowthamrao or @schuemie  -- can you confirm that you can reproduce and that I'm not mistaken about the truncation issue?  (A data partner for LEGEND-T2DM is complaining that their cohort diagnostics are releasing counts less than 5).

**Comment by schuemie** [comment]
I confirm the problem you raise is a real bug. This appears to be another downstream effect of me trying to be nice in DatabaseConnector, and recognize database integers as R integers. But R handles integers really badly (as in this case), so DatabaseConnector 5 will convert all integers back to numeric again.

```r
dplyr::mutate(sd = dplyr::case_when(.data$mean >= 0 ~ sd)) %>% # what is this condition for, anyway?
```
Should be executed after the mean is made negative if below `minCellCount`, and was intended to set SD to 0 if the output is truncated (because you can infer the mean from the SD for binary covariates). It seems the FALSE condition is not specified though.

I'll work on a fix. @gowthamrao: any rationale for the `!!` in front of `minCellCount`?

**Comment by schuemie** [comment]
My [commit](https://github.com/OHDSI/CohortDiagnostics/commit/c42bc7d117543fa9e1bdf757aead64b98ab5eea2) should fix this. Some notes:

1. I created a new branch off master, since develop seemed to be completely divorced from master.
2. For continuous covariates, truncating the mean makes no sense. For continuous covariates, there's also the min, max, median, etc. I implemented the logic that if the number of values < minCellCount the entire row for that covariate is removed.

**Comment by gowthamrao** [comment]
Hi, just saw this issue. 

regarding develop being divorced from master - that is a problem.

i will create a new develop and add your fixes to that. and we will maintain it the way it should be

i will maintain an experimental branch that will keep track of independent ideas

**Comment by gowthamrao** [comment]
@schuemie I think its ready for merge via https://github.com/OHDSI/CohortDiagnostics/pull/680

I am asking @azimov to do a quick review, and then we can merge and do a release?

**Comment by msuchard** [comment]
@gowthamrao -- may also want to adopt the unit-test I have [here](https://github.com/OHDSI/CohortDiagnostics/blob/6b5fcfa8fe004559aefb333c9f6d10c013943e13/tests/testthat/test-againstEunomia.R#L151).

**Comment by gowthamrao** [comment]
I like that idea @msuchard  !

**Comment by gowthamrao** [comment]
@msuchard  see https://github.com/OHDSI/CohortDiagnostics/pull/680/commits/60fc392086c386182ed1255fa65644f2c0689d7a

**Comment by gowthamrao** [comment]
Why is it failing tests

**Comment by gowthamrao** [comment]
Going to merge and create release candidate
