### ISSUE TITLE
Replace data_frame() with tibble()

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#67]
Warning: lifecycle_warning_deprecated: `data_frame()` is deprecated as of tibble 1.1.0.
Please use `tibble()` instead.

**Comment by schuemie** [comment]
We don't use `data_frame`, so it must be one of the tidyverse packages that is the offender. I've had messages like this before, which were automatically resolved when newer versions of tidyverse packages were released.

**Comment by gowthamrao** [comment]
Agree.
