### ISSUE TITLE
Data Sources Information - CDM Source?

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/CohortDiagnostics#671]
What is meant by the CDM Source on the Data Source Information tab in the Cohort Diagnostics viewer?  Looks like it is supposed to be additional information about the Vocabulary, but not sure what.  Right now it is reporting the Vocab version which is also reported in the Vocabulary table column

![image](https://user-images.githubusercontent.com/6305439/141306274-5caac571-4b2b-4921-8a6e-2421c6f37113.png)

**Comment by gowthamrao** [comment]
Its the vocabulary version as entered in cdm source table
It can be different from the vocabulary version in vocabulary table - hence the two fields

A difference **may** mean that the vocabulary version used during ETL may not match the vocabulary version in vocabularyDatabaseSchema - assuming the cdmSource is populating the vocabulary version used during ETL.
