### ISSUE TITLE
Cohort Overlap Table - Reorder Columns

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/CohortDiagnostics#673]
I though "both subjects" represented the count in both cohorts.  I think reordering the columns would mimic the stacked bar chart making the columns more intuitive.

![image](https://user-images.githubusercontent.com/6305439/141514556-c71b68bc-fb27-42d9-9e48-ddf292a38ed2.png)

**Comment by gowthamrao** [comment]
Ok - i see your point. easy change. we will make it

note: this issue is related to unreleased version of CD.
