### ISSUE TITLE
Cohort Overlap - Plot - Menu Titles

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/CohortDiagnostics#674]
Should "cohort" actually be "target"?

![image](https://user-images.githubusercontent.com/6305439/141515089-07b9c42a-4e85-482e-95a8-0f9121c65d97.png)

**Comment by gowthamrao** [comment]
"target' only has a meaning when there is a comparator. Compare char. is the only place we have comparator.

But the drop down, currently labelled 'cohorts' is used every where in app - so if we rename here, it will show as 'target' everywhere else (without a comparator - causing another confusion)

so i made the decision to keep it as cohort.
