### ISSUE TITLE
Cohort Counts - Records --> Entries

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/CohortDiagnostics#675]
To be consistent with the section text, please rename the Records column to Entries.  

Also, should the Subjects column come first?

![image](https://user-images.githubusercontent.com/6305439/141521474-547271d9-bf9c-41a9-9f1c-09cc72c7b287.png)

**Comment by gowthamrao** [comment]
Why not rename in section text? Its much easier

**Comment by gowthamrao** [comment]
We seem to have used records/entries interchangeably all over - so there would be a lot of changes.. 

does this really matter?
