### ISSUE TITLE
Gender --> Sex

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/CohortDiagnostics#676]
Please update references to Gender to be Sex

https://forums.ohdsi.org/t/sogi-sexual-orientation-gender-identity/13079

https://forums.ohdsi.org/t/sexual-orientation-and-gender-identity/13080

https://forums.ohdsi.org/t/gender-sex-naaccr/6837

![image](https://user-images.githubusercontent.com/6305439/141523411-f5834346-30bd-400f-9f4d-39158dedf69d.png)

**Comment by gowthamrao** [comment]
We can make this change!
