### ISSUE TITLE
revise characterization features and time windows

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/CohortDiagnostics#68]
Characterization should use:

condition (not condition group)
drug exposure (not drug group)
procedure
measurement

time windows to compute should be:
-365 -> -31
-30 -> -1
0 -> 0
1 -> 30
31 -> 365

(this will allow characterization to be used explicitly to determine if the index date seems appropriate for a given cohort, or whether observations occuring before or after seem out-of-sequence with expectations.   verbatim concepts more useful than group'ed concepts for detecting anamolies)

**Comment by gowthamrao** [comment]
Same as?

https://github.com/OHDSI/CohortDiagnostics/issues/61

**Comment by pbr6cornell** [comment]
related yes.  but difference is now i'm assigning it to you to get it done :)

**Comment by schuemie** [comment]
And I still oppose this functionality, for these reasons:

- Complexity. Yes, Patrick might now how to interpret this, but no one else will. Right now the characterization is consistent with the default used throughout HADES, so people might have a chance to get used to our crazy way of characterizing.

- Looking forward from the index date is always dangerous. Many bad causal inferences will be made.

**Comment by schuemie** [comment]
Just to be clear: the question of whether the index date is correct is an important one. I just don't think the characterization diagnostic should be warped to answer that question. Another diagnostic should be developed, although I don't yet have a good idea what that would look like.

**Comment by schuemie** [comment]
@pbr6cornell : would you mind providing some concrete examples of cohort issues that you would like CD to help identifying? I find it hard to think about this in the abstract.

**Comment by gowthamrao** [comment]
@schuemie to understand if rate of certain feature (or feature cohort) go up or down in relation to a target cohort_ANY_date, I think OHDSI/Kala is the way to go. 

There is no need to break into arbitrary discrete periods

> time windows to compute should be:
-365 -> -31
-30 -> -1
0 -> 0
1 -> 30
31 -> 365

I can imagine x axis being time/date, and y axis being a measure of feature occurrence. And then we can empirically compare patterns of features in relation to cohort. We could even test it, like negative and positive control - and pick test that pattern.

**Comment by gowthamrao** [comment]
@schuemie  @pbr6cornell  

Why cant this be solved with covariateSettings object of FeatureExtraction? Cohort Diagnostics does support passing covariateSettings in the call.

see PR [here](https://github.com/OHDSI/CohortDiagnostics/commit/155b5bbaac3c90f00a52ae4f0924f877bf3af92f) added [covariateSettings = FeatureExtraction::createDefaultCovariateSettings()](https://github.com/OHDSI/CohortDiagnostics/blob/15e7f6a76ff755ff10d0cf4c26d833415abf8efd/R/RunDiagnostics.R#L85).

**Comment by schuemie** [comment]
I really would like to see those concrete examples first, before we start engineering a solution that may not address the actual user's needs.

**Comment by pbr6cornell** [comment]
Concrete examples:

We want to determine if we've identifiied an incident case of a disease (and have properly specified the index date), so we need to investigate whether there are other observations (e.g. conditions, drugs, procedures) that occur prior to (not including the index date) which suggest that the condition already was present in the person.   A common example that can come up:  observing treatment for a condition PRIOR to seeing the diagnosis.  A diagnostic that characterizes conditions/drugs/procedures/measurements in the period of time  -30d to -1d before the index date will allow us to see if there are proximal to the index that may be potentially considered as new 'index events' to consider.   Characterizing conditions/drugs/procedures/measurements in the period of time -365d to -31d before the index date will allow us to see if there are other observations that may potentially considered as either 'index events' that we missed, but also observations that may serve as exclusion criteria we may want to consider.  An example we've seen come up a few times over the last couple months:  identifying a 'History of' code, which suggests the person has prevalent - not incident - disease.    Characterizing conditions/drugs/procedures/measurements on the index date (0d to 0d) will allow us to know what other data appear on the cohort entry date, which can be used to identify other commonly occurring elements which may not have been used in the cohort definition but should have (ex.  identifying other condition codes that may appear alongside the index diagnosis that orphan codes don't pick up, but may be relevant:  this has commonly occurred when a broad concept is seen (e.g. a specific infection is what we want, but the narrow code only sometimes shows up and always co-occurs with some broader 'infection' concept).  The other recent example:  observing where a diagnosis of 'fever' co-occurs with a measurement of 'body temperature'.   Looking at data on index can also help with identifying potential inclusion criteria, such as if one were debating a phenotype algorithm of 'diagnosis only' vs. 'diagnosis with diagnostic test', but theres uncertainty about how often the test is observed on the same date (or in the time periods prior to or after the diagnosis index).    Characterizing conditions/drugs/procedures/measurements in the 1d to 30d after the index date allows use to ascertain if the patients meeting our phenotype definition have an expected short-term subsequent health experience, such as receiving some treatments for the diagnosed disease.  We can also see whether follow-up care is observed, inclusive of observing the same diagnosis re-appearing (e.g. for those who are considering phenotype algorithms that use 1x codes vs. 2+ codes to qualify).   Characterizing conditions/drugs/procedures/measurements in the 31d to 365d after the index date allow us to confirm if we see the expected longer-term follow-up care, such as codes for disease progression or multiple treatments administered.  A recent example where this was necessary: a phenotype of new users of a drug, where we expected that most people should be chronic users of the drug and should have continuous exposure for multiple months, but we found that a small proportion of initiators had follow-up prescriptions and needed to see if it was because the patients were 'switchers', or the disease resolved, or the patients were lost to follow-up (the last item here is captured nicely in the 'time' diagnostic, but the first two aren't).

As it current stands, I am finding that the current characterizations in CohortDiagnostics, which only show me time windows prior to or on the index date do not meet my actual user needs.

I am specifically advocating for use of verbatim concepts (NOT concept groups) because this will help with identify source-specific issues with how data are captured, which can then be explored across each source that is participatnig in the network phenotype evaluation.   I want us also to clearly separate the notion of 'characterization' (being summary statistics that should used in reporting) vs. 'diagnostics' (which is about using the data to figure out if the cohort is correct).  We should very clear that diagnostics is NOT for reporting results about a given population, and that use of post-index data is not appropriate for any use other than phenotype evaluation.    When we have final phenotypes, then we'd want to pass these phenotypes to a characterization analysis (e.g. like we'd doing in our COVID research with the CHARYBDIS package).

**Comment by schuemie** [comment]
Thanks Patrick. That is very helpful!

Some thoughts:

1. I agree the pre-defined time windows make sense, especially since aggregating within these (relatively large) windows will allow us to capture many counts greater than the minimum allowed cell count.

2. One way to visualize this would be to have counts for the same covariate (concept) in one row, with different columns for the different time windows.

3. One easy way to extract this data could be using [temporal covariates in FeatureExtraction](http://ohdsi.github.io/FeatureExtraction/reference/createTemporalCovariateSettings.html).

4. I agree verbatim concepts are most of interest.

5. In fact, our standard 'table 1' filtering of covariates is precisely what we do not want here. The goal is not a global understanding of who is in the cohort, but rather to find specific concepts with 'temporal behavior of interest'.

This last point leads me to one thing I don't know how to solve: Out of all the concepts, how do we focus on the ones of most interest? We can rank-order by overall count, but then the same concepts (e.g. hypertension) will always be on top.

**Comment by gowthamrao** [comment]
After discussing with @pbr6cornell  and @schuemie  i propose the following:

- we build a characterization like output that supports various time windows. 
- the output will have one row per verbatim concept id, cross tab with one column per time window. 
- we will enforce minimum cell count rule
- we will run this new diagnostics for a selected set of cohorts (based on concrete examples from @pbr6cornell  above).
- we will review and interpret the output - and determine the usefulness of this feature.

**Comment by gowthamrao** [comment]
temporal Covariates in Feature Extraction is now working with https://github.com/OHDSI/FeatureExtraction/commit/18dd0d03214657b2752ce2f2596a2c88891a4a16 and https://github.com/OHDSI/FeatureExtraction/commit/0270bd981f11bed533f6b79a08522f6a195555bf

The design to incorporate this new functionality into results is
- Check if https://github.com/OHDSI/CohortDiagnostics/blob/ddc3f23472b53c2baec7c4469bc20ea3dcc24f6c/R/CohortCharacterizationDiagnostics.R#L48 is temporal using [isTemporalCovariateData](https://github.com/OHDSI/FeatureExtraction/blob/bfa7d6fe33a362d1c28598af4fac11249141f628/R/CovariateData.R#L184)

- If temporal covariate, then expect `timeRef (timeId, startDay, endDay) `  and [merge to returned object as here](https://github.com/OHDSI/CohortDiagnostics/blob/ddc3f23472b53c2baec7c4469bc20ea3dcc24f6c/R/CohortCharacterizationDiagnostics.R#L96)

- pending: how to present temporal data in cohort characterization (?)
