### ISSUE TITLE
Order the graphics from compare temporal characterization in time order

### ISSUE THREAD

**Issue by swerdel** [OHDSI/CohortDiagnostics#684]
The current order of the graphs has the -30 to -1D graph to the left of the -365 to -31D graph.  Can these be switched?
![image](https://user-images.githubusercontent.com/63558828/142262605-88e5eb41-3ac9-4a44-ad9a-00b04766d854.png)

**Comment by gowthamrao** [comment]
similar to closed issue

https://github.com/OHDSI/CohortDiagnostics/issues/444

**Comment by gowthamrao** [comment]
Closing issue -as this cant be solved using ggplot2, and is solved in future version
