### ISSUE TITLE
Things to know about Index Event Breakdown calculator in Cohort Diagnostics

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#699]
> A table showing the concepts belonging to the concept sets in the entry event definition that are observed on the index date. In other words, the table lists the concepts that likely triggered the cohort entry. The counts indicate number of cohort entries where the concepts was observed on the index date. Note that multiple concepts can be present on the index date, so the sum of counts might be greater than the cohort entry count.

The calculator first identified concept-sets in the cohort definition that are part of the entry event criteria portion of the cohort definition as  shown here https://github.com/OHDSI/CohortDiagnostics/blob/85d483265885ed678901908858870c1238d397c4/R/ConceptSets.R#L612-L614

The concepts are filtered to certain domains [here](https://github.com/OHDSI/CohortDiagnostics/blob/85d483265885ed678901908858870c1238d397c4/R/ConceptSets.R#L600) to the domains in this [file](https://github.com/OHDSI/CohortDiagnostics/blob/master/inst/csv/domains.csv). This is important, because for example if a cohort is build to index on date of death, and death has its own domainId - this would impact the index event breakdown output and this warning would be [given](https://github.com/OHDSI/CohortDiagnostics/blob/85d483265885ed678901908858870c1238d397c4/R/ConceptSets.R#L624) .

**Comment by gowthamrao** [comment]
**Thoughts for version 3:**

Note the sql [here](https://github.com/OHDSI/CohortDiagnostics/blob/85d483265885ed678901908858870c1238d397c4/inst/sql/sql_server/CohortEntryBreakdown.sql#L21) . I have observed that if the ETL allows for multiple rows for the same combination of subject_id, domain_concept_id, domain_start_date (e.g. if there are different domain_source_concept_id) -- this leads to negative impact of query performance (cartesian product join?). This is also an expensive SQL, because of the UNION. In future version, this sql will be rewritten.  I am experimenting with query logic like [this](https://github.com/OHDSI/CohortDiagnostics/blob/version3/R/ConceptSetDiagnostics.R#L1354) that not only have better performance, but also allow for deeper diagnostic information.

**Comment by azimov** [comment]
Closing due to age and lack of specificity
