### ISSUE TITLE
Remove cohort construction code

### ISSUE THREAD

**Issue by schuemie** [OHDSI/CohortDiagnostics#707]
If we add a dependency on the new [CohortGenerator](https://ohdsi.github.io/CohortGenerator/) package, we can remove all code for generating cohorts from this package.

**Comment by azimov** [comment]
I started a branch for this but there are some issues to resolve. Once these changes are made this can be added to release 2.2, which already references CohortGenerator in the vignettes.

For now, I was going to keep `instantiateCohorts` and `createCohortTable` but include a deprecation warning. This will give any existing users time to change code in their study packages.

**Comment by gowthamrao** [comment]
@azimov i know issuing deprecation warning is best practice - but if its cleaner and easier, i am thinking it would be better to remove the code from Cohort Diagnostics.

Studies have been using renv for sometime now - so i feel like this wont disrupt much.

**Comment by azimov** [comment]
This can be removed before the 2.2 release - the new branch #720 removes the code but it will break any existing packages. If we do this now it might be desirable to only allow the new `executeDiagnostics` function to be used and remove `runCohortDiagnostics` as this is designed to only work with a CohortDefinitionSet in the form expected by CohortGenerator
