### ISSUE TITLE
object 'result' not found using latest install

### ISSUE THREAD

**Issue by jswerdel** [OHDSI/CohortDiagnostics#71]
I received the "object 'result' not found" as well using the latest version of CohortDiagnostics.   I saw that corrections were made in the previous issue but I get 
"Skipping install of 'CohortDiagnostics' from a github remote, the SHA1 (15e7f6a7) has not changed since last install.
  Use `force = TRUE` to force installation"
when i try to download now.

**Comment by gowthamrao** [comment]
Thanks @jswerdel @jhardin29

testing to reproduce this error right now

**Comment by gowthamrao** [comment]
Could you please recheck with updated package from develop branch.

Do you still get the error message?

**Comment by jhardin29** [comment]
Thanks @jswerdel for testing the development branch; seems fixed now!
