### ISSUE TITLE
Diagnostics Explorer in database mode - how to guide

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#712]
We need a vignette to describe how to support database mode, especially when premerge files become large - else you will get a shouting from Martijn https://github.com/OHDSI/ShinyDeploy/issues/148#issuecomment-996619402

Vignette should say
1. What databases are supported. We currently only support postgres. But we are discussing https://github.com/OHDSI/CohortDiagnostics/issues/317 and https://github.com/OHDSI/CohortDiagnostics/issues/539. So i think we should probably decide on these issues prior to vignette, or at least acknowledge them
2. Make it easier to create schema and run DDL for the results data model -- as here https://github.com/OHDSI/CohortDiagnostics/blob/85d483265885ed678901908858870c1238d397c4/extras/UploadToDatabase.R#L19
3. Demonstrate how to upload as here https://github.com/OHDSI/CohortDiagnostics/blob/85d483265885ed678901908858870c1238d397c4/extras/UploadToDatabase.R#L32-L38
4. Run app as shown here https://github.com/OHDSI/CohortDiagnostics/blob/85d483265885ed678901908858870c1238d397c4/extras/UploadToDatabase.R#L44-L45

**Comment by azimov** [comment]
Uploading results has now been simplified and the vignette should be clearer
