### ISSUE TITLE
included_source_concept - NA vs 0

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/CohortDiagnostics#715]
| database_id | cohort_id | concept_set_id | concept_id | source_concept_id | concept_subjects | concept_count |
|-------------|-----------|----------------|------------|-------------------|------------------|---------------|
| PBR       | 547       | 2              | 3007461    | NA                | 5678         | 6789      |
| PBR       | 547       | 2              | 3007461    | 0                 | 1234           | 2345        |

I have a case where an NA was loaded into the included_source_concept.csv for SOURCE_CONCEPT_ID.  Technically this is allowed per the CDM.  I think when POSTGRES loaded the NA was converted to 0.  Then when the second row comes along that actually has the 0 for SOURCE_CONCEPT_ID, it violates the unique constraint.

~~~
java.sql.BatchUpdateException: Batch entry 1,059 
INSERT INTO covid_aesi.included_source_concept (database_id,cohort_id,concept_set_id,concept_id,source_concept_id,concept_subjects,concept_count) 
VALUES('PBR',547.0,2,3007461,0.0,1234,2345) was aborted: ERROR: duplicate key value violates unique constraint "included_source_concept_pkey"
Detail: Key (database_id, cohort_id, concept_set_id, concept_id, source_concept_id)=(PBR, 547, 2, 3007461, 0) already exists.  Call getNextException to see other errors in the batch.
~~~

**Comment by azimov** [comment]
This bug will break the postgres backend in many cases. I think we should be storing this as null.

I think this can be resolved by cleaning up the values returned by the  exported values [here](https://github.com/OHDSI/CohortDiagnostics/blob/develop/R/ConceptSets.R#L534).

**Comment by ericaVoss** [comment]
I just making a note that I found this behavior for the second time with another DP run.

**Comment by gowthamrao** [comment]
@azimov  i think this is the same issue we discovered while working on new function makeDataExportable for https://github.com/OHDSI/CohortDiagnostics/pull/748/ 

The output cannot violate primary keys - this one did. so i think it is before uploading - it is in the cohort diagnostics output

**Comment by azimov** [comment]
Resolved with improved export functions
