### ISSUE TITLE
CohortDiagnostics::uploadResults() - Problems with Extra Columns and Dates

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/CohortDiagnostics#716]
[concept.csv](https://github.com/OHDSI/CohortDiagnostics/files/7877999/concept.csv)

### Problem 1
My concept table has some extra columns.  These columns are used in DB maintenance.  When I try to load the data with `CohortDiagnostics::uploadResults()` it doesn't know how to check those columns and gets mad.

~~~
Error in if (expectedType == "bigint" || expectedType == "float") { : 
  missing value where TRUE/FALSE needed
~~~

So I delete the extra columns.

### Problem 2

Then after I delete the extra columns, it keeps getting mad at VALID_END_DATE. 

~~~
Uploading table concept
- Preparing to upload rows 1 through 1720
Error: Problem with `mutate()` column `valid_end_date`.
i `valid_end_date = (function (x, ...) ...`.
x character string is not in a standard unambiguous format
~~~

The error happens in `CohortDiagnostics:::checkAndFixDataTypes(...)`. 

The dates in the file all look valid to me.
![image](https://user-images.githubusercontent.com/6305439/149678858-5ccc9f9a-2f69-4845-8051-20b0547e26b9.png)

 I was only able to move past this once I reformatted both VALID_START_DATE and VALID_END_DATE manually.
`=TEXT(H2,"YYYY-MM-DD")` --> paste values

**Comment by ericaVoss** [comment]
I had to make similar changes to:

- relationship
- domain
- concept_relationship
- Concept_ancestor
- concept_synonym (ha a column call CONCEPT_SYNONYM_CHECKSUM that I needed to drop)
- vocabulary

**Comment by gowthamrao** [comment]
Should be handled by this pull request https://github.com/OHDSI/CohortDiagnostics/pull/748

what do you think @azimov

**Comment by azimov** [comment]
> Should be handled by this pull request #748
> 
> what do you think @azimov

I think you're right but I don't have concrete data examples to test it

**Comment by gowthamrao** [comment]
Closing this because we will assume it is handled.
