### ISSUE TITLE
CohortDiagnostics::uploadResults() - CONCEPT_ID as INT

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/CohortDiagnostics#717]
~~~
Uploading table concept
- Preparing to upload rows 1 through 2533
Warning: warning: Problem with `mutate()` column `concept_id`.
i `concept_id = .Primitive("as.integer")(concept_id)`.
i NAs introduced by coercion to integer range
~~~
For DPs that have self generated CONCEPT_IDs in the 3B range it will throw warnings.  Not sure if it still loads data but will continue to run.

Example:
`3000008158`
`3000008132`
`3000008159`

This happens where other CONCEPT_IDs can be:
- CONCEPT_RELATIONSHIP 
- INCLUDED_SOURCE_CONCEPT
- INDEX_EVENT_BREAKDOWN
- ORPHAN_CONCEPT
- VOCABULARY

Note: CUAMC

**Comment by azimov** [comment]
@ericaVoss i assume you mean something like this will fail

```
as.integer(3000008158)
```

These will need 64 bit int or double storage. This will definitely be a bug in the shiny app because values will be pulled out of the db as null.

**Comment by ericaVoss** [comment]
> @ericaVoss i assume you mean something like this will fail

Correct

**Comment by azimov** [comment]
Did you mean to close this issue? I think it will still possibly be a problem in the future.
