### ISSUE TITLE
Zero Counts

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/CohortDiagnostics#718]
One quick suggestion for improvement: if a database has no results it’s not in the table at all, then its not so obvious which database do NOT have these cohorts and you have to find out which database is missing. Missing database in a cohort is pretty important to known. Maybe nice to add all database to the tables, and fill with zeros, or even make these records red or something like that. For example: our IPCI database is not listed for the Narcolepsy cohort. My guess is that there is no code for this in IPCI, but I will look into this. 

Credit to @marcel1334

**Comment by azimov** [comment]
I agree, the cohort counts should be 0. This is probably because of how the counts are computed in SQL.
The shouldn't be too hard to implement. I'll try and get it into an upcoming release.

**Comment by azimov** [comment]
I created a branch/PR for this. However, I'm not sure how this will display in the shiny app so will need further evaluation. It should be exported as part of the characterization though.

Thinking about i expect it will list as less that the minimum shared value. @gowthamrao I'm not sure this is the desired behaviour? We would like to know when a cohort is 0 but not share the number if it is between 1 and the `minCellCount`, 0 identifies no individuals.

**Comment by azimov** [comment]
Fix is currently in develop branch and will be in the next release (2.2.1)
