### ISSUE TITLE
Change vignette so cohortDatabaseSchema = cohortDatabaseSchema

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/CohortDiagnostics#722]
https://github.com/OHDSI/CohortDiagnostics/blob/692c97c54f555f1e2a3e2e851abfc042596cd5d1/vignettes/RunningCohortDiagnostics.Rmd#L124

vignette has cdmDatabaseSchema as parameter.  those of us who mindlessly execute instructions will get an error :)

**Comment by azimov** [comment]
This was missed because the example uses Eunomia, but yes this will create errors if you actually try to run it on a cdm!
