### ISSUE TITLE
Unclear what inclusionStatisticsFolder should be set to or if its needed

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/CohortDiagnostics#723]
https://github.com/OHDSI/CohortDiagnostics/blob/692c97c54f555f1e2a3e2e851abfc042596cd5d1/vignettes/RunningCohortDiagnostics.Rmd#L153

This parameter was not described in vignette.  I commented it out to execute, not sure if this was replaced with CohortGenerator step?

**Comment by azimov** [comment]
Good spot; yes the inclusionStatisticsFolder is no longer i longer a requirement input if using the CohortGenerator package. It's still supported for old scripts but this should be removed from the vignette.
