### ISSUE TITLE
[index event breakdown] source codes not shown in diagnostics viewer

### ISSUE THREAD

**Issue by jamieweaver** [OHDSI/CohortDiagnostics#727]
See https://data.ohdsi.org/Covid19SubjectsAesiIncidenceRate/

Source: MDM
Cohort: DVT (C12)

Standard codes shown in viewer
![image](https://user-images.githubusercontent.com/7608016/151215422-11970363-67b2-4466-a3bb-ae544d65fe7a.png)

Non-standard codes not shows in viewer
![image](https://user-images.githubusercontent.com/7608016/151215627-2fe94908-4f85-493d-a71c-f356d4fed3a7.png)

Expected to see ICD10-CM codes, which are the native MDM condition codes.

**Comment by pbr6cornell** [comment]
To be clear, this *could* be a source ETL issue, unclear.  The first screenshot shows that voacbulary in source_concept_id is SNOMED (not ICD10)

**Comment by jamieweaver** [comment]
ahh, probably be a source ETL issue, Concepts in Data Source tab shows SNOMED codes in source fields view
![image](https://user-images.githubusercontent.com/7608016/151218506-b8e9a34c-6229-46d4-a526-ed8fef5ee621.png)
perhaps not a diagnostics viewer bug

**Comment by azimov** [comment]
I'm seeing the same thing in the Orphan concepts tab (and also only for MDM data source). This doesn't look like a dashboard issue but it might be an issue with the executor. Were there any errors in the log?

**Comment by gowthamrao** [comment]
Not seeing any action - i am thinking this is not a tool issue?

Closing for now
