### ISSUE TITLE
Diagnostics Explorer shiny app - allow comments

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#729]
Cohort Diagnostics output is viewed in Diagnostics Explorer. During review, a reviewer gains insights. The unit of the insight is a combination of cohort id + diagnostic category. They are written in notes in a seperate document and emailed etc. This is difficult. We need ability to document and discuss the insights, next to the diagnostic output. This would make sharing insights more efficient. 

Desired future state

- Capture and save comments based on the drop down in shiny app
- When same drop down combination is selected, show comments.
- Show attributes of comments - who, when, what
- allow nested comments (parent/child comments)
- allow rating
- ability to export comments into a report (pdf, rtf, word)

All users may view comments. Only authenticated users may comment. User authentication service could be the same service used by  https://atlas-phenotype.ohdsi.org/#/home . 

Note: Diagnostic category are usually the menu item on the diagnostic explorer shiny app (e.g. cohort count, time distribution, incidence rate etc). We can argue that datasource is another component of unit of insight - but i am not including that for simplicity.

@schuemie @azimov thoughts?

**Comment by gowthamrao** [comment]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-9da09ccd-7fff-ec64-ffd3-ec714d1b42aa"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Table Structure :</span></p><br /><div dir="ltr" style="margin-left:0pt;" align="left">

Comment_ID | Comment | Comment Attributes(JSON) | Created On | Last Modified On
-- | -- | -- | -- | --
PK | Text String/mark down | Key:Value Pairs | DATETIME | DATETIME OR NULL
  |   |   |   |  

</div></b>
</body>
</html>

**Comment by azimov** [comment]
Adding this in the shiny app with an sqlite db seems doable but the user authentication part will be difficult to implement across all users. I know @chrisknoll  is working on cohort annotation in atlas, we could, perhaps, user ROhdsiWebApi to persist the annotation there?

**Comment by gowthamrao** [comment]
authentication management thru webapi. users are registered to webapi and they get db credentials. e.g. atlas-phenotype.ohdsi.org

the credentials are verified using ROhdsiWebApi - detailed here https://ohdsi.github.io/ROhdsiWebApi/articles/authenticationSecurity.html


![pic 1](https://user-images.githubusercontent.com/13936600/152024618-b38b6c3b-c03d-4fb9-bfa0-b9a1e3531108.JPEG)
![pic 2 JPEG](https://user-images.githubusercontent.com/13936600/152024635-62389571-6871-4c30-b502-55b3074f4031.png)

**Comment by gowthamrao** [comment]
If bearer token --> check if database account has write privileges to the comment table --> if yes, enable write comment

**Comment by schuemie** [comment]
I highly recommend not having a generic 'attributes' field with key-value pairs encoded in a string. That will be unsearchable (and un-indexable) for database platforms. You can just add fields to the table as needed.

**Comment by gowthamrao** [comment]
Added new Annotation tables here https://github.com/OHDSI/CohortDiagnostics/blob/develop/inst/settings/resultsDataModelSpecification.csv#L9-L22

Supports local security

**Comment by azimov** [comment]
Comments are allowed - redesigning the infrastructure to make it easier may be desirable but is not currently a priority
