### ISSUE TITLE
Remove dead function

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#750]
selectColumnAccordingToResultsModel

checkCohortReference

@azimov  any other dead functions?

**Comment by azimov** [comment]
`makeBackwardsCompatible` is unused according to my IDE. 

`CohortConstruction.R` now only has code for dealing with inclusion rule so i propose a rename to `InclusionRules.R`

**Comment by gowthamrao** [comment]
i think rename is fine
