### ISSUE TITLE
Update vignette RunningCohortDiagnostics

### ISSUE THREAD

**Issue by nadavrap** [OHDSI/CohortDiagnostics#753]
In the vignette file [CohortDiagnostics/vignettes/RunningCohortDiagnostics.Rmd](https://github.com/OHDSI/CohortDiagnostics/blob/master/vignettes/RunningCohortDiagnostics.Rmd)
In line 147, the function `executeDiagnostics` should be replaced with `runCohortDiagnostics`. In addition, the default is to use package, but for webApi, need to add the next two arguments:

```
cohortSetReference=cohortDefinitionSet,
baseUrl=baseUrl
```

**Comment by azimov** [comment]
The use of `executeDiagnostics` is now the main interface to the package, `runCohortDiagnostics` will be removed in version `3.0.0`.

To continue to be up to date with new versions of the package please follow the the guidelines in the Vignette you looked at.  Notably, the usage of the [`CohortGenerator` ](https://ohdsi.github.io/CohortGenerator/)package (which will be required to generate cohorts in version 3.0.0). For interoperability with web api/atlas please use the [`RohdsiWebApi`](https://ohdsi.github.io/ROhdsiWebApi/) package - notably the function [`exportCohortDefinitionSet`](https://ohdsi.github.io/ROhdsiWebApi/reference/exportCohortDefinitionSet.html) as described in the vignette.

**Comment by nadavrap** [comment]
I see, I used an older version. Thank you for the detailed reply.
