### ISSUE TITLE
Typo - Application was last initated

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/CohortDiagnostics#755]
https://data.ohdsi.org/Covid19SubjectsAesiIncidenceRate/

At the bottom of the page there is this text:
"Powered by OHDSI Cohort Diagnostics application - Version 2.1.1 This app is working in database mode. Application was last initated on 2022-02-09 15:43:42 EST. Cohort Diagnostics website is at https://ohdsi.github.io/CohortDiagnostics/"

initated  --> initiated

**Comment by gowthamrao** [comment]
Good eye! will fix it
