### ISSUE TITLE
SharedShiny - Cohort Characterization - Display

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/CohortDiagnostics#756]
I can get this to work locally but not on data.ohdsi.org.  It was working until recently.

![image](https://user-images.githubusercontent.com/6305439/153294671-8bcb0239-0198-48dc-98d8-27ba43e857be.png)

@gowthamrao @azimov @anthonysena

**Comment by azimov** [comment]
This looks like either the dplyr version on data.ohdsi.org is old or the one of your local is.

**Comment by gowthamrao** [comment]
@leeevans  do you think you could update the packages on Shiny server please
i cant reproduce these locally

**Comment by ericaVoss** [comment]
dplyr V1.0.7

**Comment by gowthamrao** [comment]
Fixed - closing

**Comment by ericaVoss** [comment]
![image](https://user-images.githubusercontent.com/6305439/153320074-478e9b59-6dcf-4b0d-9f1a-dc11f58cc936.png)
