### ISSUE TITLE
launchDiagnosticsExplorer() fails in local project

### ISSUE THREAD

**Issue by solis9753** [OHDSI/CohortDiagnostics#761]
Hi and congratulations for the new user interface of `CohortDiagnostics`, looks fantastic. 

**The problem**
I was running the example on the vignettes using Eunomia in a newly created local directory.

Everything ran smoothly except when I attempted the `launchDiagnosticsExplorer()`.

`Error in ..stacktraceon..({ : Local data file export/PreMerged.RData does not exist.`

SessionInfo:
R version 4.0.4 (2021-02-15)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] magrittr_2.0.2          shiny_1.6.0             CohortDiagnostics_2.2.3 FeatureExtraction_3.2.0
 [5] Andromeda_0.6.0         dplyr_1.0.8             Eunomia_1.0.1           DatabaseConnector_5.0.2
 [9] devtools_2.4.1          usethis_2.0.1          

**Temporary solution**
Following the [Viewing results using Diagnostics Explorer](https://github.com/OHDSI/CohortDiagnostics/blob/master/inst/doc/ViewingResultsUsingDiagnosticsExplorer.pdf) vignette, I copied the results in the location of the DiagnosticsExplorer then I could indeed run the app. 

**Question/s**
 Perhaps you would like to read the **Some Comments** section below to understand where I am coming from but a general question is,
Is this the intended behaviour? Should I only be able to run the explorer by only copying my results to the directory of the package? Why not simply run the `launchDiagnosticsExplorer()` function giving a folder with the necessary files from any directory?

**Some Comments**
Reading the [Viewing results using Diagnostics Explorer](https://github.com/OHDSI/CohortDiagnostics/blob/master/inst/doc/ViewingResultsUsingDiagnosticsExplorer.pdf) vignette, it mentions: (section 1) _[...] The Shiny app can be found here. Make sure to copy all files in the DiagnosticsExplorer folder. When
launching the application. You maybe asked to install additional packages required by the app, such as [...]_ 

I find this explanation rather difficult to understand and in my opinion does not generalise well. Where is here? And if I run CohortDiagnostics in a separate environment (like a local R project) I would not have a DiagnosticsExplorer folder.

Then in section 2 of the same vignette it states: "_From R-studio, you may start the project by clicking on the ‘DiagnosticsExplorer.Rproj’ in the shiny
folder [...]_" Again, this failed in my example simply because I was running in a local project outside the package's directory.

**Feature request**
Launch the explorer from any directory. I found that just by replacing the `utils::packageName()` [in this line](https://github.com/OHDSI/CohortDiagnostics/blob/692c97c54f555f1e2a3e2e851abfc042596cd5d1/R/Shiny.R#L96) with a hard code for the package name (i.e package = 'CohortDiagnostics') provides the requested feature.

**Comment by solis9753** [comment]
I would like to correct make a few amendments to the previous post. 

1) I am getting the above error when I am specifying a relative path; when I change the path to absolute the error is resolved. 
2) Do not consider whatever I said regarding the feature request.

**Comment by azimov** [comment]
This is now fixed in version 3.0 which implements better handling of paths to the required data files
