### ISSUE TITLE
Select pretty or raw temporal characterization table

### ISSUE THREAD

**Issue by OskarGauffin** [OHDSI/CohortDiagnostics#763]
Hello! 

Perhaps a silly question, but I'm running CohortDiagnostics and read in the documentation that there is supposed to be a raw / pretty version of the temporal characterization, that you should be able to switch between at the top of the table. But I don't seem to find the button. Is this feature no longer supported, or does it perhaps need to be turned on somewhere in the setup? 

This is how the table currently looks, running synpuf on some standard cohorts:

![image](https://user-images.githubusercontent.com/7349924/154684124-808f44e3-06c8-4317-8c3a-0772b038b0f6.png)

**Comment by gowthamrao** [comment]
Thank you for your question @OskarGauffin The documentation needs to be corrected - we currently dont have a pretty version of temporal characterization. 

There is no technical challenge to do the pretty table - we were conflicted about the usefulness of the pretty table in this context, so it was not implemented.

Do you this rendering the temporal characterization similar to the pretty version in (non temporal) characterization would be useful?

**Comment by OskarGauffin** [comment]
Thanks, that's helpful to know. I wish I had more input to give around the usefulness, I tried looking at the cohort characterization tab to understand what pretty means, but currently the pretty version of that tab looks like this for me:

![image](https://user-images.githubusercontent.com/7349924/154978865-b630ce74-699b-48ad-8564-ffe4297930b7.png)

But perhaps this is due to our setup / our cohort definitions, we haven't gotten around to examining it further yet. 

Anyhow - there are quite a few covariates in the raw version, 14 000 or so. Something more "rolled up" could probably be useful, for our use case and potentially for others as well, unless I'm missing something.

**Comment by gowthamrao** [comment]
It specified here https://github.com/OHDSI/CohortDiagnostics/blob/main/inst/shiny/DiagnosticsExplorer/Table1Specs.csv

and here is the function that creates it
https://github.com/OHDSI/CohortDiagnostics/blob/main/inst/shiny/DiagnosticsExplorer/R/Tables.R#L3
