### ISSUE TITLE
Add CONCEPT_CODE field from CONCEPT table to the Index Event Breakdown tab

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/CohortDiagnostics#777]
Currently, The Index Event Breakdown tab allows a user to see the frequency of CONCEPT_ID and SOURCE_CONCEPT_ID that occur on the cohort start date, which fall within the cohort's conceptset within its entry event.   As shown below, when a user selects 'Non-standard concepts' from the radio button, the user sees CONCEPT_ID, CONCEPT_NAME, VOCABULARY_ID  (but not CONCEPT_CODE)

![image](https://user-images.githubusercontent.com/731930/159713573-e012c58a-5bc1-4738-b093-1137e2c5f97f.png)

@jamieweaver made a local version hack that also exposes the CONCEPT_CODE field in the CONCEPT table when the radio button for 'Non-standard concepts' is selected.   This is helpful because it allows the user to see which code (not its corresponding CONCEPT_ID) is appearing in the data.   This feature should be added to the main package:

![image](https://user-images.githubusercontent.com/731930/159713494-c48b66fd-9650-44d6-8e99-0fabec0af52e.png)

**Comment by gowthamrao** [comment]
![image](https://user-images.githubusercontent.com/13936600/159782870-6451973d-bdc7-47a8-8ac0-671c8edf571f.png)
