### ISSUE TITLE
Vignette is not rendered on GitHub

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#79]

**Comment by schuemie** [comment]
GitHub cannot render RMarkdown. But the vignette is here: https://ohdsi.github.io/CohortDiagnostics/articles/CohortDiagnosticsUsingWebApi.html, so all is well?

The PDF version of the vignette *is* missing, so you should regenerate that using [this code](https://github.com/OHDSI/CohortDiagnostics/blob/master/extras/PackageMaintenance.R#L31).

**Comment by gowthamrao** [comment]
resolved in v1.1 release
