### ISSUE TITLE
Add vignette explaining how to create a package with cohort diagnostics

### ISSUE THREAD

**Issue by schuemie** [OHDSI/CohortDiagnostics#8]

**Comment by gowthamrao** [comment]
Related to https://github.com/OHDSI/CohortDiagnostics/issues/33

**Comment by gowthamrao** [comment]
Same as https://github.com/OHDSI/CohortDiagnostics/issues/95

**Comment by gowthamrao** [comment]
We will be using Hydra to generate package
https://github.com/OHDSI/Hydra/issues/18

https://github.com/OHDSI/SkeletonCohortDiagnostics
