### ISSUE TITLE
Diagnostics Explorer: Export tables as CSV

### ISSUE THREAD

**Issue by azimov** [OHDSI/CohortDiagnostics#807]
This was previosuly achived with reactable. However, the current version of Reactable in CRAN (0.2.3) does not currently support adding CSV downloads, however, this is exposed throught the javascript API in the latest github release (0.2.3.9000). We should keep install of non-ohdsi github packages to a minimum as its difficult to verify their source.

**Comment by gowthamrao** [comment]
@azimov  looks like there is a new release of reactable  in CRAN https://cran.r-project.org/web/packages/reactable/index.html

**Comment by azimov** [comment]
Merged in to develop branch
