### ISSUE TITLE
On 'Cohort Counts' tab, use multi-selector dropdown to allow for filtering of cohorts that are shown

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/CohortDiagnostics#81]
Inspired by work @anthonysena  did on CHARYBDIS, use of multi-selector dropdowns will be helpful for filtering content.

We can also replace the database checkboxes with the multi-selector dropdown to give a consistent experience.

**Comment by gowthamrao** [comment]
@anthonysena do you have a screen shot and reference to the code base that @pbr6cornell is referencing

**Comment by anthonysena** [comment]
Sure - here is the code reference to show how it uses the `shinyWidgets` library for the multi-selector: 

https://github.com/ohdsi-studies/Covid19CharacterizationCharybdis/blob/master/inst/shiny/CharybdisResultsExplorer/ui.R#L42-L46

And example of how it looks on the UI:

![image](https://user-images.githubusercontent.com/12902366/86020618-21e57280-b9f6-11ea-9463-58aa7e517fb8.png)
