### ISSUE TITLE
Add some way to 'link' and/or describe the cohort that is being diagnosed

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/CohortDiagnostics#82]
Currently, we only have a cohort name, but there is no way to map back from the cohort name to the correesponding cohort being executed.  If that cohort was generated in ATLAS, would be useful to link out, and/or have print friendly description.

**Comment by gowthamrao** [comment]
https://github.com/OHDSI/CohortDiagnostics/issues/90

**Comment by gowthamrao** [comment]
https://github.com/OHDSI/CohortDiagnostics/issues/80

**Comment by gowthamrao** [comment]
Implementation in Charydbis
![image](https://user-images.githubusercontent.com/13936600/88684652-15bb0680-d0c3-11ea-9cd6-dca4ddab1dc6.png)

Implemented in Charydbis through
https://github.com/ohdsi-studies/Covid19CharacterizationCharybdis/pull/60

Similarly in Cohort Diagnostics -

- add to 'Cohort Counts' submenu
- in data table, make each row in dt for column DT a hyperlink
- cohort count table uses cohort table in premerged file. This table also has atlasId field
- use default baseUrl = 'https://atlas.ohdsi.org/#/'
- for hyperlink use paste0(baseUrl, 'cohortdefinitions/', atlasId)

**Comment by gowthamrao** [comment]
Added interim solution. Using cohortId as presumed AtlasId. Base URL defaults to ohdsi Atlas, but maybe overwritten in shiny app

**Comment by gowthamrao** [comment]
https://github.com/OHDSI/CohortDiagnostics/issues/144

**Comment by gowthamrao** [comment]
Current implementation of link out
- use cohortId
- use default url to append the cohort id here https://github.com/OHDSI/CohortDiagnostics/blob/61e58c8abf5cc8ec91dc2b6b110a1ef8bf90e228/inst/shiny/DiagnosticsExplorer/ui.R#L191
- add ability for user to modify it in shiny app using shiny's reactive function here  https://github.com/OHDSI/CohortDiagnostics/blob/master/inst/shiny/DiagnosticsExplorer/server.R#L97-L98


Future version
- assumption: atlas cohort definitions are stable and dont change over time, i.e. link outs to atlas are stable and persistent
- we can allow end-user to provide atlasUrl as a parameter during the creation of premerged file. Then we can generate the link out to these cohort definitions using the atlasUrl in premerged data.

**Comment by gowthamrao** [comment]
A proposed version - that we may not implement
- we cohort json expression in cohort.csv
- post expression into any available webapi/atlas of user choice to instantiate (on fly) the atlas cohort definition page from the cohort json expression (done using ROhdsiWebApi). When user comes back to shiny app - delete the instantiated cohort
