### ISSUE TITLE
Shiny interface Does Not Automatically update with specification changes

### ISSUE THREAD

**Issue by raecheldavis** [OHDSI/CohortDiagnostics#828]
Hello, 
When changing a setting or updating a parameter in the shiny interface the output screen does not automatically update.
For example, if you are within Cohort Counts or another section and then you change the database specifications the interface will not update to reflect those changes, instead you must entirely click out of the section and then go back into it again to see the updated specification changes

**Comment by azimov** [comment]
This issue seems to be difficult to fix and relates to the way the UI works. Many elements are hidden and used in different tabs. 

The UI should be overhauled when the shiny app is migrated to `OhdsiShinyModules`
