### ISSUE TITLE
Add a 'cohort group' field to the Cohorts dataframe, and make it possible to sort/filter on this field in the result tables

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/CohortDiagnostics#83]
Sometimes we use cohort diagnostics across a large number of cohort definitions all at once (e.g. all exposures and outcomes in an estimation study,   or multiple algorithm variants for the same phenotype - chapters in a book for the PhenotypeLIbrary,   or all strata within the CHARYBDIS study) .   If CohortDiagnostics provides the ability for users to specific a 'cohort group' in addition to 'cohort name', then that would allow logical groupings for sorting/filtering of results.  Much as we have a dropdown to select a given cohort, we could have a dropdown to select a 'cohort group' when reviewing the list of cohorts within 'Cohort counts'.

**Comment by gowthamrao** [comment]
Implemented as phenotypeId and referentConceptId
