### ISSUE TITLE
Temporal Covariate Settings assertion errors

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/CohortDiagnostics#833]
## Expected Behavior

CohortDiagnostics asserts that `temporalCovariateSettings$temporalStartDays` and `temporalCovariateSettings$temporalEndDays` are integers. 

## Actual Behavior

CohortDiagnostics asserts that `temporalCovariateSettings$temporalStartDays` and `temporalCovariateSettings$temporalEndDays` are doubles: 

https://github.com/OHDSI/CohortDiagnostics/blob/cd52c9a7c193beb140b5068044f66b6f38e77228/R/RunDiagnostics.R#L343-L350

**Comment by azimov** [comment]
This has now been fixed in the develop branch
