### ISSUE TITLE
Database ids with spaces causes DiagnosticsExplorer to crash

### ISSUE THREAD

**Issue by azimov** [OHDSI/CohortDiagnostics#834]
# Problem

When using database id's such as:

"IQVIA Disease Analyzer Australia (vXxx)"

Shiny apps will throw the error:

```
Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  java.lang.RuntimeException: Error parsing boolean condition: "v1945"
```

This solution likely impacts many functions in the diagnostics explorer and it will take some time before a fix is ready.

# Workaround
Don't use non-ascii or brackets in database ids when executing cohort diagnostics.
For the above example, use simple ids such as:

`iqvia_disease_analyzer_australia_v1234`

**Comment by raecheldavis** [comment]
I think this is what I observed when I entered in my issue/bug report, closing that one now
