### ISSUE TITLE
Orphan Concepts error occurs periodically when "selecting all databases" for select cohorts

### ISSUE THREAD

**Issue by raecheldavis** [OHDSI/CohortDiagnostics#837]
Orphan Concepts bug observed version 3.0.1. This only occurs periodically when clicking on the tab for orphan concepts, then clicking "select all databases" option and moving through select cohorts, (not selecting a concept set) this error message is observed:

![image](https://user-images.githubusercontent.com/97139078/175981608-20c042b7-09fd-4d1e-b637-161b4e9ee41f.png)

**Comment by gowthamrao** [comment]
This seems to occur when the data output seems to have records where a concept id satisfies both 'standard' and 'non standard' only filters. That means, the conceptId occurs twice for the same group causing the pivot to fail.

**Comment by azimov** [comment]
Reactive issue that should now be resolved in OhdsiShinyModules package
