### ISSUE TITLE
invalid UTF-8 byte sequence detected

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#857]
invalid UTF-8 byte sequence detected; try calling stri_enc_toutf8()

Warning in .data$databaseId == databaseIdToFilter :
  longer object length is not a multiple of shorter object length
Warning: Error in stri_length: invalid UTF-8 byte sequence detected; try calling stri_enc_toutf8()
  101: stri_length
  100: stringr::str_length
   99: getDisplayTableColumnMinMaxWidth [D:\git\github\ohdsi\CohortDiagnostics\inst\shiny\DiagnosticsExplorer\R\DisplayFunctions.R#536]
   98: getDisplayTableSimple [D:\git\github\ohdsi\CohortDiagnostics\inst\shiny\DiagnosticsExplorer\R\DisplayFunctions.R#398]

**Comment by azimov** [comment]
Please describe steps to reproduce

**Comment by azimov** [comment]
No steps to reproduce error, will be closed until steps can be given
