### ISSUE TITLE
launchDiagnosticsExplorer crashes shinnyApp

### ISSUE THREAD

**Issue by andtsouch** [OHDSI/CohortDiagnostics#873]
Hi, I am executing CohortDiagnostics and I am running into an error that leads to the ShinnyApp opening but freezing and force closing automatically. I am attaching a screenshot of the command, the error and the session info below. 
![cohortDiagIssue](https://user-images.githubusercontent.com/59889084/182562533-4085b2c3-34bd-45e4-a7ad-545e03969742.jpg)
.

**Comment by azimov** [comment]
Hi @andtsouch it looks like the results file has not been generated correctly, can you please post the log of `createMergedResultsFile` and the parameters you specified?

**Comment by andtsouch** [comment]
Hi again, thank you for your response @azimov, I attach bellow the command and output of createMergedResultsFile.
![Issuev2](https://user-images.githubusercontent.com/59889084/182869785-58fcbe13-ec37-44ca-a9c4-099c72d8275a.jpg)

**Comment by azimov** [comment]
Hi @andtsouch it looks like the data has been processed fine. I'm wondering if there is a problem with your cohort definition json that doesn't cause a problem during execution but breaks the shiny app. Did you generate the expression using atlas? 

It may be helpful if you could copy and paste the definition json used in your `cohortDefinitionSet`

**Comment by andtsouch** [comment]
Hi, I have identified the issue, the cohort did not have any expression since it was a simple cohort for any death with no inclusion criteria or concept sets.
