### ISSUE TITLE
[BUG] Shiny app does not start when Characterization diagnostics is not in results

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#875]
To reproduce

1. Run Cohort Diagnostics with characterization switched off. The output will not have tables like temporal_analysis_ref
2. in the absence of temporal_analysis_ref  shiny app wont start

`
Warning: Error in hasData: object 'temporalAnalysisRef' not found`

**Comment by gowthamrao** [comment]
Bug in this line when temporalAnalysisRef does not exist (because characterization was not run)

https://github.com/OHDSI/CohortDiagnostics/blob/5567b89bd29ae84d9719e0805b1f3ee8b516dd9c/inst/shiny/DiagnosticsExplorer/server.R#L2259

**Comment by azimov** [comment]
Should now be resolved in develop (see #987)
