### ISSUE TITLE
Develop branch - looking for annotation when annotation is set to FALSE

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#879]
As descried here https://github.com/OHDSI/CohortDiagnostics/pull/876#issuecomment-1204421179

Testing this on my local - connected to remote postgres. with 

> diagExpEnv$enableAnnotation <- FALSE
> diagExpEnv$enableAuthorization <- FALSE
> diagExpEnv$activeUser <- NULL

### Observed
When i click on 'Concepts in data source' i get this

![image](https://user-images.githubusercontent.com/13936600/182699102-d7bf800d-2c22-4811-8bcb-6038878db289.png)

On R console i see this

```
SELECT *
                            FROM assure_phenotypes_o.annotation
                            WHERE annotation_id IN ();
Warning: Error in ._jobjRef_dollar: no field, method or inner class called 'parent' 
```

looks like app is trying to enable annotation even when its switched off

### Expected:

When `diagExpEnv$enableAuthorization <- FALSE` no annotation/comments should be shown.

**Comment by azimov** [comment]
Closing as setting `enableAuthorization` is now done via the configuration file. These options don't impact this.and will be removed in the develop branch very soon.
