### ISSUE TITLE
Extend the skeleton 'Comparative effectiveness studies data model' to become a OHDSI results data model

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#88]
Most OHDSI studies output a set of non-person level (non identifiable) data assets. These output serve as a set of standard input for presentation tools (most commonly R-shiny). This framework of outputting a computed output holds for OHDSI characterization, estimation and prediction studies. It also holds for cohort diagnostics. 

Currently only Skeleton comparative effect study has a published results output format see: [Comparative effectiveness studies data model](https://github.com/OHDSI/SkeletonComparativeEffectStudy/blob/master/vignettes/DataModel.Rmd) . The output format of cohort diagnostics is a derivative of Comparative effectiveness studies data model - but is not documented as such.

Through this issue - we need to think about unifiying the output (results) format for Skeleton comparative effectiveness studies and cohort diagnostics. Hopefully also Phevaluator (@jswerdel), Future characterization (@anthonysena ) . 

Based on discussion with @schuemie

**Comment by chandryou** [comment]
I truly agree with this.

**Comment by gowthamrao** [comment]
Assigning to @anthonysena to potentially design a shared results data model

We need to standardize the input from (and probably output of) phevaluator
Related to https://github.com/OHDSI/CohortDiagnostics/issues/132
https://github.com/OHDSI/CohortDiagnostics/issues/125

**Comment by gowthamrao** [comment]
@anthonysena  

FYI - i am beginning to think that the difference between 'Cohort Diagnostics' and 'Phenotype Library' is the presence of two data objects - 'phenotype description' and 'cohort description'. The presence of these data objects, switches cohort diagnostics into phenotype library https://github.com/OHDSI/CohortDiagnostics/issues/154

**Comment by gowthamrao** [comment]
@anthonysena i am assigning this issue to you https://github.com/OHDSI/CohortDiagnostics/issues/97 to help design the results data model.

**Comment by gowthamrao** [comment]
@anthonysena  regarding the output for 'temporalCharacterization'
https://github.com/OHDSI/CohortDiagnostics/issues/68#issuecomment-652956744
https://github.com/OHDSI/FeatureExtraction/commit/18dd0d03214657b2752ce2f2596a2c88891a4a16

> timeRef (timeId, startDay, endDay)

I think we should design the results data model for temporal-covariates to have the same tsibble format. This would make comparing features that are ordered in time easier and allow us to leverage tidyverts

**Comment by gowthamrao** [comment]
After discussion with @chrisknoll we wont be extending the Skeleton Comparative Effectiveness studies data model for Cohort Diagnostics. Cohort Diagnostics will have a separate results data model (that will include the output of PheValuator @jswerdel).
