### ISSUE TITLE
Main Branch - Cohort Overlap issues

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#885]
1) Switching cohort selection does not change the display. here i have done no cohort selection - but i see cohort overlap
![image](https://user-images.githubusercontent.com/13936600/182924961-a94f874c-d82a-4fb1-adfd-1a121d50d991.png)

2) here i changed the selection - did not trigger reactive changes
![image](https://user-images.githubusercontent.com/13936600/182925159-267a0ac4-341d-42dd-91e9-9c80b570ad27.png)

**Comment by azimov** [comment]
Fixed in development branch - will be included in next release
