### ISSUE TITLE
Develop branch - inclusion rule statistics does not show percentage

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#896]
Percentages are very useful. It was present in a previous version.

Wish list:
- we would like to modify the inclusion rule viewer to be similar to Atlas. All the output used by Atlas to generate the view in Atlas is now in results data model of Cohort Diagnostics (starting version 3)

This is further described 

Inclusion rule statistics - visualization https://github.com/OHDSI/CohortDiagnostics/issues/409
https://github.com/OHDSI/CohortDiagnostics/issues/616 https://github.com/OHDSI/CohortDiagnostics/issues/616

**Comment by gowthamrao** [comment]
A functionality that was present in a previous version of cohort diagnostics (not sure if it was released or was in an experimental branch) was a click thru experience to inclusion rule in cohort count menu of cohort definition page.

As an illustration - the iquvia_pharmetric_plus was clickable - and would reveal inclusion rules data

![image](https://user-images.githubusercontent.com/13936600/183461049-5886128d-14a2-4769-873e-3d35b3b3f844.png)

**Comment by azimov** [comment]
Closing: Inclusion rules is in the cohort counts tab and cohort generator functionality of OhdsiShinyModules
