### ISSUE TITLE
Add ability to save plots and figures

### ISSUE THREAD

**Issue by schuemie** [OHDSI/CohortDiagnostics#9]
Probably using [Shiny modules](https://ildiczeller.com/2018/02/11/downloadable-ggplots-in-shiny/).

Perhaps using [this](https://cran.r-project.org/web/packages/periscope/vignettes/downloadablePlot-module.html).

**Comment by schuemie** [comment]
Also DataTables to csv

**Comment by gowthamrao** [comment]
Implemented downloading png
