### ISSUE TITLE
Execution times output is not appending

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#918]
Observed: The execution time output is not appending in incremental mode. 

Expected: should append. appending corresponds to previous logging behavior

**Comment by gowthamrao** [comment]
From what i saw in todays execution - the execution time files seems to be overwriting previous files.

**Comment by azimov** [comment]
I can't confirm this bug, I found an unrelated issue (see #919 ) with the function recording times but the tests show that[ appending works](https://github.com/OHDSI/CohortDiagnostics/blob/04416dfc433d2365564279a18afd928a9e2af5de/tests/testthat/test-other.R#L97).
Can you provide reproducible steps.

**Comment by gowthamrao** [comment]
The code looks fine  here

https://github.com/OHDSI/CohortDiagnostics/blob/04416dfc433d2365564279a18afd928a9e2af5de/R/Private.R#L333

i will observe in the next execution

**Comment by gowthamrao** [comment]
There is definitely an issue here - my log is like this

![image](https://user-images.githubusercontent.com/13936600/190852794-35775749-b0dd-4937-b787-56b6bafdbc53.png)

**Comment by gowthamrao** [comment]
For some i see complete information

![image](https://user-images.githubusercontent.com/13936600/190852821-bdff116a-ae4e-4fc2-906d-59f3f9a7c19e.png)

**Comment by azimov** [comment]
@gowthamrao see PR #919 which resolves this issue
