### ISSUE TITLE
Warning in .findOrphanConcepts

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#920]
There is a warning in Orphan Concepts 

> 2022-09-19 11:11:25	[Thread 9]	TRACE	CohortDiagnostics	.findOrphanConcepts	- Fetching orphan concepts from server
> 2022-09-19 11:11:25	[Thread 9]	TRACE	CohortDiagnostics	.findOrphanConcepts	- Dropping orphan temp tables
> 2022-09-19 11:11:26	[Thread 9]	WARN	tibble	$.tbl_df	Unknown or uninitialised column: `name`.

**Comment by azimov** [comment]
No steps to reproduce

**Comment by gowthamrao** [comment]
Run this script in cohort diagnostics extra folder https://github.com/OHDSI/CohortDiagnostics/blob/main/extras/exampleCodeToRun/CodeToRun_Eunomia.R

> 
> 2022-09-26 21:27:31	[Main thread]	INFO	CohortDiagnostics	runConceptSetDiagnostics	- Finding orphan concepts for concept set 'Diabetes mellitus (exclude Type 2)'
> 2022-09-26 21:27:31	[Main thread]	INFO	DatabaseConnector	executeSql	Executing SQL took 0.0208 secs
> 2022-09-26 21:27:31	[Main thread]	TRACE	CohortDiagnostics	.findOrphanConcepts	- Fetching orphan concepts from server
> 2022-09-26 21:27:31	[Main thread]	TRACE	CohortDiagnostics	.findOrphanConcepts	- Dropping orphan temp tables
> 2022-09-26 21:27:32	[Main thread]	WARN	tibble	$.tbl_df	Unknown or uninitialised column: `name`.

**Comment by gowthamrao** [comment]
tomaybe its a non- issue, but i thought it should atleast be investigated.

if you get a chance, could you see if u can reproduce it using the script above?

**Comment by azimov** [comment]
Still can't reproduce. Would likely be caused when accessing a[ column that doesn't exist in a tibble](https://github.com/tidyverse/tibble/issues/450).

The only references to a use of `$name` i can find are in the [conceptSet diagnostics.](https://github.com/OHDSI/CohortDiagnostics/blob/e04b3bb6b3656b62fcb6e59bd067e94b83752200/R/ConceptSets.R#L87)

e.g. something like:
```
conceptSet$name
```

The only reason I think this would happen is if the data frame is empty which isn't a great concern. However, I can't reproduce this warning with the above example.
