### ISSUE TITLE
Cohort Definition:  Export Cohorts Zip button does not produce Zip

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/CohortDiagnostics#923]
Top right hand button, 'Export Cohorts Zip',  I expected upon click would download a zip file containing the definitions.

![image](https://user-images.githubusercontent.com/731930/191118359-bc72f94c-c153-4cf1-9d14-f9806bc9444b.png)

Instead, it downloaded a file called 'download.html, which looks like a stripped down version of the page itself:

![image](https://user-images.githubusercontent.com/731930/191118449-bf29670c-23f0-4d63-9bb7-3c771e89cd5c.png)

**Comment by azimov** [comment]
Fixed in #943
