### ISSUE TITLE
Cohort Definition tab:  cosmetic improvements

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/CohortDiagnostics#924]
1.  Cohort ID field is integer, but gets sorted as string.   Screenshot below shows ID 345 shorted after 3075, rather than before 1068.    Suggestion:   cast field as integer so sorts

![image](https://user-images.githubusercontent.com/731930/191111717-47e75994-1155-4139-aeb4-0d50c3b189c1.png)

Note, from user perspective, it is unclear the difference between the Cohort field and the CohortId field.  Cohort has a 'C' prefixing the Id, it's not clear if both fields are necessary or useful.  But, if Cohort is preserved instead of CohortId, then this is a string that will not be able to support numeric sort.

2.   Select cohort, drilldown: Cohort Count tab shows # of persons and # of events.   Both are integers, but get displayed as decimals.    Suggestion:  format as int.

![image](https://user-images.githubusercontent.com/731930/191112832-70098230-f9ec-42f1-824a-a338687e2b16.png)

Same formatting can be applied to Subjects and Count columns in the Concept Sets/Mapped table, below:

![image](https://user-images.githubusercontent.com/731930/191116334-107d61d2-799c-4752-875f-5ea86a255e26.png)

3.  Select cohort, drilldown: Concept Sets tab shows concept set expression with checkmarks for Exclude and Descendants, but then there is no way to filter in the textbox in the column header.    I don't have a suggestion for how to enable filtering, except to change checkbox to 'Y'.

![image](https://user-images.githubusercontent.com/731930/191113516-36c2573d-4be6-4314-93c3-47ea1a98576e.png)

Note, in the view above, we see the conceptset expression, plus a series of additional fields we don't show in other tools using conceptsets (Invalid, Concept Code, Vocabulary Id, Concept Class Id).      Suggestion:   allow user to show/hide columns of interest.

4.  In the Conceptsets, with Resolved or Mapped tab,  the table include columns titled 'Subjects' and 'Count'.   It's unclear to the user what they represent.     Suggestion:   align with the 'Cohort Counts' tab (assuming that the content is supposed to be the same', which names the columns 'Persons' and 'Records'.

![image](https://user-images.githubusercontent.com/731930/191117056-21bbd086-f5d2-4234-b8a2-671ca8fb258b.png)

**Comment by gowthamrao** [comment]
Cohort field with 'C' prefix has been around for many version. It was essential in version 2 because 'DT' did not have flexibility offered by 'reactable', and putting cohort names in the same row without the lookup - took too much real estate. We also did not have ability to dynamically expand the column width - so couldnt see the full name i.e was is hypertension (broad) or hypertension (narrow). 

We dont need this lookup anymore.

![image](https://user-images.githubusercontent.com/13936600/191388721-206c41a6-91e8-42cc-a4f2-f702b4094738.png)


Continuing the enhancement requests: It would be nice if he can for cohort names (when used anywhere in the app), have an ability 
- to hover over the cell and show full name like a tool tip, 
- (we have this now) - dynamically increase width
- allow for multi line names (ie.. wrap text)

**Comment by gowthamrao** [comment]
> I don't have a suggestion for how to enable filtering, except to change checkbox to 'Y'.

Looks like the selection of the table is disabled

**Comment by azimov** [comment]
Issues 1, 2 and 4 have been resolved. 

Issues 3 has now got a cross for the display - one thing to note is this column is filterable with a "TRUE" or "FALSE" in the search. This can also be just T or F:

<img width="1045" alt="Screenshot 2022-09-26 at 1 17 42 PM" src="https://user-images.githubusercontent.com/180659/192371822-3f685c7c-a46c-436a-8b36-0d5a6a2a0739.png">

I've added some text to make this clear

**Comment by gowthamrao** [comment]
On https://data.ohdsi.org/Phenotype_0002_AcutePancreatitis/  **x** is rendering as **+**

![image](https://user-images.githubusercontent.com/13936600/194964220-b764a8f1-ea52-4f0e-933d-04b113c2af41.png)

**Comment by gowthamrao** [comment]
In Cohort Definition tab, on selecting resolved - concepts are not sorted by frequency

![image](https://user-images.githubusercontent.com/13936600/194964410-2e8d5195-7d6b-4b3e-adcd-35babf638977.png)

**Comment by gowthamrao** [comment]
Negative numbers mean less than. i.e. -5 should be shown as < 5, and -10 as < 10. In the past we did this thru html masking - where the values could still be sorted by the underlying value, but the display is < 5, or < 10.

![image](https://user-images.githubusercontent.com/13936600/194964578-71be2c77-3aa6-43d6-bee8-27a9d1193b66.png)

**Comment by gowthamrao** [comment]
I think we should think of a better way to present mapped. In this case, one of the resolved concept id is 195596, 

![image](https://user-images.githubusercontent.com/13936600/194964748-faf3d19a-b5d2-4d0d-a7ea-4a29ad3c79fb.png)

it "mapped to" several concept ids - as shown here
![Uploading image.png…]()

How about a click thru experience. Select a row in resolved, and it opens another table below that shows the mapped concepts and their counts
