### ISSUE TITLE
Cohort Diagnostics All Tabs: Info button does not open

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/CohortDiagnostics#928]
Beside each tab on the left menu, there is a {i} button, which is supposed to open a helper description of the content of the tab.

![image](https://user-images.githubusercontent.com/731930/191135313-2c61e253-fc63-43f5-87a0-42a7ddedad6c.png)

Clicking on the {i} does not open the help.     Suggestion:  each tab should have help description accessible somehow (if not on left tab, then upon open of a tab, via top right-hand corner with {i} or {?} icon.

**Comment by azimov** [comment]
Info button has now been replaced with information in a collapsable tab box for each tab
