### ISSUE TITLE
Time Distributions tab: Suggested enhancements

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/CohortDiagnostics#931]
1.  Time Distributions / Table :   Allow user to show/hide fields. 

![image](https://user-images.githubusercontent.com/731930/191138726-3b236090-4d0e-4cd4-b426-f787b97e6b22.png)

2   Time DIstributions/ Table:  Currently, table lists Cohort and requires 'lookup' to table above display.    Suggestion: Provide cohort name directly in table.

3.  Time DIstributions/ Table:   Min/P10/P25/Median/P75/P90/Max are all integer fields, but formatted as decimal.  Suggest to format at int.

4.  Time DIstributions/ Plot:  database name is rendered extremely small on graph, difficult to read.

5.  Time DIstributions/ Plot:  CohortId listed on y-axis, it would be desirable to have cohort name displayed if possible (also in tooltip).

6.  'Download as CSV', file does not contain cohort names.

**Comment by azimov** [comment]
Changes made in develop branch
