### ISSUE TITLE
Index Event Breakdown:  suggested enhancements

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/CohortDiagnostics#934]
1.   Persons/Records are integer, but formatted as decimal.  Suggest to format as int.

![image](https://user-images.githubusercontent.com/731930/191140264-e6fd9a12-23a2-4905-8e74-7c822d248133.png)

2.  'Download as CSV', only selects filtered rows.   Consider 'Download selected as csv' and 'Download all'.

**Comment by azimov** [comment]
Resolved with other fixes
