### ISSUE TITLE
Inclusion rule statistics - suggested enhancement

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#938]
1. 3.0 output now has the full inclusion rule result set. We can now report both persons and events.  

A UI that shows the impact of inclusion rule with many data sources, is useful to understand the differential impact of the rules by data source. An implementation like this with radio button for persons/events, and a radio button to toggle between raw numbers and percent would be useful.

![image](https://user-images.githubusercontent.com/13936600/191382931-9de73faa-c283-439e-a134-8fe7b6313097.png)

Note: when toggling off show percent, we will need to know the number of persons/event that met the entry event criteria as follows

![image](https://user-images.githubusercontent.com/13936600/191383195-347470bc-3151-4f46-a5cd-2cc8a81030a5.png)

**Comment by gowthamrao** [comment]
Inclusion rule statistics has redundancy in display. It has a standalone menu and is available as drill down experience in cohort count menu. 

suggest having one of them - my preference is cohort count menu

**Comment by azimov** [comment]
Removed inclusion rules tab as it is included in counts. Multiple view sources for the same data is a recipe for error.
