### ISSUE TITLE
Prefer database id over database Name in visuals, tables, drop down menu

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#940]
I suggest we consistently use databaseId uniformly across the shiny app for user selections, reports (plots and tables). 

Reason:

1. databaseId is always unique, databaseName may duplicate.
2. databaseId have stricter requirement e.g. no space or special character. database name does not
3. it is shorter and easier

**Comment by gowthamrao** [comment]
annotation drop downs are showing databaseName. For reasons above, i suggest we use databaseId

https://github.com/OHDSI/CohortDiagnostics/blob/d39d869eececbe04f4df1d999ec176861fae02e8/inst/shiny/DiagnosticsExplorer/R/Annotation.R#L157

**Comment by azimov** [comment]
The database ID (can, and will) be an integer for stratgeus purposes. In future versions using a clear and unique database name is recommended.
