### ISSUE TITLE
Bug in retrieving resolvedConcepts - is pointing to orphan concept 

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#941]
https://github.com/OHDSI/CohortDiagnostics/blob/d39d869eececbe04f4df1d999ec176861fae02e8/inst/shiny/DiagnosticsExplorer/R/Results.R#L574

**Comment by azimov** [comment]
No steps to reproduce

**Comment by gowthamrao** [comment]
Looks like you fixed it https://github.com/OHDSI/CohortDiagnostics/blob/84c8ece0fb2e52d1d8fdc1850595ce3e948036f7/inst/shiny/DiagnosticsExplorer/R/Results.R#L642
