### ISSUE TITLE
Retrieval of results for resolved, mapped, orphan - seem to be incorrect

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#942]
Sorry @azimov but there are many issues. I think if you can please compare the code here https://github.com/gowthamrao/CohortDiagnostics/blob/execute2/inst/shiny/DiagnosticsExplorer/R/Results.R to the code in develop it would be easier.

But some summary

- we shouldnt have an inner join here, because it is possible that there will be mismatch between resolved concepts and concept table example https://github.com/OHDSI/CohortDiagnostics/issues/907
![image](https://user-images.githubusercontent.com/13936600/191391071-abdc8c63-db4f-4cf7-816c-aea14cfc46c5.png)

- is pointing to the wrong table
![image](https://user-images.githubusercontent.com/13936600/191391205-c7a23571-91c0-4897-81ed-d97dea46d31d.png)

- not sure why the complexiting in resolved concepts here. i think it explains why it is taking so long to retrieve

![image](https://user-images.githubusercontent.com/13936600/191391302-7d109153-dcc0-4903-8f73-4149496bacde.png)

**Comment by azimov** [comment]
Issue #921. You commented on it less than half an hour ago

**Comment by azimov** [comment]
Moved comment to relevant issue
