### ISSUE TITLE
Cohort Definition tab :  multiple rows per code appearing in Mapped tab under Conceptset

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/CohortDiagnostics#945]
Cohort Definition tab,  select cohort, go to Concept Sets,  select conceptset, click 'Mapped' button.    Re: below:

![image](https://user-images.githubusercontent.com/731930/192118017-c7d5376b-2e31-4563-aced-17baeb77b3c2.png)

You'll notice there are 4 rows per source_concept_id, each with the same content in all rows.    So, I suspect there needs to be DISTINCT on the query that's missing to consolidate the records.

**Comment by azimov** [comment]
Fixed in develop branch
