### ISSUE TITLE
Cohort Counts tab:   database dropdown doesnt appear to select appropriate databases

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/CohortDiagnostics#946]
![image](https://user-images.githubusercontent.com/731930/192120260-a346f33a-ee05-448e-b7f5-d9c35de1b394.png)

When toggling between databases in the Database dropdown on the lefthand menu, and selecting databases, the results do not show up for all selected databases.

When I select all databases, only a subset of databases get displayed  (as if there was a filter set somewhere else that wasn't reset).

![image](https://user-images.githubusercontent.com/731930/192120289-631a2b10-24d2-45c7-a0d4-59b9022eb59a.png)

In this screenshot, you see all databases selected, but only 5 databases appear (even when I right horizontal scroll).

When I refresh the app completely. go Cohort Counts, select all databases, it again limits to only the first 5 databases.

If I deselect all, and purposefully select the last 5 in the list, then no databases get displayed:

![image](https://user-images.githubusercontent.com/731930/192120345-420188f7-6685-4135-9c02-a1f75bf44f10.png)

So, I wonder if somewhere there is a limit among the first 5 databases in some selector?

Note, I'm seeing this same experience on other tabs, so I think the database filter that is consistent across 'Orphan concepts', 'Cohort Counts', 'Incidence Rate', 'Time Distribution', 'Index Event Breakdown', 'Visit context', and 'Cohort Overlap' may be directly impacted by this issue.

**Comment by pbr6cornell** [comment]
I'm experiencing inconsistent behavior with this error.  Cant always reproduce it.  But appeared to be that one tab's database dropdown has cached a subset of values and the other tab honored it.

**Comment by azimov** [comment]
Fixed database dropdown, however, more user testing is required as behaviour may not perform well in certain situations
