### ISSUE TITLE
Incidence Rate tab:   'Minimum person years' changes reset values in other Filters

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/CohortDiagnostics#947]
In the Incidence Rate tab, the user must select values from stratify by checkboxes (age/sex/calendar year), dropdowns for 'filter by age', 'filter by sex', and slider for 'filter by calendar year', in addition to setting 'minimum person years' and 'minimum subject count':

![image](https://user-images.githubusercontent.com/731930/192120709-53ce9c04-46c4-4d7b-9530-920ba1097ec4.png)

It appears that the 'filter by age' and 'filter by sex' options are somehow dependent on the value specifed in the 'minimum person years field'.   Note, when i change minimum person years = 0, the filter by age choices expands to include other age groups:

![image](https://user-images.githubusercontent.com/731930/192120748-a61cc20f-5203-40ca-a483-24dcd9cec92f.png)

If I increase 'minimum person years' to 100000, both filter by age and filter by sex offer fewer options:

![image](https://user-images.githubusercontent.com/731930/192120811-c5297040-8e52-4da5-9387-ca79ef26d698.png)

The challenge with this is that if you make selections in the 'filter by age' and 'filter by sex' dropdowns, and then change the 'minimum person years' value, then the selections you made in the filter dropdowns are reset and you have to go back and correct them.

Suggestion:  don't have the filters dependent on the minimum person years.  Make dropdown fixed based on all available options assuming minimum = 0, and then it doesn't need to refresh when the value changes.

**Comment by pbr6cornell** [comment]
Note, it appears the 'filter by age' and 'filter by sex' dropdowns also reset when you change the 'Stratify by' checkboxes.    Suggestion to remove that reset also so that user selections are preserved.

**Comment by pbr6cornell** [comment]
whoops, didn't mean to close this.  still persists

**Comment by azimov** [comment]
Resolved in develop branch
