### ISSUE TITLE
Vignette - for running cohort diagnostics in package mode

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#95]
We need a vignette to run cohort diagnositcs in package mode

**Comment by ablack3** [comment]
I think there is a user story that would be good to cover in this or another vignette:

> "As a researcher with access to Atlas I want to run cohortDiagnostics on a cohort I created in Atlas so I can evaluate the quality of my cohort definition. I am not able to programmatically interact with WebAPI due to security restrictions in my institution and am not an R package developer. I can run SQL against my CDM from R though."

**Comment by gowthamrao** [comment]
https://github.com/OHDSI/CohortDiagnostics/pull/345/commits/43913ce3d69694fe85ff02b29312f90ea633446f
