### ISSUE TITLE
Compare Chararacterization:  StDiff enhancements

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/CohortDiagnostics#950]
Two items on standardized difference:

1.   All StDiff values should be listed with 2 decimals. currently we only show 1 decimal point:
![image](https://user-images.githubusercontent.com/731930/192122837-0e02a559-4022-4052-b695-10463ab66df0.png)

2.  If target or comparator has 0%, but the other cohort has a value >0%, we should be able to compute StDiff.   Currently, StDiff is NULL in these cases:   (need to coalesce the null cohort to have mean = 0, stdev = 0, then the standard StDiff formula will be fine).

![image](https://user-images.githubusercontent.com/731930/192122850-bd6d1dbf-94a3-40b5-9bb8-1f65f7515365.png)

**Comment by pbr6cornell** [comment]
Note, I think this may be specifically influenced by the 'Min Covariate Mean' user input parameter.  It could be there is non-zero values that just fall below the threshold.

**Comment by azimov** [comment]
The calculation has been fixed as per screenshot below: 
<img width="1327" alt="Screenshot 2022-09-26 at 10 23 54 AM" src="https://user-images.githubusercontent.com/180659/192341653-835eaf5c-fe29-4056-99ef-5eae945f07c9.png">

however, I'm keeping this issue open as currently the operation is slow as legacy code pulls down data the target and comparator separately - Instead it would be significantly more performant to pull it down for both doing the standard diff calculation in SQL.
