### ISSUE TITLE
Inclusion rules - disconnect between selected cohort and reported cohorts

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#953]
In this example

![image](https://user-images.githubusercontent.com/13936600/193068015-546383f5-81c9-4f1b-8dd6-ea7039b4d039.png)

selected cohort is 9016
reported cohrot are something else

**Comment by gowthamrao** [comment]
This is now fixed

**Comment by gowthamrao** [comment]
I think this bug is back after this change
https://github.com/OHDSI/CohortDiagnostics/commit/cb80fa70f0694ed7b3029e889e4bdf13163f9cbe

**Comment by gowthamrao** [comment]
See disconnect

![image](https://user-images.githubusercontent.com/13936600/195488801-94705454-09da-4931-ab9b-22fb436074e8.png)

**Comment by azimov** [comment]
This was caused when sorting columns in tables grouped by database id, which is now disabled again in this case. We can revisit this in a future version if we need sortabity in the tables
