### ISSUE TITLE
Inclusion rule - person event missing

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#954]
Missing here

![image](https://user-images.githubusercontent.com/13936600/193070642-fc3baf66-a3af-48f1-b041-3e52b368d989.png)

Present here

![image](https://user-images.githubusercontent.com/13936600/193070708-da5ed4ac-9836-4aa9-9eb8-bc2dea6c4bf5.png)

**Comment by azimov** [comment]
Removed tab
