### ISSUE TITLE
Concepts in Data Source tab:  selecting conceptset from dropdown throws error

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/CohortDiagnostics#960]
Concepts in data source tab,  select all databases, select Guillan Barre cohort.  Table looks ok:

![image](https://user-images.githubusercontent.com/731930/193975139-156a9d24-d6eb-4a68-a38f-05e1de3cf5cd.png)

But select any conceptsets from the dropdown on the lower left, and you recieve an error:

![image](https://user-images.githubusercontent.com/731930/193975205-9271c7bd-8094-400b-8604-d08948e53ef3.png)

deselecting the conceptsets returns the table to its original state.

**Comment by azimov** [comment]
Fixed in develop branch
