### ISSUE TITLE
Time distribution tab:  value for max=-5 distorts graph

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/CohortDiagnostics#964]
Time distribution tab, all times should be positive.   However, in screenshot below, Max = -5, which creates an odd boxplot:

![image](https://user-images.githubusercontent.com/731930/193979921-aeb223f7-26c4-4334-a389-dd29c66b84b8.png)

I'm not sure why max = -5, but if small cell counts are being censored, then presumably the other values shoudl also be censored, or outright removed, and not plotted.

**Comment by azimov** [comment]
This is tricker to fix than at first glance. Max will be -5 because of non-identifiable data rules.

**Comment by gowthamrao** [comment]
In past we have used absolute values to solve this. An alternate option is to replace the negative value with next neighbor valid percentile value

**Comment by azimov** [comment]
SHould now be fixed in OhdsiShinyModules package as plot has been moved to plotly
