### ISSUE TITLE
Remove forced filtering of analysisId

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#967]
https://github.com/OHDSI/CohortDiagnostics/blob/b8ad6d30f1766645a1c69faa57632379eefdc34e/inst/shiny/DiagnosticsExplorer/R/StartUpScripts.R#L467-L472

**Comment by gowthamrao** [comment]
With the changes to the UX (i.e. no separation of temporal vs non temporal) this would be not applicable. This was applicable when a previous thought was to present different characterization output based on characterization vs temporal characterization.

**Comment by gowthamrao** [comment]
I think this may be considered a BUG now. 

Justification - if i run cohort diagnostics with custom feature extraction specification (i.e. 
    useVisitCount  = TRUE, 
    useVisitConceptCount = TRUE 
 instead of getDefaultCovariateSettings)

The output has visit domain related covariate output
![image](https://user-images.githubusercontent.com/13936600/194641806-61330755-bdb3-4c7a-9993-fd74f2862787.png)

The shiny app doesnt
![image](https://user-images.githubusercontent.com/13936600/194641912-ecd161a8-c7aa-4924-a037-fd6cec1d24af.png)

**Comment by azimov** [comment]
Removed hard coding in develop branch
