### ISSUE TITLE
Prevalence/Incidence over time:  exploring data by month

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/CohortDiagnostics#97]
Currently, we plot incidence over time in units of years on x-axis.   In our COVID work, where all data is in 2020, this causes some less-than-pretty artifacts on the graphs, but that's understandable given that theres only one year.    It may be useful to consider as a future enhancement, whether we let user specify the time unit (e.g. months or years), or perhaps since its cheap enough to compute, just add a incidence per month plot (akin to what's already available in ACHILLES).    In the case of COVID, seeing prevalence and incidence by month may have been more informative for phenotype evaluation (e.g. seeing the cases in Jan/Feb, which are less plausible than those in Mar onward).   Potentially this also allows for viewing the data to determine if there a seasonal pattern that is expected or not.

**Comment by cgreich** [comment]
Actually, we need that in ATLAS. The EMA complained about the absence of exactly this. Probably not the right place to ask  this, but how are the two going to jive?

**Comment by gowthamrao** [comment]
@anthonysena - implementing this functionality will need change in the results data model. Current implementation use year
![image](https://user-images.githubusercontent.com/13936600/89775710-66286000-dad6-11ea-92e8-d535e92ccdb8.png)


To add month we have to change this structure. When we change, I think we should use timeseries structure recommended by [tidyverts/tsibble ](https://tsibble.tidyverts.org/)

```
In tsibble:
Index is a variable with inherent ordering from past to present.
Key is a set of variables that define observational units over time.
Each observation should be uniquely identified by index and key.
Each observational unit should be measured at a common interval, if regularly spaced.
```

This would allow us to easily use the functionality of packages in tidyverts for timeseries

![image](https://user-images.githubusercontent.com/13936600/89775814-9243e100-dad6-11ea-8ccd-d4562336c10a.png)

**Comment by gowthamrao** [comment]
working on timeseries for version 2.2
