### ISSUE TITLE
Orphan concepts - unknown error

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#972]
To reproduce - go to orphan concepts on this app

https://data.ohdsi.org/Phenotype_0002_AcutePancreatitis/

to see this error message

![image](https://user-images.githubusercontent.com/13936600/194932838-01d3ae2e-dad6-46b4-a18e-c14737a17344.png)

**Comment by azimov** [comment]
Issue with duplicate data - fixed this in develop branch but possibly a problem when executing with this data set
