### ISSUE TITLE
inclusion_rule_stats table in sql but not in resultsDataModelSpecification

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#979]
https://github.com/OHDSI/CohortDiagnostics/blob/cb80fa70f0694ed7b3029e889e4bdf13163f9cbe/inst/sql/sql_server/CreateResultsDataModel.sql#L354-L366

related to https://github.com/OHDSI/CohortDiagnostics/issues/978

**Comment by azimov** [comment]
should be in data model (inclusion rules now conform to CohortGenerator standard not the old cd table)
