### ISSUE TITLE
Add (optional) grid lines to incidence rate plot

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#98]
Incidence rate plot may benefit from having grid lines (darker major, barely visible minor ticks)
https://github.com/OHDSI/CohortDiagnostics/blob/master/vignettes/shiny.png

**Comment by schuemie** [comment]
There are already the default ggplot grid lines (white on gray). Are you saying you don't like those?

**Comment by gowthamrao** [comment]
Interesting - this seems to be some rendering issue. E.g. on my computer monitor, i dont see it

![image](https://user-images.githubusercontent.com/13936600/87948727-11636d80-ca73-11ea-9229-ef020a767414.png)

**Comment by gowthamrao** [comment]
not reproducible
