### ISSUE TITLE
Non SqlRender-friendly formatting of CreateConceptIdTable.sql - generates error 

### ISSUE THREAD

**Issue by rtmill** [OHDSI/CohortDiagnostics#981]
Unlike most of the drop and create SQL snippets in here, this one isn't in the format supported by SqlRender. Throws error during execution using sql server. 

Error Output:
```
DBMS: sql server
Error: com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near the keyword 'IF'.
SQL:   DROP TABLE IF EXISTS #concept_ids
```

Current code: 
```
DROP TABLE IF EXISTS @table_name;
CREATE TABLE @table_name (concept_id INT);
```

Suggested edit:
```
(if parameterization is needed)
IF OBJECT_ID('@table_name', 'U') IS NOT NULL 
    DROP TABLE @table_name;
CREATE TABLE @table_name (concept_id INT);

(if static) 
IF OBJECT_ID('#concept_ids', 'U') IS NOT NULL 
    DROP TABLE #concept_ids;
CREATE TABLE #concept_ids (concept_id INT);
```

**Comment by gowthamrao** [comment]
Hi @rtmill  this may be related to https://github.com/OHDSI/SqlRender/issues/306

**Comment by azimov** [comment]
Unrleated to CohortDiagnostics please see [DatabaseConnector issue](https://github.com/OHDSI/DatabaseConnector/issues/204). However, it is unlikely that we will support versions of MS Sql Server this old as we don't have any test infrastructure to do this.
