### ISSUE TITLE
Characterization data not displayed on local sqlite db

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#983]
Today at the OHDSI tutorial the shiny app did not display results. 

![image](https://user-images.githubusercontent.com/13936600/196003649-bc1367a9-8393-4ab7-a3d8-634cc355ea6d.png)

I do not know why it happened - i was running the release candidate version in develop branch

**Comment by azimov** [comment]
This issue should be resolved in the latest version - please post any further Shiny app related issues on OhdsiShinyModules
