### ISSUE TITLE
emtpy cohorts don't show up

### ISSUE THREAD

**Issue by eldarallakhverdiiev** [OHDSI/CohortDiagnostics#985]
Expected behavior:
When one of the cohorts has 0 records,  cohort is shown in the lists of cohort definitions and inclusion rule statistics is available

Current behavior:
Cohort is completely missing from cohort diagnostics results

**Comment by azimov** [comment]
Hi @eldarallakhverdiiev the way inclusion rules are calculated is during the cohort generation step in cohort generator. If the cohorts are empty then no inclusion rules stats will be generated. It is also possible that a cohort has no inclusion rules, and therefore not inclusion rule stats.

In the coming release, the inclusion rules table will be included in the cohort counts tab of the module - this will make it clearer that the reason for no rules is a zero count
