### ISSUE TITLE
tidyselect 1.2.0 warning on develop branch diagnostic explorer

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#992]
> Warning: Use of .data in tidyselect expressions was deprecated in tidyselect 1.2.0.

Looks like `.data$` is disliked now

**Comment by azimov** [comment]
This was actually resolved [this morning,] (https://github.com/OHDSI/CohortDiagnostics/commit/e0a897ca2d2e184d5525934b6ecd5e13100af7ed)

I think I got all of them.

**Comment by gowthamrao** [comment]
Then do we have to update the min tidy select version?
