### ISSUE TITLE
error is.character(databaseSchema) is not TRUE

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#997]
https://github.com/OHDSI/CohortDiagnostics/blob/5660d147da391dea76a9c77655513dbb94ff2b55/R/DataSourceInformation.R#L52-L55

(if i comment out this line - everythign worked fine)

Gives me this error - which i dont understand 

> 
> Message:  is.character(databaseSchema) is not TRUE
> Level:  FATAL
> Time:  2022-11-11 14:51:52

> Stack trace:
> 13: (function (e) 
> {
>     ParallelLogger::logFatal(conditionMessage(e))
>     stop(e)
> 
> 12: stop(simpleError(msg, call = if (p <- sys.parent(1)) sys.call(p)))
> 11: stopifnot(is.character(databaseSchema), length(databaseSchema) == 1, DBI::d
> 10: getTableNames(connection, databaseSchema)
> 9: existsTable(connection = conn, databaseSchema = databaseSchema, tableName =
> 8: .local(conn, name, ...)
> 7: DatabaseConnector::dbExistsTable(conn = connection, name = "cdm_source")
> 6: DatabaseConnector::dbExistsTable(conn = connection, name = "cdm_source")
> 5: getCdmDataSourceInformation(connection = connection, cdmDatabaseSchema = cd
> 4: eval(expr)
> 3: timeExecution(exportFolder, taskName = "getCdmDataSourceInformation", cohor
> 2: CohortDiagnostics.R#139: CohortDiagnostics::executeDiagnostics(cohortDefini

When i debug it

> 
> debugging in: DatabaseConnector::dbExistsTable(conn = connection, name = "cdm_source")
> debug: {
>     ans <- standardGeneric("dbExistsTable")
>     .valueClassTest(ans, "logical", "dbExistsTable")
> }
> Browse[4]> n
> debug: ans <- standardGeneric("dbExistsTable")
> Browse[4]> n
> Error in getTableNames(connection, databaseSchema) : 
>   is.character(databaseSchema) is not TRUE

**Comment by azimov** [comment]
Not sure why this code is failing for you now but its using very old DatabaseConnector code that isn't exposed in its API. PR incoming

**Comment by azimov** [comment]
Fixed in develop branch
