### ISSUE TITLE
Filter concept name by using regular expression

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#998]
A very powerful function in CohortExplorer is the use of regular expressions to filter a table. 

We can have a text box where a user may put in a regular expression. the regular expression then filters a table with concept name as follows 

`    data[grepl(input$filterRegex, data$conceptName, ignore.case = TRUE),]`

**Comment by azimov** [comment]
Closing due to age and that this is now Ohdsi Shiny modules related UI issue
